---
- name: strip patch version from k8s version
  set_fact:
    k8s_version_stripped: "{{ k8s_version | regex_replace('^(\\d+\\.\\d+)\\.\\d+$', '\\1') }}"

- name: add signing key for k8s repo
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_stripped }}/deb/Release.key"
    dest: "/etc/apt/keyrings/kubernetes-v{{ k8s_version_stripped }}.asc"

- name: add k8s repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-v{{ k8s_version_stripped }}.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_stripped }}/deb/ /"
    state: present

- name: add signing key for docker repo
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: add docker repo
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: install k8s core dependencies
  apt:
    pkg:
      - "kubelet={{ k8s_version }}-*"
      - "kubeadm={{ k8s_version }}-*"
    state: present
    allow_change_held_packages: true # here be dragons
  notify: restart kubelet

- name: install containerd
  apt:
    pkg:
      - "containerd.io>={{ containerd_version }}"
    state: present
    allow_change_held_packages: true # here be dragons
  register: containerd_install

- name: install CRI tools
  apt:
    pkg:
      - "cri-tools={{ k8s_version_stripped }}.*"
    state: present
    allow_change_held_packages: true # here be dragons

- name: mark k8s core dependencies as hold
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - containerd.io
    - cri-tools

- name: enable IPv4 and IPv6 packet forwarding
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
  with_items:
    - name: net.ipv4.ip_forward
      value: '1'
    - name: net.ipv6.conf.all.forwarding
      value: '1'
    - name: net.ipv6.conf.all.accept_ra
      value: '2'

- name: get node suffix from IPv4 address
  set_fact:
    node_suffix: "{{ ansible_default_ipv4.address.split('.')[-1] }}"

- name: configure k8s IPv6 ULA subnet
  template:
    src: 60-k8s-ipv6.yaml.j2
    dest: /etc/netplan/60-k8s-ipv6.yaml
    mode: '0640'
  register: netplan_config

- name: apply netplan configuration
  command: netplan apply
  when: netplan_config.changed
  changed_when: true

- name: ensure /etc/containerd directory exists
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: generate default containerd config
  command: containerd config default
  register: containerd_config
  changed_when: false

- name: modify containerd config
  set_fact:
    modified_containerd_config: "{{ containerd_config.stdout | regex_replace('SystemdCgroup = false', 'SystemdCgroup = true ') }}"

- name: write modified containerd config to file
  copy:
    content: "{{ modified_containerd_config }}"
    dest: /etc/containerd/config.toml
  notify: restart containerd

- name: configure kubelet IPs
  copy:
    dest: /etc/default/kubelet
    content: |
      Environment="KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }},{{ ula_prefix }}{{ node_suffix }}"
  notify:
    - reload systemd daemon
    - restart kubelet

- meta: flush_handlers
