apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: jetstack
    namespace: cert-manager-system
spec:
    url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: cert-manager-system
spec:
    interval: 1m
    chart:
        spec:
            chart: cert-manager
            version: v1.16.2
            sourceRef:
                kind: HelmRepository
                name: jetstack
                namespace: cert-manager-system
    values:
        crds:
            enabled: true
