---
creation_rules:
  - path_regex: ansible/.*\.sops\.ya?ml
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/infrastructure/controllers/external-dns\.sops\.ya?ml
    encrypted_regex: "^.*(provider|extraArgs)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/infrastructure/configs/cert-manager\.sops\.ya?ml
    encrypted_regex: "^.*(email|api-token)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/apps/controllers/dex\.sops\.ya?ml
    encrypted_regex: "^.*(values|subjects)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/apps/controllers/longhorn\.sops\.ya?ml
    encrypted_regex: "^.*(host|hostname)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
