---
creation_rules:
  - path_regex: ansible/.*\.sops\.ya?ml
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/secrets/.+\.sops\.ya?ml
    unencrypted_regex: "^(apiVersion|kind|metadata|type)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/apps/nextcloud\.sops\.ya?ml
    encrypted_regex: "^.*(host|hosts|trustedDomains|fromAddress|domain|smtp|password|path|mountPath)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/apps/pihole\.sops\.ya?ml
    encrypted_regex: "^.*(hosts|whitelist)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/apps/bitwarden\.sops\.ya?ml
    encrypted_regex: "^.*(password|value|domain|smtp|hostname)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/apps/paperless\.sops\.ya?ml
    encrypted_regex: "^.*(password|PAPERLESS_URL|PAPERLESS_SECRET_KEY|PAPERLESS_DBPASS|hosts)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/apps/unifi\.sops\.ya?ml
    encrypted_regex: "^.*(auth|extraEnvVars|env|hosts)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
