---
creation_rules:
  - path_regex: ansible/.*\.sops\.ya?ml
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/system/infrastructure-controllers/external-dns\.sops\.ya?ml
    encrypted_regex: "^.*(env)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/system/infrastructure-configs/cert-manager\.sops\.ya?ml
    encrypted_regex: "^.*(email|api-token)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/system/app-configs/dex\.sops\.ya?ml
    encrypted_regex: "^.*(values|subjects)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/system/app-configs/longhorn\.sops\.ya?ml
    encrypted_regex: "^.*(host|hosts)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
  - path_regex: flux/system/app-controllers/democratic-csi\.sops\.ya?ml
    encrypted_regex: "^.*(config)$"
    age: >-
      age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp

