apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: democratic-csi-ssd
    namespace: democratic-csi-system
spec:
    interval: 1m
    chart:
        spec:
            chart: democratic-csi
            version: 0.14.7
            sourceRef:
                kind: HelmRepository
                name: democratic-csi
                namespace: democratic-csi-system
    values:
        csiDriver:
            name: nas-ssd
            fsGroupPolicy: File
        storageClasses:
            - name: nas-scratch-ssd
              defaultClass: false
              reclaimPolicy: Delete
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                fsType: nfs
              mountOptions:
                - noatime
                - nfsvers=3
        driver:
            config:
                driver: ENC[AES256_GCM,data:VlBGOic6nZbqUhA=,iv:6bL50w02vYx7/tMxf+MEj3WqRDF4LiGgrclIRzDeElU=,tag:+UPj4Xz0QpAS7qyW2KsAGg==,type:str]
                instance_id: null
                httpConnection:
                    protocol: ENC[AES256_GCM,data:yhoEsA==,iv:46C11HeaBqKmuqhTCSaSMuCNhyhsBxJxL2xc7hLNuqA=,tag:xJmcvYz55x+TBzqlz0laeA==,type:str]
                    host: ENC[AES256_GCM,data:Qd8OjOPPZy+akOo=,iv:sPFz9fAQhm0sv63mOPBTEKxCta1fIrHnN6bVGgiGp64=,tag:YC/DHultJla6GBVJEN48OQ==,type:str]
                    port: ENC[AES256_GCM,data:NPE=,iv:6nT7eW2Da4St7u+YPwWDzgF/MIZEMIUsvKZkHVU/3pg=,tag:J0O5J1CC771BZzoBFr7Sqg==,type:int]
                    username: ENC[AES256_GCM,data:FHxV+Q==,iv:n/4Dr4b5XNQauUGjabqc8mfBnLdudyXKzN+N9SPm/5E=,tag:1deX3K1Ij5V9/fiy95cunA==,type:str]
                    password: ENC[AES256_GCM,data:9pv65/BqblvL8DlbNaFTbPs50w==,iv:raY/RHBCypvvmVC/U14ohft6YwMz5d2rVccR8kTjHrk=,tag:Fob6J9VtN5emz0S0fkrrpw==,type:str]
                    allowInsecure: ENC[AES256_GCM,data:bCgeiw==,iv:1ChItt584iCSrSH3iER6g2V0rzNpVe8sNnWDX8bOF1o=,tag:SX20TIATzOpk848tNtoY6Q==,type:bool]
                sshConnection:
                    host: ENC[AES256_GCM,data:iKSeRP8kikGxfdo=,iv:jec7rGONe0Cp7LK/6+To+lnrPJ3SqxUn3aMYsK25aek=,tag:BXq2XNnwBZsBHu/W8o0fmA==,type:str]
                    port: ENC[AES256_GCM,data:vd0=,iv:it5VDdoQU2a+FGfIdT3rSQjCrTn34a2WYdPSY3aWSGQ=,tag:owIqa3XsLpAcO4UQVubCkw==,type:int]
                    username: ENC[AES256_GCM,data:+m3jJw==,iv:VV8qj6LzzYjLv+xUMlWrvkjUAg4cSai1axA9HE/sA/U=,tag:vVRKJPBskyJC9497aAfm2g==,type:str]
                    password: ENC[AES256_GCM,data:NUr4TYuWpiW+0YikZqsH9wInEg==,iv:vYC2M3Ueg3hnOQruguzJvKOTFTKqr7nYvZLkxfHLlV4=,tag:xoMFkzmQClM50vZMBFAr6A==,type:str]
                zfs:
                    datasetParentName: ENC[AES256_GCM,data:VD65JLrjcxDhG8c=,iv:+jT6Tj7XnD74x+wOf3TQ7R0Mog/cPP6PDGuBmSEVu/E=,tag:rHwk5HDj3DNtH5pLj0QGwQ==,type:str]
                    detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:C2tC0wnYv0jV6TIPTQ==,iv:OjDl+ca8RM4k5c7wCq81zVmi8VDpaPXdimZAkJlDar4=,tag:MPzsxKQ11XYl3LHOgW50ow==,type:str]
                    datasetEnableQuotas: ENC[AES256_GCM,data:elkG7w==,iv:ELOWngHnXxchRbwafeN6X+Mu8berQ60z6T0NNekNwg4=,tag:9CErgBilubKMqc1UOR/lpw==,type:bool]
                    datasetEnableReservation: ENC[AES256_GCM,data:nZMyIEI=,iv:RotIMMGs62d8F8Wj4F2evZhagz8X6M2holFZudR2MaQ=,tag:XHqH4EthUqPxZyzbEAZ8lw==,type:bool]
                    datasetPermissionsMode: ENC[AES256_GCM,data:9/Hsbg==,iv:9vu1X8IFc+jjwPhu/bOJGrqVKBBk9dM456WB3YQAHPs=,tag:gOzmxWMXbczWz20FXyGp8w==,type:str]
                    datasetPermissionsUser: ENC[AES256_GCM,data:kQ==,iv:UGc6LPlY58VNGeFBcFpEuRTtLPeFoZUndyOatCu1YHQ=,tag:FFx/owCDWKKMarGRgOKEog==,type:int]
                    datasetPermissionsGroup: ENC[AES256_GCM,data:hQ==,iv:sWUVeca9yMwbk+YFPf7frm9YK06xqgHwJWHFOPZwVro=,tag:KV/q3HdHzqlTUni0Qd2osw==,type:int]
                nfs:
                    shareHost: ENC[AES256_GCM,data:vdEac2yJMw/CWhI=,iv:oG0H6txPppOMrSqkrLffnMrkJQ/pqG+T77O7DNz070E=,tag:d1VKYPrviTzFZ0b/+WJIoQ==,type:str]
                    shareAlldirs: ENC[AES256_GCM,data:WM7lH1c=,iv:Or0/uITW12qUgzSi10StAvVQEoc0fi+wAd6P/Wl/Il4=,tag:otRaFECWzzvk3A0Z+xCcTA==,type:bool]
                    shareMaprootUser: ENC[AES256_GCM,data:8c7Olg==,iv:Dc9uipdNySYEYQJ0mEm/r3rArfPf7sWJPZ4czqTqhsc=,tag:JIh6nrn67n7ERtmjwsI4Hg==,type:str]
                    shareMaprootGroup: ENC[AES256_GCM,data:+RkPjRs=,iv:biqB07QCTDvxvgsP1gwduPNXAMAblQLNAXzAQNCifvg=,tag:L8ONmyr2IIj3v3J/3PLISA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTGEycHVONHZ1VmU4OWVP
            dkFoSWVjTVNjMFJvb2dPVXlneWJpVTlBVFFJCmU4Sy91TTVwRG5URVpIelk2ckxZ
            Q0E1UEdjUlRoNDZxOTUvYUdrWGVqQ1kKLS0tIFRVWFdTNmxDUC9GNW5zYlVLN21y
            WDdtMzhHMVh6dXNGanZCbktnN2hsNGMKg7d1rSorqJ25l/Qdnk6v5S1LhGEzAH5e
            65nRi7rB6k3iKpp3xku5cHMYunrWjwRPrRLoobd3ETOyeMpEK7LDdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T16:10:07Z"
    mac: ENC[AES256_GCM,data:1w4sOt5p9G7gdSjJx2N8stwTejoXiZ+IrpKdW+rX7sZiJccdEispoKI2vhEvblLcyooK7Fd8+Ip+qkkdzY3qC0uJFrbQ8Gy5uUHTv/RtqDLfeu3vpIybpvhloliU4pUHviBB9ep/JssEcZz7owijDNLMr7AkWE5G/roxP7UQOT4=,iv:3RDYTntIeWKx1eXwfzxTtH4QkX+E9VSeCo1jiG/xSK8=,tag:E13niMcWjYgzSIi955h6JA==,type:str]
    pgp: []
    encrypted_regex: ^.*(config)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: democratic-csi-hdd
    namespace: democratic-csi-system
spec:
    interval: 1m
    chart:
        spec:
            chart: democratic-csi
            version: 0.14.7
            sourceRef:
                kind: HelmRepository
                name: democratic-csi
                namespace: democratic-csi-system
    values:
        csiDriver:
            name: nas-hdd
            fsGroupPolicy: File
        storageClasses:
            - name: nas-replicated-hdd
              defaultClass: false
              reclaimPolicy: Retain
              volumeBindingMode: Immediate
              allowVolumeExpansion: true
              parameters:
                fsType: nfs
              mountOptions:
                - noatime
                - nfsvers=3
        driver:
            config:
                driver: ENC[AES256_GCM,data:VlBGOic6nZbqUhA=,iv:6bL50w02vYx7/tMxf+MEj3WqRDF4LiGgrclIRzDeElU=,tag:+UPj4Xz0QpAS7qyW2KsAGg==,type:str]
                instance_id: null
                httpConnection:
                    protocol: ENC[AES256_GCM,data:yhoEsA==,iv:46C11HeaBqKmuqhTCSaSMuCNhyhsBxJxL2xc7hLNuqA=,tag:xJmcvYz55x+TBzqlz0laeA==,type:str]
                    host: ENC[AES256_GCM,data:Qd8OjOPPZy+akOo=,iv:sPFz9fAQhm0sv63mOPBTEKxCta1fIrHnN6bVGgiGp64=,tag:YC/DHultJla6GBVJEN48OQ==,type:str]
                    port: ENC[AES256_GCM,data:NPE=,iv:6nT7eW2Da4St7u+YPwWDzgF/MIZEMIUsvKZkHVU/3pg=,tag:J0O5J1CC771BZzoBFr7Sqg==,type:int]
                    username: ENC[AES256_GCM,data:FHxV+Q==,iv:n/4Dr4b5XNQauUGjabqc8mfBnLdudyXKzN+N9SPm/5E=,tag:1deX3K1Ij5V9/fiy95cunA==,type:str]
                    password: ENC[AES256_GCM,data:9pv65/BqblvL8DlbNaFTbPs50w==,iv:raY/RHBCypvvmVC/U14ohft6YwMz5d2rVccR8kTjHrk=,tag:Fob6J9VtN5emz0S0fkrrpw==,type:str]
                    allowInsecure: ENC[AES256_GCM,data:bCgeiw==,iv:1ChItt584iCSrSH3iER6g2V0rzNpVe8sNnWDX8bOF1o=,tag:SX20TIATzOpk848tNtoY6Q==,type:bool]
                sshConnection:
                    host: ENC[AES256_GCM,data:iKSeRP8kikGxfdo=,iv:jec7rGONe0Cp7LK/6+To+lnrPJ3SqxUn3aMYsK25aek=,tag:BXq2XNnwBZsBHu/W8o0fmA==,type:str]
                    port: ENC[AES256_GCM,data:vd0=,iv:it5VDdoQU2a+FGfIdT3rSQjCrTn34a2WYdPSY3aWSGQ=,tag:owIqa3XsLpAcO4UQVubCkw==,type:int]
                    username: ENC[AES256_GCM,data:+m3jJw==,iv:VV8qj6LzzYjLv+xUMlWrvkjUAg4cSai1axA9HE/sA/U=,tag:vVRKJPBskyJC9497aAfm2g==,type:str]
                    password: ENC[AES256_GCM,data:NUr4TYuWpiW+0YikZqsH9wInEg==,iv:vYC2M3Ueg3hnOQruguzJvKOTFTKqr7nYvZLkxfHLlV4=,tag:xoMFkzmQClM50vZMBFAr6A==,type:str]
                zfs:
                    datasetParentName: ENC[AES256_GCM,data:Kl290yhVQHr+zHWiklmIhw==,iv:yNN2zOPzLU+/sHKZB7xR2Ka9H2qLo/7gbvo9JnZFIYM=,tag:6LTqXy5etMWNMRk3ZSkwDg==,type:str]
                    detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:vtASzeqFKoZ1+snC13c5F1p/,iv:HeroHVDslj8izvI+wAUASFWqfqZMTEBI1lwOqvOcGmo=,tag:nPRxrevV2xCYPMZMfapmCQ==,type:str]
                    datasetEnableQuotas: ENC[AES256_GCM,data:elkG7w==,iv:ELOWngHnXxchRbwafeN6X+Mu8berQ60z6T0NNekNwg4=,tag:9CErgBilubKMqc1UOR/lpw==,type:bool]
                    datasetEnableReservation: ENC[AES256_GCM,data:nZMyIEI=,iv:RotIMMGs62d8F8Wj4F2evZhagz8X6M2holFZudR2MaQ=,tag:XHqH4EthUqPxZyzbEAZ8lw==,type:bool]
                    datasetPermissionsMode: ENC[AES256_GCM,data:9/Hsbg==,iv:9vu1X8IFc+jjwPhu/bOJGrqVKBBk9dM456WB3YQAHPs=,tag:gOzmxWMXbczWz20FXyGp8w==,type:str]
                    datasetPermissionsUser: ENC[AES256_GCM,data:kQ==,iv:UGc6LPlY58VNGeFBcFpEuRTtLPeFoZUndyOatCu1YHQ=,tag:FFx/owCDWKKMarGRgOKEog==,type:int]
                    datasetPermissionsGroup: ENC[AES256_GCM,data:hQ==,iv:sWUVeca9yMwbk+YFPf7frm9YK06xqgHwJWHFOPZwVro=,tag:KV/q3HdHzqlTUni0Qd2osw==,type:int]
                nfs:
                    shareHost: ENC[AES256_GCM,data:vdEac2yJMw/CWhI=,iv:oG0H6txPppOMrSqkrLffnMrkJQ/pqG+T77O7DNz070E=,tag:d1VKYPrviTzFZ0b/+WJIoQ==,type:str]
                    shareAlldirs: ENC[AES256_GCM,data:WM7lH1c=,iv:Or0/uITW12qUgzSi10StAvVQEoc0fi+wAd6P/Wl/Il4=,tag:otRaFECWzzvk3A0Z+xCcTA==,type:bool]
                    shareMaprootUser: ENC[AES256_GCM,data:8c7Olg==,iv:Dc9uipdNySYEYQJ0mEm/r3rArfPf7sWJPZ4czqTqhsc=,tag:JIh6nrn67n7ERtmjwsI4Hg==,type:str]
                    shareMaprootGroup: ENC[AES256_GCM,data:+RkPjRs=,iv:biqB07QCTDvxvgsP1gwduPNXAMAblQLNAXzAQNCifvg=,tag:L8ONmyr2IIj3v3J/3PLISA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTGEycHVONHZ1VmU4OWVP
            dkFoSWVjTVNjMFJvb2dPVXlneWJpVTlBVFFJCmU4Sy91TTVwRG5URVpIelk2ckxZ
            Q0E1UEdjUlRoNDZxOTUvYUdrWGVqQ1kKLS0tIFRVWFdTNmxDUC9GNW5zYlVLN21y
            WDdtMzhHMVh6dXNGanZCbktnN2hsNGMKg7d1rSorqJ25l/Qdnk6v5S1LhGEzAH5e
            65nRi7rB6k3iKpp3xku5cHMYunrWjwRPrRLoobd3ETOyeMpEK7LDdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T16:10:07Z"
    mac: ENC[AES256_GCM,data:1w4sOt5p9G7gdSjJx2N8stwTejoXiZ+IrpKdW+rX7sZiJccdEispoKI2vhEvblLcyooK7Fd8+Ip+qkkdzY3qC0uJFrbQ8Gy5uUHTv/RtqDLfeu3vpIybpvhloliU4pUHviBB9ep/JssEcZz7owijDNLMr7AkWE5G/roxP7UQOT4=,iv:3RDYTntIeWKx1eXwfzxTtH4QkX+E9VSeCo1jiG/xSK8=,tag:E13niMcWjYgzSIi955h6JA==,type:str]
    pgp: []
    encrypted_regex: ^.*(config)$
    version: 3.9.2
