apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8up-crds
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8up
  path: ./config/crd/apiextensions.k8s.io/v1
