---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nginx-stable
  namespace: nginx-system
spec:
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.3"
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: nginx-system
  values:
    controller:
      service:
        ipFamilyPolicy: RequireDualStack
