apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        ipFamilyPolicy: RequireDualStack
        ipFamilies:
          - IPv4
          - IPv6
        annotations:
         metallb.io/allow-shared-ip: default
      allowSnippetAnnotations: true
