apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        ipFamilyPolicy: RequireDualStack
        ipFamilies:
          - IPv4
          - IPv6
        annotations:
         metallb.io/allow-shared-ip: default
      metrics:
        enabled: true
        serviceMonitor:
          additionalLabels:
            release: kube-prometheus-stack
          enabled: true
      allowSnippetAnnotations: true
      # TODO https://github.com/kubernetes/ingress-nginx/issues/12618
      # allowSnippetAnnotations: true is basically ignored in the default 4.12.0 config
      config:
        annotations-risk-level: Critical
