apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate-system
spec:
  interval: 1m
  chart:
    spec:
      chart: renovate
      version: 39.140.0
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
  values:
    cronjob:
      schedule: '0/15 * * * *'
    renovate:
      existingConfigFile: /config/config.json
    extraVolumes:
      - name: &volume-name renovate-config
        secret:
          secretName: renovate-config
    extraVolumeMounts:
      - name: *volume-name
        mountPath: /config
