apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stash
  namespace: stash-system
spec:
  interval: 1m
  chart:
    spec:
      chart: stash
      version: v2025.1.9
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
  values:
    global:
      licenseSecretName: stash-license
    features:
      enterprise: true
