apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: vpa
      version: 4.7.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  dependsOn:
    - name: metrics-server
      namespace: kube-system
  values:
    # only used for goldilocks right now, so only the recommender is needed
    recommender:
      enabled: true
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 1.3.1@sha256:6af32652ae412c75fa6a9e506278ad190eebfa69161938eab0c73c1f8ce44ca2
    updater:
      enabled: false
    admissionController:
      enabled: false
    metrics-server:
      enabled: false
