apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: vpa
      version: 4.7.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  dependsOn:
    - name: metrics-server
      namespace: kube-system
  values:
    # only used for goldilocks right now, so only the recommender is needed
    recommender:
      enabled: true
      image:
        tag: 1.2.1
    updater:
      enabled: false
    admissionController:
      enabled: false
    metrics-server:
      enabled: false
