apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden-postgresql
    namespace: default
spec:
    interval: 1m
    chart:
        spec:
            chart: postgresql
            version: 16.3.4
            sourceRef:
                kind: HelmRepository
                name: bitnami
                namespace: flux-system
    values:
        image:
            # Current Vaultwarden is built with PG 15, also use that as long as it is supported
            # https://github.com/dani-garcia/vaultwarden/blob/1.32.6/docker/Dockerfile.alpine#L56-L57
            # https://www.postgresql.org/support/versioning/
            tag: 15.10.0
        global:
            storageClass: cluster-replicated
            postgresql:
                auth:
                    username: vaultwarden
                    password: ENC[AES256_GCM,data:/yMCUUggk4g9Y/Dpa9ZrpYwhO+aa5FG0O7Xon+/v9eE=,iv:9xxtk868sHZvTyYxumM/67H2DpmuKqZoJzkJzzC+9wc=,tag:4b3zz675b0jAsa8IAkNEnQ==,type:str]
                    database: vaultwarden
        primary:
            persistence:
                enabled: true
                size: 2Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa3FrVkpONjQwTE42RUY0
            T1c4N1R0cTBSbnlUcUJINlJ6MjBzWkhVR3o4Ckt0QlBqc0tqM0lVM2tzVy9hWGpW
            Tjd3aVcwS0c0OGJKaEhheEN1RU9QcDgKLS0tIFFEWjl0b1dvYXZ0UEZOOERtVTZ3
            WitKN1BIN0NLTE4wcUYxNmpkVlB1Y0kKXraUzj3LIw2D5PTUZWUzyZaIJ0IUkypv
            Fb3C4MXczbx0woDMK1vK2F+naCLsaJJKGMj/JEWKg1JMWURasYuPdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T20:39:44Z"
    mac: ENC[AES256_GCM,data:FTw7i10qxzzqZgqPNMsaZyTUbW5BV0HYRN/cufLFfEnLmskWoUxx7ZX0dwDCy49j6JldJPckMGD+yLlyfVh1bO/horNrMA8CNMYyAVCj3JKICOwYGd9Kct7Oy0vVsPBqjASDIcqXZtnlsvSzwAHlWsozxPr/9doxDhkEEXWlwXw=,iv:+tLoFYa8+sDJZIBvQwoOY96mNtZ66mwTOrVTVttXeAw=,tag:bxhbqTx2kn+equDblJbdLg==,type:str]
    pgp: []
    encrypted_regex: ^.*(password|value|domain|smtp|hostname)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: default
spec:
    interval: 1m
    chart:
        spec:
            chart: vaultwarden
            version: 0.31.1
            sourceRef:
                kind: HelmRepository
                name: guerzon
                namespace: flux-system
    values:
        image:
            tag: 1.32.7-alpine
        resourceType: Deployment
        # TODO https://github.com/ttionya/vaultwarden-backup as sidedcar?
        storage:
            data:
                name: vaultwarden-data
                class: cluster-replicated
                accessMode: ReadWriteOnce
                size: 1Gi
        initContainers:
            - name: wait-for-postgresql
              # Current Vaultwarden is built with PG 15, also use that as long as it is supported
              # https://github.com/dani-garcia/vaultwarden/blob/1.32.6/docker/Dockerfile.alpine#L56-L57
              # https://www.postgresql.org/support/versioning/
              image: docker.io/bitnami/postgresql:15.10.0
              command:
                - /bin/sh
                - -ec
                - |
                  until pg_isready -h vaultwarden-postgresql -U vaultwarden; do
                    echo "Waiting for PostgreSQL to be ready..."
                    sleep 2
                  done
        database:
            type: postgresql
            host: vaultwarden-postgresql
            port: "5432"
            username: vaultwarden
            password: ENC[AES256_GCM,data:T2F2eXBJKZgqaPEll41sb1jbKWanLt8Piw5p+sVobSo=,iv:zXTw/Cs7BgiF6aJuBzPSLRfOsC3E0aiIy8nGD5b0wLk=,tag:8Gap37FNn1F+sWcbs+2Vgw==,type:str]
            dbName: vaultwarden
        pushNotifications:
            enabled: true
            installationId:
                value: ENC[AES256_GCM,data:yuWMu6ANPDhDsiD4CH9LlwedHOGmiZFCWjKBoZg7Agaap+eH,iv:p0oKuu3vzGbygLrjxl2QHgapzolsSaJOF1Ww1txDtIc=,tag:Me40YAbFk/B+UoeVVISFpA==,type:str]
            installationKey:
                value: ENC[AES256_GCM,data:BvsB6fcB5k8Vm21TkZ/PW/MBDQ8=,iv:TPF56pMU8KXIbkQTCYb01OqbhoM9FGRpQyB4QjgFUL0=,tag:JkBFrM1+gZ5uYfLRiwR+ew==,type:str]
            relayUri: https://api.bitwarden.eu
            identityUri: https://identity.bitwarden.eu
        domain: ENC[AES256_GCM,data:Mq7j5Y8Z3CzNhhe48ij/96u27ZTwzTzN8wKsH79s,iv:QYkGBr0TGJ4ThVGIZisqVhknH3KlB9vCDzp+zktrx5A=,tag:rVHGF6qpBHZvpjmeBaESTw==,type:str]
        # TODO hibp API key?
        signupsAllowed: false
        iconBlacklistNonGlobalIps: false
        adminToken:
            value: ENC[AES256_GCM,data:H2tWw+QtGBtqNYBg8l7D4ntI3Jw4j57zMRWoDe+cxJ9zrLZ0KRYDPL0zSPoiqDBot+cArXnvdO5NtUPwnEVtqQ==,iv:rDwbXGfpOTayzurXTEn5fCDexUR8cVbQUYS7aba3F2k=,tag:bLR4luYnd9GQuA77X2D6yA==,type:str]
        timeZone: Europe/Berlin
        smtp:
            host: ENC[AES256_GCM,data:hxUlC6IZpx/7o7dWYDmVCTU=,iv:jaNKCZx+l4jO8tP6tmXDCCln9zmDVr9INGh12rdObRc=,tag:sT1vIB749nMub7Z/8zVN1A==,type:str]
            port: ENC[AES256_GCM,data:hEyb,iv:cjmxrjEIRo5FE/90BRC+IafOG2TtNee1YX4GvSQtAAw=,tag:ZtZQ9T8RlELcvOuqc6KqTg==,type:int]
            security: ENC[AES256_GCM,data:DDLIGEkneBfW,iv:acPkNDvJYxguM1jAQfUCeRrwrRl7RF/tmpIM9SXtoXw=,tag:sqlJpivS/AQEIMIoP2YbRg==,type:str]
            from: ENC[AES256_GCM,data:Q5N2O5Ljaujo7PW1yWlyEgzJCfencQ==,iv:baSl74oOmg5gHUHIynZYX1Qgk+OjnUZ4qZciWM0ZWbU=,tag:vsZ9vUQ3JUYiakVHV3PC1A==,type:str]
            fromName: ENC[AES256_GCM,data:Pb58MDmjkOrc,iv:/wjP4V+0dz64tvUn4tL8YduUEDzITPnI41nru1Iusdo=,tag:rpqP0fpOyi1Yds+p1c0+eA==,type:str]
            username:
                value: ENC[AES256_GCM,data:gbIJGkgJ,iv:9ZAz0jmgJ9xO6MULktPKzjliTefvVBOb6ux/PPYks0M=,tag:u6ogLRzgaTAn7m4ggMcvXw==,type:str]
            password:
                value: ENC[AES256_GCM,data:8RQ8FaiGFZCnxAGiaQ+9EXlQHiKiWsYAUIItdzCZ3OTPI4SEJjRLy87RkBXi7W3apI/mRLW2gghKy+rx780GHMoqnsR7,iv:9ZHvQ60U+x+13YRnuJ8JEzSwD6G7vxSYfjD//XB11vo=,tag:SZUGxLyb9NVUdQuinid4Qw==,type:str]
            authMechanism: ENC[AES256_GCM,data:+rpYgBA=,iv:X3I1Ehx1iRbuCLoHoTFaIOi8qSAgj25fUl98wVeKPXs=,tag:HIWZ6JmAv9DNB7dqpFJXAA==,type:str]
        ingress:
            enabled: true
            class: nginx
            nginxIngressAnnotations: true
            additionalAnnotations:
                cert-manager.io/cluster-issuer: letsencrypt
                # https://github.com/guerzon/vaultwarden/issues/117
                nginx.ingress.kubernetes.io/server-snippet: |
                    location /notifications {
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade $http_upgrade;
                      proxy_set_header Connection $http_connection;

                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;

                      proxy_pass http://vaultwarden.default.svc:80;
                    }
            tls: true
            hostname: ENC[AES256_GCM,data:P5cg13OGgpaTUK48vOCPiSmc3WhF+w==,iv:R/qA5d32yKCjc032TxQBaE4ytef+XxGF2eVyNMQ85Lo=,tag:jCqg3PjLZnvxp2jPEe4qBw==,type:str]
            tlsSecret: bitwarden-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBa3FrVkpONjQwTE42RUY0
            T1c4N1R0cTBSbnlUcUJINlJ6MjBzWkhVR3o4Ckt0QlBqc0tqM0lVM2tzVy9hWGpW
            Tjd3aVcwS0c0OGJKaEhheEN1RU9QcDgKLS0tIFFEWjl0b1dvYXZ0UEZOOERtVTZ3
            WitKN1BIN0NLTE4wcUYxNmpkVlB1Y0kKXraUzj3LIw2D5PTUZWUzyZaIJ0IUkypv
            Fb3C4MXczbx0woDMK1vK2F+naCLsaJJKGMj/JEWKg1JMWURasYuPdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T20:39:44Z"
    mac: ENC[AES256_GCM,data:FTw7i10qxzzqZgqPNMsaZyTUbW5BV0HYRN/cufLFfEnLmskWoUxx7ZX0dwDCy49j6JldJPckMGD+yLlyfVh1bO/horNrMA8CNMYyAVCj3JKICOwYGd9Kct7Oy0vVsPBqjASDIcqXZtnlsvSzwAHlWsozxPr/9doxDhkEEXWlwXw=,iv:+tLoFYa8+sDJZIBvQwoOY96mNtZ66mwTOrVTVttXeAw=,tag:bxhbqTx2kn+equDblJbdLg==,type:str]
    pgp: []
    encrypted_regex: ^.*(password|value|domain|smtp|hostname)$
    version: 3.9.2
