apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: bitnami
    namespace: default
spec:
    type: oci
    url: oci://registry-1.docker.io/bitnamicharts
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArczg5dDQ5N0NVY2ZZQkYy
            SGhRN0lxR1VuRHZjbDBINFZRTzNRZURWZkhrCjZOUG0vd0l3eUNqZVdyeWVBU1NG
            UjJiMzZwRm5PbFZlUW5GMjNRMGlodmsKLS0tIGxnZGJ5K0Zwbktxa21xSGNhZG82
            Uy9hT001L0N5TmNBa3lTOVRkMktnRXcK4AxE5ovIInedqoVFp9w389uWm1T6Q3sB
            /lLL628+hp+PEKWB9QFx82h4yKyMxd6GyjOrSAX9RiRZxjbL4hYPhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T14:58:45Z"
    mac: ENC[AES256_GCM,data:2Eqd3KobIAB6YFevNLsTRmLTHxYtQ/S4q+Lmu7JIlfdhRZkvORG8RXCOrE3qE3T7I/9lSB2leEoonQUHY8skLbhW4cYiuIGu6cAKjfJs0QZkHqjwNNqyXEI1ks8QR120L/DVFbLx/sAf8w6Ws0Qn4O68BErA/kQuv2YToQ2UL0I=,iv:nAZ1ZKrvTAlsT5kCKubrxTHUUhzkNO94hHU9HMG3tbw=,tag:WaxEmkp4hxInlJTXtsGyHg==,type:str]
    pgp: []
    encrypted_regex: ^.*(password|value|domain|smtp|hostname)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden-postgresql
    namespace: default
spec:
    interval: 1m
    chart:
        spec:
            chart: postgresql
            version: 16.3.2
            sourceRef:
                kind: HelmRepository
                name: bitnami
                namespace: default
    values:
        image:
            # Current Vaultwarden is built with PG 15, also use that as long as it is supported
            # https://github.com/dani-garcia/vaultwarden/blob/1.32.6/docker/Dockerfile.alpine#L56-L57
            # https://www.postgresql.org/support/versioning/
            tag: 15.10.0
        global:
            storageClass: cluster-replicated
            postgresql:
                auth:
                    username: vaultwarden
                    password: ENC[AES256_GCM,data:V3NBDuBISta21vpHyXBLSX9yGyJ7awIGIFesaFalZps=,iv:gwu3oI/hlFhj/EmmML4xYwNHHhd6IpBZ0cWGAnC+ZRc=,tag:HKiSH7BTDrT8+i2UskUCSw==,type:str]
                    database: vaultwarden
        primary:
            persistence:
                enabled: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArczg5dDQ5N0NVY2ZZQkYy
            SGhRN0lxR1VuRHZjbDBINFZRTzNRZURWZkhrCjZOUG0vd0l3eUNqZVdyeWVBU1NG
            UjJiMzZwRm5PbFZlUW5GMjNRMGlodmsKLS0tIGxnZGJ5K0Zwbktxa21xSGNhZG82
            Uy9hT001L0N5TmNBa3lTOVRkMktnRXcK4AxE5ovIInedqoVFp9w389uWm1T6Q3sB
            /lLL628+hp+PEKWB9QFx82h4yKyMxd6GyjOrSAX9RiRZxjbL4hYPhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T14:58:45Z"
    mac: ENC[AES256_GCM,data:2Eqd3KobIAB6YFevNLsTRmLTHxYtQ/S4q+Lmu7JIlfdhRZkvORG8RXCOrE3qE3T7I/9lSB2leEoonQUHY8skLbhW4cYiuIGu6cAKjfJs0QZkHqjwNNqyXEI1ks8QR120L/DVFbLx/sAf8w6Ws0Qn4O68BErA/kQuv2YToQ2UL0I=,iv:nAZ1ZKrvTAlsT5kCKubrxTHUUhzkNO94hHU9HMG3tbw=,tag:WaxEmkp4hxInlJTXtsGyHg==,type:str]
    pgp: []
    encrypted_regex: ^.*(password|value|domain|smtp|hostname)$
    version: 3.9.2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: guerzon
    namespace: default
spec:
    url: https://guerzon.github.io/vaultwarden
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArczg5dDQ5N0NVY2ZZQkYy
            SGhRN0lxR1VuRHZjbDBINFZRTzNRZURWZkhrCjZOUG0vd0l3eUNqZVdyeWVBU1NG
            UjJiMzZwRm5PbFZlUW5GMjNRMGlodmsKLS0tIGxnZGJ5K0Zwbktxa21xSGNhZG82
            Uy9hT001L0N5TmNBa3lTOVRkMktnRXcK4AxE5ovIInedqoVFp9w389uWm1T6Q3sB
            /lLL628+hp+PEKWB9QFx82h4yKyMxd6GyjOrSAX9RiRZxjbL4hYPhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T14:58:45Z"
    mac: ENC[AES256_GCM,data:2Eqd3KobIAB6YFevNLsTRmLTHxYtQ/S4q+Lmu7JIlfdhRZkvORG8RXCOrE3qE3T7I/9lSB2leEoonQUHY8skLbhW4cYiuIGu6cAKjfJs0QZkHqjwNNqyXEI1ks8QR120L/DVFbLx/sAf8w6Ws0Qn4O68BErA/kQuv2YToQ2UL0I=,iv:nAZ1ZKrvTAlsT5kCKubrxTHUUhzkNO94hHU9HMG3tbw=,tag:WaxEmkp4hxInlJTXtsGyHg==,type:str]
    pgp: []
    encrypted_regex: ^.*(password|value|domain|smtp|hostname)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: default
spec:
    interval: 1m
    chart:
        spec:
            chart: vaultwarden
            version: 0.31.1
            sourceRef:
                kind: HelmRepository
                name: guerzon
                namespace: default
    values:
        image:
            tag: 1.32.6-alpine
        resourceType: Deployment
        # TODO https://github.com/ttionya/vaultwarden-backup as sidedcar?
        storage:
            data:
                name: vaultwarden-data
                class: cluster-replicated
                accessMode: ReadWriteOnce
                size: 1Gi
        initContainers:
            - name: wait-for-postgresql
              # Current Vaultwarden is built with PG 15, also use that as long as it is supported
              # https://github.com/dani-garcia/vaultwarden/blob/1.32.6/docker/Dockerfile.alpine#L56-L57
              # https://www.postgresql.org/support/versioning/
              image: docker.io/bitnami/postgresql:15.10.0
              command:
                - /bin/sh
                - -ec
                - |
                  until pg_isready -h vaultwarden-postgresql -U vaultwarden; do
                    echo "Waiting for PostgreSQL to be ready..."
                    sleep 2
                  done
        database:
            type: postgresql
            host: vaultwarden-postgresql
            port: "5432"
            username: vaultwarden
            password: ENC[AES256_GCM,data:LVVkikFz5n0SGUaJLz2ZD1k884f6kVqWByB9KOFve9k=,iv:pwQ2fcC21tU/lFpNM7Zw253+AgUMDIzv0hCqivznLZg=,tag:dHYltYyDEQbn0majIT5abQ==,type:str]
            dbName: vaultwarden
        pushNotifications:
            enabled: true
            installationId:
                value: ENC[AES256_GCM,data:5g9iRsBAir61coA8u9TGHukO9Ho3IAqkz4g+3P5J8Oo2ISUd,iv:BhmHDTxjCiPXHCAaizsX7EzqX0NpiW6i85H5EkE+bBk=,tag:6+JTQskajgi4RAV1CTwy5w==,type:str]
            installationKey:
                value: ENC[AES256_GCM,data:yvns4E9d4PfHx3XFJBCCdCtacDw=,iv:AD1IKzKARlVEvskVETYiZy/tgEY+3B7CUdqo6UUmci4=,tag:8+miIoFHCF2hQnm7/wNaFQ==,type:str]
            relayUri: https://api.bitwarden.eu
            identityUri: https://identity.bitwarden.eu
        domain: ENC[AES256_GCM,data:WiMv9IrdulJcYgdCQ+eHJP78k9LhX0DAOzzgDn0Z,iv:pyHVboRsaE1n4rGD7pXjcxgZXgeOIcXSHP+Wr4yW+JA=,tag:Ze/u1sE7EIfA2YGZ+uej9A==,type:str]
        # TODO hibp API key?
        signupsAllowed: false
        iconBlacklistNonGlobalIps: false
        adminToken:
            value: ENC[AES256_GCM,data:B+BwxOKvGSln8chAWx0RKE7FU1odnSuJATt8laymrNmqbiWyUhCVQf7kw+ynb0I9pZOLzPbeCYyyhZoYO1STXA==,iv:d5tbgNgnHlu0UcngBylRC8pnfLa30f67h2SDq8ktOH4=,tag:0vtDTHlGcNhyf9Cwum606w==,type:str]
        timeZone: Europe/Berlin
        smtp:
            host: ENC[AES256_GCM,data:1EYPrZSOAY+J0LQ3fQHLaqU=,iv:CUOnhttbcUp3muszrZCIayVW32/6Fva4l8vE0d0Gn8o=,tag:1toONaZxocSuGQH/M2e3mA==,type:str]
            port: ENC[AES256_GCM,data:qlfH,iv:FVus/c/vOcC1oRh0Je16f95sdJjZFHnK91aaFY8Ah+g=,tag:Z0Cv8/Kh5UqDO7/dG5Jybw==,type:int]
            security: ENC[AES256_GCM,data:LX+TJldHcmM=,iv:/bbULWbhvnWlWas1JCZDHssnOKv/Ca/6EtOrlTDJvIY=,tag:cROCpp/Ij3JcbVqo/mFvIw==,type:str]
            from: ENC[AES256_GCM,data:Q4ncn5/9ZAULiO7drot+aFOXPfsl5g==,iv:lIvETg0Ca6IvmOmmIe4zcL3fB5LKBKQPLWMDaju+SBg=,tag:gaDgA4huuRsIbzsnEIHDxw==,type:str]
            fromName: ENC[AES256_GCM,data:KJn68kKPCp1u,iv:kTN7hXSIicywz6O6HSyawJPEtyN2TI3ikF57B16BAAE=,tag:DhwP7bkFbzJjw4qDCBr0uQ==,type:str]
            username:
                value: ENC[AES256_GCM,data:lVWsVw0D,iv:yX3mi/P0KcxYq3sSvzBK/GBrMmt2l81pyxdWU/xJvm8=,tag:kC4Q3JJDB4QbHT3LEc8u6Q==,type:str]
            password:
                value: ENC[AES256_GCM,data:zdk/cC0NDvZcezh0M7PesnwAdW/8uj778ZRs2p6TWWSu5C1d09Y2CueGyhsSiYM248/7tIBqSPd1CjT9oYXxfuAx/3T7,iv:6efhVqsZjFYeUGwJgNnyV5v9299VZjdNzprFTxWSI5o=,tag:d5esoQjrPp01mjM9d+7tXA==,type:str]
            authMechanism: ENC[AES256_GCM,data:a67sEeI=,iv:ZMa3jgJVZ/4jK0N209T9NUUW4+vwyZHDlZk3Z+xrzgc=,tag:2OscD+I5IkHLdctMXLXoBQ==,type:str]
        ingress:
            enabled: true
            class: nginx
            nginxIngressAnnotations: true
            additionalAnnotations:
                cert-manager.io/cluster-issuer: letsencrypt
                # https://github.com/guerzon/vaultwarden/issues/117
                nginx.ingress.kubernetes.io/server-snippet: |
                    location /notifications {
                      proxy_http_version 1.1;
                      proxy_set_header Upgrade $http_upgrade;
                      proxy_set_header Connection $http_connection;

                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;

                      proxy_pass http://vaultwarden.default.svc:80;
                    }
            tls: true
            hostname: ENC[AES256_GCM,data:tdggc0NFNCEaJkBW2o0Lioe6EC3ibA==,iv:leNc8mm2MUUEdmtFNUWLuXRILszWguG3w9JENpJG8IA=,tag:ngPxQHEHWPv+WsRwSc6Ikw==,type:str]
            tlsSecret: bitwarden-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArczg5dDQ5N0NVY2ZZQkYy
            SGhRN0lxR1VuRHZjbDBINFZRTzNRZURWZkhrCjZOUG0vd0l3eUNqZVdyeWVBU1NG
            UjJiMzZwRm5PbFZlUW5GMjNRMGlodmsKLS0tIGxnZGJ5K0Zwbktxa21xSGNhZG82
            Uy9hT001L0N5TmNBa3lTOVRkMktnRXcK4AxE5ovIInedqoVFp9w389uWm1T6Q3sB
            /lLL628+hp+PEKWB9QFx82h4yKyMxd6GyjOrSAX9RiRZxjbL4hYPhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T14:58:45Z"
    mac: ENC[AES256_GCM,data:2Eqd3KobIAB6YFevNLsTRmLTHxYtQ/S4q+Lmu7JIlfdhRZkvORG8RXCOrE3qE3T7I/9lSB2leEoonQUHY8skLbhW4cYiuIGu6cAKjfJs0QZkHqjwNNqyXEI1ks8QR120L/DVFbLx/sAf8w6Ws0Qn4O68BErA/kQuv2YToQ2UL0I=,iv:nAZ1ZKrvTAlsT5kCKubrxTHUUhzkNO94hHU9HMG3tbw=,tag:WaxEmkp4hxInlJTXtsGyHg==,type:str]
    pgp: []
    encrypted_regex: ^.*(password|value|domain|smtp|hostname)$
    version: 3.9.2
