apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: firefly-postgresql
  namespace: default
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-27
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: stashbackup
        passwordSecret:
          name: stash-postgres-backup-user
        login: true
        superuser: false
        inRoles:
          - pg_read_all_data
  bootstrap:
    initdb:
      database: firefly
      owner: firefly
      secret:
        name: firefly-postgres-user
  storage:
    size: 2Gi
    storageClass: cluster-replicated
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: firefly-iii
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: flux-system
  values:
    image:
      repository: fireflyiii/core
      tag: version-6.1.25@sha256:8391c11f3260354a1feb48d1cf2cb822ad00db311efe2b21eccd7d5ee6bfe60a
    persistence:
      enabled: false
    config:
      existingSecret: firefly-config
    cronjob:
      auth:
        existingSecret: firefly-cron
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - firefly.${SERVICE_DOMAIN}
      tls:
        - secretName: firefly-tls
          hosts:
            - firefly.${SERVICE_DOMAIN}
    resources:
      requests:
        cpu: 20m
        memory: 200Mi
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: firefly-postgresql
  namespace: default
spec:
  clientConfig:
    service:
      name: firefly-postgresql-rw
      port: 5432
      scheme: postgresql
  secret:
    name: stash-postgres-backup-user
  type: postgres
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: firefly-postgresql
  namespace: default
spec:
  schedule: "11 * * * *"
  task:
    name: postgres-backup-17.2
  repository:
    name: b2-database-repo
    namespace: stash-system
  target:
    alias: firefly
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: firefly-postgresql
  retentionPolicy:
    name: "staggered"
    keepHourly: 24
    keepDaily: 14
    keepWeekly: 12
    keepMonthly: 6
    keepYearly: 2
    prune: false
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: firefly-postgresql-prune
  namespace: stash-system
spec:
  schedule: "41 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: restic
              image: restic/restic:0.17.3@sha256:8f5a62b422a2cb1277ea0dd6e826fe1acf649e5b9f02d60e5268d5fd1976255a
              command:
                - /bin/sh
                - -c
                - |
                  restic forget --prune \
                    --keep-hourly 24 \
                    --keep-daily 14 \
                    --keep-weekly 12 \
                    --keep-monthly 6 \
                    --keep-yearly 2
              env:
                - name: B2_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: b2-secret
                      key: B2_ACCOUNT_ID
                - name: B2_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: b2-secret
                      key: B2_ACCOUNT_KEY
                - name: RESTIC_REPOSITORY
                  value: b2:backup-database-manhunt4669:/
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: b2-secret
                      key: RESTIC_PASSWORD
                - name: RESTIC_HOST
                  value: firefly
