apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: firefly-postgresql
  namespace: default
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-27
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: stashbackup
        passwordSecret:
          name: stash-postgres-backup-user
        login: true
        superuser: false
        inRoles:
          - pg_read_all_data
  bootstrap:
    initdb:
      database: firefly
      owner: firefly
      secret:
        name: firefly-postgres-user
  storage:
    size: 2Gi
    storageClass: cluster-replicated
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: firefly-iii
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: flux-system
  values:
    image:
      repository: fireflyiii/core
      tag: version-6.2.9@sha256:8047e1337cbcd3f8c347f89c5e2e4c22ff5df043227481a5749368d6caab1a2e
    persistence:
      enabled: false
    config:
      existingSecret: firefly-config
    cronjob:
      auth:
        existingSecret: firefly-cron
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - firefly.${SERVICE_DOMAIN}
      tls:
        - secretName: firefly-tls
          hosts:
            - firefly.${SERVICE_DOMAIN}
    resources:
      requests:
        cpu: 20m
        memory: 200Mi
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: firefly-postgresql
  namespace: default
spec:
  clientConfig:
    service:
      name: firefly-postgresql-rw
      port: 5432
      scheme: postgresql
  secret:
    name: stash-postgres-backup-user
  type: postgres
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: firefly-postgresql
  namespace: default
spec:
  schedule: "11 4/6 * * *"
  task:
    name: postgres-backup-17.2
  repository:
    name: b2-database-repo
    namespace: stash-system
  target:
    alias: firefly
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: firefly-postgresql
  retentionPolicy:
    name: "staggered"
    keepHourly: 6
    keepDaily: 14
    keepWeekly: 12
    keepMonthly: 6
    keepYearly: 2
    prune: true
