apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: firefly-postgresql
  namespace: default
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-27@sha256:9308dcd778be66f56bdce8503916ab820d12420e7d1bc74fff0d663c95e126c3
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: backup
        passwordSecret:
          name: postgres-backup-user
        login: true
        superuser: false
        inRoles:
          - pg_read_all_data
  bootstrap:
    initdb:
      database: firefly
      owner: firefly
      secret:
        name: firefly-postgres-user
  storage:
    size: 2Gi
    storageClass: cluster-replicated
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: firefly-iii
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: flux-system
  values:
    image:
      repository: fireflyiii/core
      tag: version-6.2.9@sha256:ac842bc5b7a66f40f9680b27e03f9155907741ce8940bb3a3ceffa99f43b200a
    persistence:
      enabled: false
    config:
      existingSecret: firefly-config
    cronjob:
      auth:
        existingSecret: firefly-cron
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - firefly.${SERVICE_DOMAIN}
      tls:
        - secretName: firefly-tls
          hosts:
            - firefly.${SERVICE_DOMAIN}
    resources:
      requests:
        cpu: 20m
        memory: 200Mi
---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: firefly-database-backup
  namespace: default
  labels:
    backup: firefly-database
  annotations:
    k8up.io/backup: "true"
spec:
  backupCommand: sh -c 'PGHOST="$POSTGRES_HOST" PGUSER="$POSTGRES_USER" PGPASSWORD="$POSTGRES_PASSWORD" pg_dumpall --clean'
  pod:
    spec:
      containers:
        - name: firefly-database-backup
          image: postgres:17.4-alpine@sha256:6c717ca5788964057727e357b9bb634df43197ccbee573994b438921f97a3583
          command:
            - "sleep"
            - "infinity"
          env:
            - name: POSTGRES_HOST
              value: firefly-postgresql-rw
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-user
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-user
                  key: password
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: firefly-database
  namespace: default
spec:
  backend:
    repoPasswordSecretRef:
      name: k8up-restic-secrets
      key: restic-password
    s3:
      bucket: Habitat-Giggle9-Composer/firefly
  backup:
    labelSelectors:
      - matchLabels:
          backup: firefly-database
    schedule: "11 4/6 * * *"
    concurrentRunsAllowed: false
  prune:
    schedule: "41 0 1 * *"
    concurrentRunsAllowed: false
    retention:
      keepHourly: 6
      keepDaily: 14
      keepWeekly: 12
      keepMonthly: 6
      keepYearly: 2
