apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fresh-rss-postgresql
  namespace: default
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-27
  instances: 1
  bootstrap:
    initdb:
      database: freshrss
      owner: freshrss
      secret:
        name: fresh-rss-postgres-user
  storage:
    size: 2Gi
    storageClass: cluster-replicated
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fresh-rss
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: freshrss/freshrss
              tag: 1.25.0-alpine
            env:
              TZ: Europe/Berlin
              BASE_URL: https://freshrss.${SERVICE_DOMAIN}
              CRON_MIN: '*/12'
              FRESHRSS_INSTALL:
                valueFrom:
                  secretKeyRef:
                    name: fresh-rss-config
                    key: freshrss-install
              FRESHRSS_USER:
                valueFrom:
                  secretKeyRef:
                    name: fresh-rss-config
                    key: freshrss-user
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: freshrss.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: fresh-rss-tls
            hosts:
              - freshrss.${SERVICE_DOMAIN}
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /var/www/FreshRSS/data
