apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fresh-rss-postgresql
  namespace: default
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-27
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: stashbackup
        passwordSecret:
          name: stash-postgres-backup-user
        login: true
        superuser: false
        inRoles:
          - pg_read_all_data
  bootstrap:
    initdb:
      database: freshrss
      owner: freshrss
      secret:
        name: fresh-rss-postgres-user
  storage:
    size: 2Gi
    storageClass: cluster-replicated
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fresh-rss
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: freshrss/freshrss
              tag: 1.25.0-alpine@sha256:e9f1b39e7e6ef940b2f7f5564d03a33a30f26d7d134c980fbdebadc9cb434cfc
            env:
              TZ: Europe/Berlin
              BASE_URL: https://freshrss.${SERVICE_DOMAIN}
              CRON_MIN: '*/12'
              FRESHRSS_INSTALL:
                valueFrom:
                  secretKeyRef:
                    name: fresh-rss-config
                    key: freshrss-install
              FRESHRSS_USER:
                valueFrom:
                  secretKeyRef:
                    name: fresh-rss-config
                    key: freshrss-user
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 20m
                memory: 100Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: freshrss.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: fresh-rss-tls
            hosts:
              - freshrss.${SERVICE_DOMAIN}
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /var/www/FreshRSS/data
---
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: fresh-rss-postgresql
  namespace: default
spec:
  clientConfig:
    service:
      name: fresh-rss-postgresql-rw
      port: 5432
      scheme: postgresql
  secret:
    name: stash-postgres-backup-user
  type: postgres
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: fresh-rss-postgresql
  namespace: default
spec:
  schedule: "17 * * * *"
  task:
    name: postgres-backup-17.2
  repository:
    name: b2-database-repo
    namespace: stash-system
  target:
    alias: freshrss
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: fresh-rss-postgresql
  retentionPolicy:
    name: "staggered"
    keepHourly: 24
    keepDaily: 14
    keepWeekly: 12
    keepMonthly: 6
    keepYearly: 2
    prune: false
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fresh-rss-postgresql-prune
  namespace: stash-system
spec:
  schedule: "47 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: restic
              image: restic/restic:0.17.3@sha256:8f5a62b422a2cb1277ea0dd6e826fe1acf649e5b9f02d60e5268d5fd1976255a
              command:
                - /bin/sh
                - -c
                - |
                  restic forget --prune \
                    --keep-hourly 24 \
                    --keep-daily 14 \
                    --keep-weekly 12 \
                    --keep-monthly 6 \
                    --keep-yearly 2
              env:
                - name: B2_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: b2-secret
                      key: B2_ACCOUNT_ID
                - name: B2_ACCOUNT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: b2-secret
                      key: B2_ACCOUNT_KEY
                - name: RESTIC_REPOSITORY
                  value: b2:backup-database-manhunt4669:/
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: b2-secret
                      key: RESTIC_PASSWORD
                - name: RESTIC_HOST
                  value: freshrss
