apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.0.4@sha256:78a34acb9ca1e63eecf12919fc9fb6c91f5dea748395172d7c1904db4c5bc973
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    enableRbac: true
    serviceAccount:
      create: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: homepage.${SERVICE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - homepage.${SERVICE_DOMAIN}
    config:
      useExistingConfigMap: homepage-config
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "homepage.${SERVICE_DOMAIN}"
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
