apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: jellyfin
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/jellyfin/jellyfin
      tag: 10.10.5@sha256:54340f53459858156896d5758a6eaa2cea9c95ff95c3c966f2fff1307e31660c
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: jellyfin.${SERVICE_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls
          hosts:
            - jellyfin.${SERVICE_DOMAIN}
    volumes:
      - name: nas-filme
        nfs:
          server: 192.168.1.2
          path: /mnt/tank/Filme
      - name: nas-serien
        nfs:
          server: 192.168.1.2
          path: /mnt/tank/Serien
    volumeMounts:
      - name: nas-filme
        mountPath: /mnt/tank/Filme
      - name: nas-serien
        mountPath: /mnt/tank/Serien
    persistence:
      config:
        storageClass: cluster-replicated
        size: 10Gi
      media:
        enabled: false
