apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: nextcloud
    namespace: default
spec:
    url: https://nextcloud.github.io/helm/
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSFpQSURnU0I3K1d0TWdG
            eXlvd2FnQVJsbGZMSy92dXQwZTFCZlpIYkR3CkpXRHpIK2gwN2haYkRKRjBEVWhU
            ekIzU2lhd0FDaGovNFAzMkNHU0RpN0EKLS0tIGVkV2w5azRKSStNOHlYVmR5UE4x
            SFd2Qm10dWUvZExaQnViYWhXNC8yR3cK2E/YspelbRm0u69h6LImK2rv6ZeS3xGh
            ViZR2HwM5GOkfNEp90OYUT0ZfB/W0o7SxYqySnfDfX9e7Vsqif65Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T09:07:06Z"
    mac: ENC[AES256_GCM,data:O5G/yAgtzI4kRqTbOPdLYhVlMEYlJDUhNuODuHno/bqWWiTXxEBZCIfrGUVoqH5hOFo8KpC6OrRaudThiK4YM1WyiYSSFTrD7hzvrjZPHnUNu5ZuApHjfH0XsMXaAL0ZHHmyKHhvSmKfIQHtMl34bdkmOe+YzwQGflIHzkojfVM=,iv:2SfYs0BoSGKcBj/1zIiGZWNr1n9AFd4PRYfQXJ+U9Zc=,tag:IGgCGQUxzmlrsuTUHTOYIg==,type:str]
    pgp: []
    encrypted_regex: ^.*(host|hosts|trustedDomains|fromAddress|domain|smtp|password)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: default
spec:
    interval: 1m
    chart:
        spec:
            chart: nextcloud
            version: 6.4.1
            sourceRef:
                kind: HelmRepository
                name: nextcloud
                namespace: default
    values:
        replicaCount: 2
        image:
            flavor: fpm-alpine
        # https://github.com/nextcloud/helm/issues/10
        # https://github.com/nextcloud/helm/issues/399
        startupProbe:
            enabled: true
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 50
            successThreshold: 1
        ingress:
            enabled: true
            className: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                nginx.ingress.kubernetes.io/affinity: cookie
                nginx.ingress.kubernetes.io/cors-allow-headers: X-Forwarded-For
                nginx.ingress.kubernetes.io/enable-cors: "true"
                nginx.ingress.kubernetes.io/proxy-body-size: 4G
            tls:
                - secretName: nextcloud-tls
                  hosts:
                    - ENC[AES256_GCM,data:dY7HlhrSHE5rNWqlskySTjTETbhM5w==,iv:trT/oVLInIUm7Oyu0Kea6iNSrUNwa3msggMVGRG/N+U=,tag:Nff0+KXJkwLFy14dXRCYvA==,type:str]
        phpClientHttpsFix:
            enabled: true
        nextcloud:
            host: ENC[AES256_GCM,data:0525VxrK0WERg6ZTKRtkSwO53OIdpg==,iv:BrPks2/SxnB/jcqW1QLzhkLlTwYEK36/SDCyoyx+gZY=,tag:8GIBGe1z418s/AU+tpok/A==,type:str]
            trustedDomains:
                - ENC[AES256_GCM,data:pFbIz/b01FSf,iv:+X+a0/ULVZ3S4O/3a1Vi0Jo+nGGwqQJqf7AhwGu95NU=,tag:V1eh3E3F8PE1L4ZVQgaFEg==,type:str]
                - ENC[AES256_GCM,data:+JygrOhV1Mp6phxC2chJHaBzA+9WFg==,iv:nCM1Ib8lWwl21tBrxxuOgRT5iGo6DwhiLnN6Te5CD5Y=,tag:ZfmJcsvS2tdByRZFcLB/Ww==,type:str]
            configs:
                proxy.config.php: |-
                    <?php
                    $CONFIG = array (
                      'trusted_proxies' => array(
                        0 => '127.0.0.1',
                        1 => '172.16.0.0/24',
                        2 => '172.32.0.0/16',
                        3 => 'fd08:172:16::/112',
                        4 => 'fd08:172:32::/56',
                      ),
                      'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
                    );
                previews.config.php: |-
                    <?php
                    $CONFIG = array (
                      'enable_previews' => true,
                      'enabledPreviewProviders' => array (
                        'OC\Preview\Movie',
                        'OC\Preview\PNG',
                        'OC\Preview\JPEG',
                        'OC\Preview\GIF',
                        'OC\Preview\BMP',
                        'OC\Preview\XBitmap',
                        'OC\Preview\MP3',
                        'OC\Preview\MP4',
                        'OC\Preview\TXT',
                        'OC\Preview\MarkDown',
                        'OC\Preview\PDF'
                      ),
                    );
            mail:
                enabled: true
                fromAddress: ENC[AES256_GCM,data:KNk85i8WfPq7,iv:PnbQ1szgVcvkqtguGfy7z/E6t6TvhhW3aH++cdXex4k=,tag:rSnrGJqBpqB9Aos231lFqQ==,type:str]
                domain: ENC[AES256_GCM,data:Yh8VUS7H5GWRBJUe,iv:DFZud9E8TA0eKbXtkJJGdxwWytABkDXVE13eiEGK3vc=,tag:RE0Er7MD7DHJJgsYfT49HA==,type:str]
                smtp:
                    host: ENC[AES256_GCM,data:Jc672Wk65t77KgRfBCQk6uE=,iv:CnaqkCZlFdleybdfm8+nkzFLJ3FgxxQBZF60Ssj+VdI=,tag:XSfXNHnR/byxaWUsxggUcQ==,type:str]
                    port: ENC[AES256_GCM,data:awyp,iv:qOyEdo7ZFFzToD+WOkSkVhIc1twrBBeKDoz8MeLy27U=,tag:e6j9EDQpB/QG0oHaWcggHQ==,type:int]
                    secure: ENC[AES256_GCM,data:Yi0w,iv:oeth2Sapl1TSSmCpG1VvRZ6xXT0DZrfQZCnPjaKwUvY=,tag:wWyXva8vh6D9EUJ85D665A==,type:str]
                    authtype: ENC[AES256_GCM,data:vsTxG68=,iv:u4kTr0gc0igT1FppJq9wJ7BqMf+d9myCgiiFpKxX4Vc=,tag:ZsAYldFVOJG7dJCKWJDftg==,type:str]
                    name: ENC[AES256_GCM,data:PVuFuUXX,iv:gkWo096Zcm2lIGxv1Xixjvb9S6WW1GGQ2R4MmJL96+M=,tag:6FHhL0HxWmXHB8y0iv1Jjg==,type:str]
                    password: ENC[AES256_GCM,data:HJWtyPsXCtVCniNzPJzovRgoe4AHUe/ZKHg+odB0IOWWwEotRaCC5A7IMAk/1+41wdARwK9G9S8OxPVz5QhNXGkZ+PQ2,iv:5J7riXFJ3ZBeQoial7x/YyUGEpmoOKwgPx1Xz3CQt88=,tag:JqFJ//8xuG3Jcsfrr9m6uA==,type:str]
        nginx:
            enabled: true
            ipFamilies:
                - IPv4
                - IPv6
        redis:
            enabled: true
            auth:
                enabled: true
                password: ENC[AES256_GCM,data:hS8BbQ5ne5LJTzV59t6Rb7WZYyKoxaNU+T+UM6mYEx0=,iv:6O4umMYflwQPY2ia6mrutOvAHQrH9RHVaFgUJ153RTM=,tag:W8Inqk/0Et5H91D4PlLCrw==,type:str]
            global:
                storageClass: cluster-local
            architecture: standalone
        cronjob:
            enabled: true
        internalDatabase:
            enabled: false
        externalDatabase:
            enabled: true
            type: postgresql
        postgresql:
            enabled: true
            global:
                postgresql:
                    auth:
                        password: ENC[AES256_GCM,data:wOHAqDvfuV+zFQvkhveaOh5NQI6PjSwH9LYXefHAy2o=,iv:pVYx9h4NW2KqkA8iVrFdb+6ae1psRTGkHo7byor1VDE=,tag:VcqhnXBuzrCfjiUO5GWn+Q==,type:str]
            primary:
                persistence:
                    enabled: true
                    storageClass: cluster-replicated
        persistence:
            enabled: true
            storageClass: cluster-replicated
            accessMode: ReadWriteMany
            nextcloudData:
                enabled: true
                storageClass: cluster-replicated
                accessMode: ReadWriteMany
                size: 100Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSFpQSURnU0I3K1d0TWdG
            eXlvd2FnQVJsbGZMSy92dXQwZTFCZlpIYkR3CkpXRHpIK2gwN2haYkRKRjBEVWhU
            ekIzU2lhd0FDaGovNFAzMkNHU0RpN0EKLS0tIGVkV2w5azRKSStNOHlYVmR5UE4x
            SFd2Qm10dWUvZExaQnViYWhXNC8yR3cK2E/YspelbRm0u69h6LImK2rv6ZeS3xGh
            ViZR2HwM5GOkfNEp90OYUT0ZfB/W0o7SxYqySnfDfX9e7Vsqif65Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-17T09:07:06Z"
    mac: ENC[AES256_GCM,data:O5G/yAgtzI4kRqTbOPdLYhVlMEYlJDUhNuODuHno/bqWWiTXxEBZCIfrGUVoqH5hOFo8KpC6OrRaudThiK4YM1WyiYSSFTrD7hzvrjZPHnUNu5ZuApHjfH0XsMXaAL0ZHHmyKHhvSmKfIQHtMl34bdkmOe+YzwQGflIHzkojfVM=,iv:2SfYs0BoSGKcBj/1zIiGZWNr1n9AFd4PRYfQXJ+U9Zc=,tag:IGgCGQUxzmlrsuTUHTOYIg==,type:str]
    pgp: []
    encrypted_regex: ^.*(host|hosts|trustedDomains|fromAddress|domain|smtp|password)$
    version: 3.9.2
