apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opnsense-ipv6-prefix-update
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "*/1 * * * *"
        containers:
          main:
            image:
              repository: ghcr.io/c0nsultant/opnsense-ipv6-prefix-update
              tag: v1.0.3
            env:
              OPNSENSE_HOST: 192.168.1.1
              OPNSENSE_PORT: 80
              OPNSENSE_SSL: "false"
              OPNSENSE_VERIFY_SSL: "true"
              IPV6_PREFIX_LENGTH: 57
            envFrom:
              - secret: opnsense-ipv6-prefix-update-secrets
