apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opnsense-ipv6-prefix-update
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "*/1 * * * *"
        initContainers:
          main:
            image:
              repository: ghcr.io/c0nsultant/opnsense-ipv6-prefix-update
              tag: v1.0.3@sha256:5371e931a8e186f914e2261ec4832b220f95e478986bb1365157026490fba00a
            env:
              OPNSENSE_HOST: 192.168.1.1
              OPNSENSE_PORT: 80
              OPNSENSE_SSL: "false"
              OPNSENSE_VERIFY_SSL: "true"
              IPV6_PREFIX_LENGTH: 57
            envFrom:
              - secret: opnsense-ipv6-prefix-update-secrets
        containers:
          healthcheck:
            image:
              repository: curlimages/curl
              tag: latest@sha256:e7f227b4e2adafe7bd743bda37f4f6d6f803ea965e9e827061ff07de9d67d433
            command: ["curl"]
            args: ["-fs", "$(HEALTHCHECK)"]
            env:
              - name: HEALTHCHECK
                valueFrom:
                  secretKeyRef:
                    name: opnsense-ipv6-prefix-update-secrets
                    key: HEALTHCHECK
