apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overleaf-mongodb
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: mongodb
      version: 16.4.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      defaultStorageClass: cluster-replicated
    image:
      tag: 8.0.4
    architecture: standalone
    useStatefulSet: true
    auth:
      enabled: true
      usernames:
        - sharelatex
      databases:
        - sharelatex
      existingSecret: overleaf-mongodb-secrets
    persistence:
      enabled: true
      size: 2Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overleaf-redis
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: redis
      version: 20.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      enabled: false
    global:
      storageClass: cluster-scratch
    master:
      persistence:
        size: 2Gi
    architecture: standalone
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overleaf
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  values:
    controllers:
      main:
        containers:
          main:
            image:
              # preferably, bootstrap the full latex distribution /w init container and persistent storage
              # ... but the base image does not offer a straight-forward way to PV /usr/local/texlive
              repository: ghcr.io/tuetenk0pp/sharelatex-full
              tag: 5.3.1@sha256:5b22c4f3ea7a20d92b0625a24b91276cb22e134ca54faedf377f9e9187b7273b
            envFrom:
              - secret: overleaf-secrets
            env:
              OVERLEAF_APP_NAME: Overleaf
              OVERLEAF_REDIS_HOST: overleaf-redis-master
              REDIS_HOST: overleaf-redis-master
              OVERLEAF_BEHIND_PROXY: "true"
              OVERLEAF_SECURE_COOKIE: "true"
              OVERLEAF_ALLOW_PUBLIC_ACCESS: "false"
              OVERLEAF_SITE_URL: https://overleaf.${SERVICE_DOMAIN}
              OVERLEAF_EMAIL_FROM_ADDRESS: "overleaf@${SERVICE_DOMAIN}"
              OVERLEAF_ADMIN_EMAIL: "overleaf@${SERVICE_DOMAIN}"
              OVERLEAF_EMAIL_REPLY_TO: "overleaf@${SERVICE_DOMAIN}"
              ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"
              ENABLE_CONVERSIONS: "true"
              EMAIL_CONFIRMATION_DISABLED: "false"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: 80
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: 80
            resources:
              requests:
                cpu: 100m
                memory: 700Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/proxy-body-size: 100M
        hosts:
          - host: overleaf.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: overleaf-tls
            hosts:
              - overleaf.${SERVICE_DOMAIN}
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /var/lib/overleaf
