apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: mojo2600
    namespace: default
spec:
    url: https://mojo2600.github.io/pihole-kubernetes/
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR0lFdVFHaUNzNjRzdlRk
            SDcvWUN3am8vOWo5TmdMNHB3RDZXTlU5U0RBCldhM2R2dkYrUTdaUXMxekFrbFNK
            dVBnRDV0R1pPRTM0WElQOTZvc0N2YjAKLS0tIGI4dTg5bXRQb0tvYWVPUjNBWmQ3
            VmYwVSs4TFM4VkI4Znl6Y1VHclBlejAK4jPTJuZjgBUHheKhE4PgFUTUb3ylZA59
            ltnuoNdy6Bssa5iFvsPGlc0qP8QQvY01Xi6x2+M3g+HzfqMf7btRJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T15:16:16Z"
    mac: ENC[AES256_GCM,data:kyoVVOsdeDtNsMRIrf2cpgbYCIt8WyUwHavgZQIExx6hocSsuULWxYl0gmXmzgM/EnzD3AVk+ol3AVYd8dCoUwRI6T0evVnuMjHg1DEDv0c+bqdtFYIlNQjbXrJzZ7oWiM6tyejKy1dARlQUpAGenQlDtouUImTeOkSyPrBBvK8=,iv:poAUMo49iiYt3ghvRENwxw5fbKE1ERQ1Nv8SedQUqu0=,tag:IHUMfeBQrz9FJe25aWnLkA==,type:str]
    pgp: []
    encrypted_regex: ^.*(hosts|whitelist)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pihole
    namespace: default
spec:
    interval: 1m
    chart:
        spec:
            chart: pihole
            version: 2.27.0
            sourceRef:
                kind: HelmRepository
                name: mojo2600
                namespace: default
    values:
        # TODO set cache size to 0 to avoid double-caching
        dualStack:
            enabled: true
        serviceDns:
            mixedService: true
            type: LoadBalancer
            externalTrafficPolicy: Cluster
            annotations:
                metallb.io/allow-shared-ip: default
        serviceDhcp:
            enabled: false
        ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt
            hosts:
                - ENC[AES256_GCM,data:/5GvCCl2d9++Qpfr1vv3wkQUuA==,iv:i0KoiZJJX1UKyXFIwdHGor82ZeZY4t+6x1cF/LYOVQk=,tag:rrDYM5z80Jty8g6X1Y0lnw==,type:str]
            tls:
                - secretName: pihole-tls
                  hosts:
                    - ENC[AES256_GCM,data:YNIBQ2OtxBA5n8fgBWOgx60kZw==,iv:7rf7n0Ru3nlDCh3+UHaiA7bkkNdmmu+sM4uGsRH+BAY=,tag:qBpDB+DLgqwFnr2q/D3x7A==,type:str]
        admin:
            enabled: false
        DNS1: 192.168.1.1
        DNS2: fe80::1
        adlists:
            # everything but the kitchen sink
            - https://big.oisd.nl
            - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt
            - https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
            - https://someonewhocares.org/hosts/zero/hosts
            - https://v.firebog.net/hosts/static/w3kbl.txt
            - https://winhelp2002.mvps.org/hosts.txt
            # ads
            - https://adaway.org/hosts.txt
            - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
            - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
            - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
            - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
            - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/popupads.txt
            - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
            - https://v.firebog.net/hosts/AdguardDNS.txt
            - https://v.firebog.net/hosts/Admiral.txt
            - https://v.firebog.net/hosts/Easylist.txt
            # tracking
            - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
            - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
            - https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt
            - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
            - https://v.firebog.net/hosts/Easyprivacy.txt
            - https://v.firebog.net/hosts/Prigent-Ads.txt
            - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
            # dangerous stuff
            - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
            - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
            - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
            - https://phishing.army/download/phishing_army_blocklist_extended.txt
            - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts_full
            - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
            - https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/hosts.txt
            - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
            - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/tif.txt
            - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
            - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe
            - https://raw.githubusercontent.com/RPiList/specials/refs/heads/master/Blocklisten/notserious
            - https://urlhaus.abuse.ch/downloads/hostfile/
            - https://v.firebog.net/hosts/Prigent-Crypto.txt
            - https://v.firebog.net/hosts/Prigent-Malware.txt
            - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
            # spam
            - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
            - https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
            - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
            # bad reputation
            - https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
            - https://raw.githubusercontent.com/autinerd/anti-axelspringer-hosts/master/axelspringer-hosts
            - https://raw.githubusercontent.com/autinerd/anti-bertelsmann-hosts/master/bertelsmann-hosts
            - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
            - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/gambling.txt
            - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Fake-Science
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
            - https://www.github.developerdan.com/hosts/lists/hate-and-junk-extended.txt
            # device / service specific
            - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
            - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
            - https://raw.githubusercontent.com/TheShawnMiranda/LG-TV-Ad-Block/master/list
            - https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt
            # DOH (DNS is totalitarian in this network!)
            - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/doh.txt
            - https://raw.githubusercontent.com/jpgpi250/piholemanual/master/DOH/DOHadb.txt
        whitelist:
            - ENC[AES256_GCM,data:Lt0qpsWsQZTRF8pr,iv:FNlfWUSgAq6FaupBDOzc2SD0TzJOqQv+nuAEvjtlsos=,tag:Jvb8Qez3b7qKUuWsK1o9Wg==,type:str]
        podDnsConfig:
            enabled: true
            policy: None
            nameservers:
                - 192.168.1.1
                - fe80::1
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR0lFdVFHaUNzNjRzdlRk
            SDcvWUN3am8vOWo5TmdMNHB3RDZXTlU5U0RBCldhM2R2dkYrUTdaUXMxekFrbFNK
            dVBnRDV0R1pPRTM0WElQOTZvc0N2YjAKLS0tIGI4dTg5bXRQb0tvYWVPUjNBWmQ3
            VmYwVSs4TFM4VkI4Znl6Y1VHclBlejAK4jPTJuZjgBUHheKhE4PgFUTUb3ylZA59
            ltnuoNdy6Bssa5iFvsPGlc0qP8QQvY01Xi6x2+M3g+HzfqMf7btRJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T15:16:16Z"
    mac: ENC[AES256_GCM,data:kyoVVOsdeDtNsMRIrf2cpgbYCIt8WyUwHavgZQIExx6hocSsuULWxYl0gmXmzgM/EnzD3AVk+ol3AVYd8dCoUwRI6T0evVnuMjHg1DEDv0c+bqdtFYIlNQjbXrJzZ7oWiM6tyejKy1dARlQUpAGenQlDtouUImTeOkSyPrBBvK8=,iv:poAUMo49iiYt3ghvRENwxw5fbKE1ERQ1Nv8SedQUqu0=,tag:IHUMfeBQrz9FJe25aWnLkA==,type:str]
    pgp: []
    encrypted_regex: ^.*(hosts|whitelist)$
    version: 3.9.2
