apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: linuxserver/qbittorrent
              tag: 5.0.3-r0-ls372
            probes:
              liveness: &qb-probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: 8080
                  periodSeconds: 60
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *qb-probe
            resources:
              requests:
                cpu: 400m
                memory: 400Mi
          gluetun:
            dependsOn: main
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            envFrom:
              - secret: gluetun-secrets
            securityContext:
              # https://github.com/tailscale/tailscale/issues/10814
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
            probes:
              liveness: &gluetun-probe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /gluetun-entrypoint
                      - healthcheck
                  periodSeconds: 60
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *gluetun-probe
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
          port-forward:
            dependsOn: gluetun
            image:
              repository: snoringdragon/gluetun-qbittorrent-port-manager
              tag: 1.3
            env:
              QBITTORRENT_SERVER: localhost
              QBITTORRENT_PORT: "8080"
              PORT_FORWARDED: "/tmp/gluetun/forwarded_port"
            envFrom:
              - secret: gluetun-secrets
            resources:
              requests:
                cpu: 10m
                memory: 35Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: qbittorrent.kthxbye.cyou
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: qbittorrent-tls
            hosts:
              - qbittorrent.kthxbye.cyou
    persistence:
      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
      config:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 500Mi
      incomplete-downloads:
        type: persistentVolumeClaim
        storageClass: cluster-scratch
        accessMode: ReadWriteOnce
        size: 100Gi
      downloads:
        type: nfs
        server: 192.168.1.2
        path: /mnt/tank/Scratch/Torrent
