apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rss-bridge
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/rss-bridge/rss-bridge
              tag: latest@sha256:05b758a554de5c1b391f5247850bb74cab7229ec28caa1b46629ca8e53940fb1
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    configMaps:
      config:
        data:
          config.ini.php: |
            ; <?php exit; ?> DO NOT REMOVE THIS LINE
            [system]
            timezone = "Europe/Berlin"
            [error]
            output = "http"
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: rssbridge.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: rss-bridge-tls
            hosts:
              - rssbridge.${SERVICE_DOMAIN}
    persistence:
      config:
        type: configMap
        name: rss-bridge-config
