apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soundcloud-scraper
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "*/15 * * * *"
          concurrencyPolicy: Replace
        containers:
          main:
            image:
              repository: ghcr.io/c0nsultant/soundcloud-scraper
              tag: v1.1.1@sha256:dde620080cd90161929560f5741072aaf40cc26cbc72c8daf838d6c52716146b
            env:
              DATA_DIR: /data
              SOUNDCLOUD_USERNAME: psykko0
            envFrom:
              - secret: soundcloud-scraper-secrets
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 500Mi
