apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: stirling-pdf-chart
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: default
  values:
    image:
      registry: ghcr.io
      repository: stirling-tools/stirling-pdf
      tag: 0.40.2-fat@sha256:0d30644dd8f632c532721d495fcd2f19452ee4da5427cd1bbe352f2c9d4260a0
    envs:
      - name: SYSTEM_DEFAULTLOCALE
        value: de-DE
      - name: SYSTEM_SHOWUPDATE
        value: "false"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - name: stirling-pdf.${SERVICE_DOMAIN}
        path: /
        tls: true
        tlsSecret: stirling-pdf-tls
    resources:
      requests:
        cpu: 10m
        memory: 600Mi
    probes:
      liveness:
        initialDelaySeconds: 30
      readiness:
        initialDelaySeconds: 30
