apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: stirling-pdf-chart
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: stirling-tools/stirling-pdf
      tag: 0.45.3-fat@sha256:80509ded67825f8f5498bf8c112edd60a51d4e98ac276d04aeb22f09eb33e116
    envs:
      - name: SYSTEM_DEFAULTLOCALE
        value: de-DE
      - name: SYSTEM_SHOWUPDATE
        value: "false"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - name: stirling-pdf.${SERVICE_DOMAIN}
        path: /
        tls: true
        tlsSecret: stirling-pdf-tls
    resources:
      requests:
        cpu: 10m
        memory: 600Mi
    probes:
      liveness:
        initialDelaySeconds: 30
      readiness:
        initialDelaySeconds: 30
