apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: unifi-controller-mongodb
    namespace: default
spec:
    interval: 1m
    chart:
        spec:
            chart: mongodb
            version: 16.4.0
            sourceRef:
                kind: HelmRepository
                name: bitnami
                namespace: flux-system
    values:
        global:
            defaultStorageClass: cluster-replicated
        image:
            tag: 8.0.4
        architecture: standalone
        useStatefulSet: true
        auth:
            rootUser: ENC[AES256_GCM,data:MsPyBw==,iv:UZxFZNcvq7rkTIYZPrQHkl5wFErQppoO2wt2R+/RoY8=,tag:Hh0Ji9zJ4LlVmnDC2sRakQ==,type:str]
            rootPassword: ENC[AES256_GCM,data:/jMuaF6Yd0lFF4RLlbU5zCm4Zh5yoEAx97JLUfHr4y4=,iv:BAqgCYTFFQRSl3p+wwz5QzPI8r49gZvDSGgTUhDTVww=,tag:QnH0KIOqQ6YwLs2XIPb4Dg==,type:str]
        extraEnvVars:
            - name: ENC[AES256_GCM,data:nogEiUWROh5g9KszjVH5mCe5HBPBaGIcAI8=,iv:4ebZY5ENz5hCtdGFfxXRLx0WGL3eaE1ovKFqhzCIor8=,tag:1FEreO1QU4xHSmzxhntMXg==,type:str]
              value: ENC[AES256_GCM,data:gC5ltg==,iv:MTwSEP0uh0PLUHVl5wGks2YJjs9mGVR+Qxvk4XgFOlI=,tag:0i2dy37heBuDz4+f9DoAbQ==,type:str]
            - name: ENC[AES256_GCM,data:9frwJoJ6VkB8qehvvCOw6IuKzSLAzE+uOnM=,iv:bAPiOqOWIJSR8y6vFQ1hRRxSt0QFWJ4rH9eg6KeC75o=,tag:ZxuL1nDw4+XD5lH7daS0AA==,type:str]
              value: ENC[AES256_GCM,data:whaI6dHaHkR1NgY0i9pxLwlg11h0CF0xB1aboNVAHn4=,iv:ryskZ9up4ISuY5DhML1KWGlSl6FPOBHujFO1UToAPmk=,tag:nzfVD+6ZAZgOyEcpByZA4g==,type:str]
            - name: ENC[AES256_GCM,data:syeknmSnhEfhsg==,iv:HM5LCH4i6t5+42GaYYFIncejv1Z7lDWQkLXcRDjrkrM=,tag:seuR/HZPw5YfSnuYQNITdw==,type:str]
              value: ENC[AES256_GCM,data:aUfRWfQ=,iv:rq/PS8nT1DJhEs/vwmGyGt729/yOwt6jjup/w2wFCME=,tag:8TijO+/+wQ2tz4leOlssSQ==,type:str]
            - name: ENC[AES256_GCM,data:BRSdXkN+rKKUWQ==,iv:yqG1Cc4SD7CHplH5WvkM/M1LpAStwl20khiPQUcEX6M=,tag:VRsPWwWmbyKsB0TiCF1eug==,type:str]
              value: ENC[AES256_GCM,data:83E1W5s5xZYgp77jUcEFCSjcOAWlCD6XhA5kH6SL+qo=,iv:tyRPwWNUVeI50G3ifr9JkFmP5t3ExXYBkO/FD+O+KDI=,tag:axU3I0W0RLgcHLWiy5KtNA==,type:str]
            - name: ENC[AES256_GCM,data:FkoQRAkJeFg3wyUx,iv:ZpwSo1Z6Pw/T8EGQeGp2oX35k5zZ9s6dHRM6/6AUS0Y=,tag:auxP49GR5A4ysKP5pMGeVg==,type:str]
              value: ENC[AES256_GCM,data:aUfRWfQ=,iv:rq/PS8nT1DJhEs/vwmGyGt729/yOwt6jjup/w2wFCME=,tag:8TijO+/+wQ2tz4leOlssSQ==,type:str]
            - name: ENC[AES256_GCM,data:aivqWOOYY477zs8ycfZ0AA==,iv:Fosu9E12rXCVJXw0VVFlE3NlF34wp7B54jzAM7TZuSg=,tag:UApsoxW+pzIigXXgQty3Kg==,type:str]
              value: ENC[AES256_GCM,data:0ltSaoE=,iv:b2gqVZFoUvM5KDDsQooxfB4tM7FTuXK6LFnYadLZ7QM=,tag:o8AildpOMF+4SuourLhYiA==,type:str]
        initdbScripts:
            # https://github.com/linuxserver/docker-unifi-network-application?tab=readme-ov-file#setting-up-your-external-database
            init-unifi-user.sh: |
                #!/bin/bash
                if which mongosh > /dev/null 2>&1; then
                  mongo_init_bin='mongosh'
                else
                  mongo_init_bin='mongo'
                fi
                "${mongo_init_bin}" <<EOF
                use ${MONGO_AUTHSOURCE}
                db.auth("${MONGO_INITDB_ROOT_USERNAME}", "${MONGO_INITDB_ROOT_PASSWORD}")
                db.createUser({
                  user: "${MONGO_USER}",
                  pwd: "${MONGO_PASS}",
                  roles: [
                    { db: "${MONGO_DBNAME}", role: "dbOwner" },
                    { db: "${MONGO_DBNAME}_stat", role: "dbOwner" }
                  ]
                })
                EOF
        persistence:
            enabled: true
            size: 2Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dFBwTW4xV2JQT2JybGdh
            S1c2Z2ZqVnFKM0lYbnIwbzJhMisvWWpuVUVZCkhsQTMvUlBYMkFtNFIwTGtDcmx6
            NURReUNaWHVCMW5XMEJnSjZmQmdjV0EKLS0tIHMveXY4UlVuRytEOGRvaThtK0s2
            d2RMVFVMK3ZCSTVWZk5lbEUvczArZVUKx9Cu2hk548SblTGt89K7UMvGUdeBcJ3r
            4K8lYVHkSZC8pU5VS+8QNUKljIRdh6SG6dUV1HrVjl0ENvEagaH9cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T17:37:40Z"
    mac: ENC[AES256_GCM,data:PA5pNDuELT1I/f8JPEnEykY1wetcb5dsz4jRG1i0R2ilohvUfI9IV0CSwSNvzCvVmwoP3RiU5+zWp3II4Dkduot5MVdIHkRDY3c1HWvsBHku2pCpx7MqRroRE3AFnfaZ2BCkU0OdMjiqkiufhvLreeabdS0/U0NIjfsSiojGaek=,iv:6SBZWx3NZzOzHT/xubileYGtM8Ljx/vEMh7S6lXPQIg=,tag:XtUl78TpXSfwmdFPOrZ5jA==,type:str]
    pgp: []
    encrypted_regex: ^.*(auth|extraEnvVars|env|hosts)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: unifi-controller
    namespace: default
spec:
    interval: 1m
    chart:
        spec:
            chart: app-template
            version: 3.6.0
            sourceRef:
                kind: HelmRepository
                name: bjw-s
                namespace: default
    values:
        controllers:
            main:
                containers:
                    main:
                        image:
                            repository: linuxserver/unifi-network-application
                            tag: 8.6.9-ls73
                        env:
                            TZ: ENC[AES256_GCM,data:J/G0VloDmp+zJ5lFwQ==,iv:DYVa6C0YecrgQNHl/njcxntCqPesQhBCZTrMmsh7epM=,tag:gl9ZqjM5pZkm50HyaiLxGg==,type:str]
                            MONGO_HOST: ENC[AES256_GCM,data:Ju+FmtgLEpYV4OIhgxfzU/M0XyEmCOiO,iv:qoQFL69glRo+C9eJAP/u0JSJmYfwiX10qRqA4F8O4zo=,tag:SDMqmHBeIyo6xEYPbasMMg==,type:str]
                            MONGO_PORT: ENC[AES256_GCM,data:1XrNSk0=,iv:71BDnspU60GtlDS7DOoMn90iQszM9Fx0WVVD84Qq5+s=,tag:0dFL+SeA1T+XShJhDf5isA==,type:int]
                            MONGO_USER: ENC[AES256_GCM,data:B7zw6jc=,iv:zlBtSHufni0Iu8XPfSZ7cQ/lpMoa4C2/eWHOcmIbtks=,tag:rfvrkXUaH8+HnpMqeC8qUg==,type:str]
                            MONGO_PASS: ENC[AES256_GCM,data:oaWAzc22sixqX0B7UAxZjQaNWDDu4Npq2GUpHxaTF7E=,iv:+ZB0yyhDML6zmWDkSt/DWFUyYOS6no2fVXtWwjWGfvs=,tag:5l5KR/n2GJOVKcj62BqLXw==,type:str]
                            MONGO_DBNAME: ENC[AES256_GCM,data:xy6CQXs=,iv:8o6xxs795V6e6zyVGuPxVVbe3gjmgksTKj6jY/ZL2aw=,tag:qVAcSfvEPk3lUj/vWg9igQ==,type:str]
                            MONGO_AUTHSOURCE: ENC[AES256_GCM,data:zNZN52w=,iv:Jf9SV6alNCXF0CCdzmjAw8Z2znzHsxsIRJlTS8cC0LI=,tag:Z/zhgq+Q5i9AuMCeC10MJQ==,type:str]
                        probes:
                            liveness:
                                enabled: true
                                custom: true
                                spec:
                                    httpGet:
                                        path: /setup/
                                        port: 8080
                            readiness:
                                enabled: true
                                custom: true
                                spec:
                                    httpGet:
                                        path: /setup/
                                        port: 8080
        service:
            external:
                controller: main
                type: LoadBalancer
                annotations:
                    metallb.io/allow-shared-ip: default
                ports:
                    controller:
                        port: 8080
                        protocol: HTTP
                    speedtest:
                        port: 6789
                        protocol: TCP
                    stun:
                        port: 3478
                        protocol: UDP
                    syslog:
                        port: 5514
                        protocol: UDP
                    discovery:
                        port: 10001
                        protocol: UDP
                    l2discovery:
                        port: 1900
                        protocol: UDP
            internal:
                controller: main
                ports:
                    https:
                        port: 8443
                        protocol: HTTPS
        ingress:
            main:
                className: nginx
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
                hosts:
                    - host: ENC[AES256_GCM,data:Uv6GPtI6JBOIHCYhRRP5+/lD,iv:0u4LG+e59M/zQe5JXiTwzeV6YtqDrs21kZK71rAS9a8=,tag:CH0RqNgIgFCFqMEzSZ2oMQ==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:mw==,iv:Da5J0bNh2UtTQObKQpA0E6sqkvQgh/Fl8FtF76gRi0I=,tag:5QUAgPcXSnpOYVC6ujwjog==,type:str]
                          service:
                            identifier: ENC[AES256_GCM,data:HjUwRavMaks=,iv:EsWz/JOnlk+tJyld6/4SpVNPNVmIqxJ98hUVfKrQ0Iw=,tag:8TB17unhQXQwN0RFMm8O7A==,type:str]
                            port: ENC[AES256_GCM,data:u4/Wq9k=,iv:tpKyDX7i7NOfSaOcT5HBjq/Ayu0AciMTJN6GW3gTKDg=,tag:ABTRsRhnZX71XNTGpgKrcA==,type:str]
                tls:
                    - secretName: unifi-tls
                      hosts:
                        - ENC[AES256_GCM,data:0ZcnZnTz8rA0miYLRez0gnra,iv:toaG+hiVPLbhU5Xg7SUjLJ04Dta2w8ypIy6L028MdO0=,tag:REo3zimt8c2VviGeagyk7A==,type:str]
        persistence:
            config:
                type: persistentVolumeClaim
                storageClass: cluster-replicated
                accessMode: ReadWriteOnce
                size: 2Gi
                globalMounts:
                    - path: /config
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dFBwTW4xV2JQT2JybGdh
            S1c2Z2ZqVnFKM0lYbnIwbzJhMisvWWpuVUVZCkhsQTMvUlBYMkFtNFIwTGtDcmx6
            NURReUNaWHVCMW5XMEJnSjZmQmdjV0EKLS0tIHMveXY4UlVuRytEOGRvaThtK0s2
            d2RMVFVMK3ZCSTVWZk5lbEUvczArZVUKx9Cu2hk548SblTGt89K7UMvGUdeBcJ3r
            4K8lYVHkSZC8pU5VS+8QNUKljIRdh6SG6dUV1HrVjl0ENvEagaH9cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T17:37:40Z"
    mac: ENC[AES256_GCM,data:PA5pNDuELT1I/f8JPEnEykY1wetcb5dsz4jRG1i0R2ilohvUfI9IV0CSwSNvzCvVmwoP3RiU5+zWp3II4Dkduot5MVdIHkRDY3c1HWvsBHku2pCpx7MqRroRE3AFnfaZ2BCkU0OdMjiqkiufhvLreeabdS0/U0NIjfsSiojGaek=,iv:6SBZWx3NZzOzHT/xubileYGtM8Ljx/vEMh7S6lXPQIg=,tag:XtUl78TpXSfwmdFPOrZ5jA==,type:str]
    pgp: []
    encrypted_regex: ^.*(auth|extraEnvVars|env|hosts)$
    version: 3.9.2
