apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    # https://metallb.io/installation/#installation-with-helm
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
