apiVersion: v1
kind: Namespace
metadata:
    name: external-dns-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld252Y3F3RTFaektnZzRG
            SVZmOS9LZm5HTkxFamI5QTRyYUI1Zms5Y3lnCldWenNtYUtmemZKVG0za1E0c0tT
            b2EvL3dXRFE3em9ud1BBU3lYUXRHa0EKLS0tIFpxaVJtM0twZUI4a05IV3Q1bnI4
            UXhTWkNVbjJCai9mcFlFUWwvNUs0TTAKXYNpGFeLBD0OkmSPOZsl7rIU0X+Wryu+
            IgN7dIJdoKQRiQZj90hQeFYJ13wy4I2bf0ujM5nafXTaJrkj/AlPuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T16:46:18Z"
    mac: ENC[AES256_GCM,data:JlpOaoeibzEA8eiFtrdzZwzDv/c5MSoqrWV1sv2y2ebMRrNpeCbXjBClt14fzcjdYU9cnSufvQi2bJifC6PrqfaDJqwSsELJWmwIN6qQoDeQmDZ0W1zksBEWSnn/ROE7OTlXfW83xLIpN9Hee0TVC9XzqDErzqJBJ260b8aV9Tw=,iv:WsMjnLICobwGsv74yHlLsRcramLZu+LebErtMTdl1c8=,tag:HUU+3d/UUAo9V6gMo7zlGg==,type:str]
    pgp: []
    encrypted_regex: ^.*(provider|extraArgs)$
    version: 3.9.2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: external-dns
    namespace: external-dns-system
spec:
    url: https://kubernetes-sigs.github.io/external-dns/
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld252Y3F3RTFaektnZzRG
            SVZmOS9LZm5HTkxFamI5QTRyYUI1Zms5Y3lnCldWenNtYUtmemZKVG0za1E0c0tT
            b2EvL3dXRFE3em9ud1BBU3lYUXRHa0EKLS0tIFpxaVJtM0twZUI4a05IV3Q1bnI4
            UXhTWkNVbjJCai9mcFlFUWwvNUs0TTAKXYNpGFeLBD0OkmSPOZsl7rIU0X+Wryu+
            IgN7dIJdoKQRiQZj90hQeFYJ13wy4I2bf0ujM5nafXTaJrkj/AlPuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T16:46:18Z"
    mac: ENC[AES256_GCM,data:JlpOaoeibzEA8eiFtrdzZwzDv/c5MSoqrWV1sv2y2ebMRrNpeCbXjBClt14fzcjdYU9cnSufvQi2bJifC6PrqfaDJqwSsELJWmwIN6qQoDeQmDZ0W1zksBEWSnn/ROE7OTlXfW83xLIpN9Hee0TVC9XzqDErzqJBJ260b8aV9Tw=,iv:WsMjnLICobwGsv74yHlLsRcramLZu+LebErtMTdl1c8=,tag:HUU+3d/UUAo9V6gMo7zlGg==,type:str]
    pgp: []
    encrypted_regex: ^.*(provider|extraArgs)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-dns
    namespace: external-dns-system
spec:
    interval: 1m
    chart:
        spec:
            chart: external-dns
            version: v1.15.0
            sourceRef:
                kind: HelmRepository
                name: external-dns
                namespace: external-dns-system
    values:
        policy: sync
        provider: ENC[AES256_GCM,data:JnJn7HbVDA==,iv:FK4yvabheVPLl3g0Q6v6gL6tfLnn9GeJBJA0O0ybckA=,tag:1IvcGi0XDR3Ih/+O7BdyvA==,type:str]
        extraArgs:
            - ENC[AES256_GCM,data:FsrbOCAs529h2RomG+CMvY+eJwJocSccYF8=,iv:CrWGiaoL29XkgGNjq+76OAKEqxEG1LTt/1o2ttfLBZM=,tag:i0+e0PGpDCiftQQWslom3w==,type:str]
            - ENC[AES256_GCM,data:etYI7FS7VHdGLUGIzRY5wyhpjQ==,iv:CB1Smm2yrJINOZSXQGnvMPvLadWy4yTAaYayNxQzrEY=,tag:wma6ZlfgSfTXE863E3LzQg==,type:str]
            - ENC[AES256_GCM,data:24yMC7DXtktEAnTxwoGdeWxzCg9YQoCQOcgU,iv:rfnz2Oyx4wPbAIMWrbDDMq/0FvjIHpnrnqTv9D/qgvY=,tag:L40DAZAJHWIjEIRfnesk1A==,type:str]
            - ENC[AES256_GCM,data:+YYTaABueNqijiiMsRUClFX4kmG7,iv:cIa3PY0981jeulw295rmPud3rW5twumU3sF4/muu+74=,tag:zGHjCbzN4nNPAKYPUT2Yzw==,type:str]
            - ENC[AES256_GCM,data:LVwnLDsjkUs6KvAql1ZqrYjJ8X0eu8UwEUYyFEjjKtEyl3+ghTKjbO6CWiCmZr33iNv+cO9cxFVmt7ZxG37PBx8g,iv:bjkiUi23DsuBM5XHgvfIY7w4pZiLruvkBnpcGvDrF3g=,tag:91tNWCTJhwTb1CoWbsysaQ==,type:str]
            - ENC[AES256_GCM,data:GZXBB2seV1M/cY+y10BgQjqVLGVf69X9CCL3ZmUNX7fmj+0N+Q==,iv:oa2bTqGTGHH6mSmv29Is40Bv140OJNknm+wcgdAAsMc=,tag:r3f+d1R6Cuu8o2VaId+5Sg==,type:str]
            - ENC[AES256_GCM,data:f/AEekz8zPiyCNDSDdUeo+JlUTzqYSK+5h3VM19dqg==,iv:Jb+He1z1cA7xu6QhJ/Si083TbUDGEj4fUkTz9cJjUU0=,tag:YPd28MDH1jWYWi6r1aP8Nw==,type:str]
            - ENC[AES256_GCM,data:O/pY1eo5Va1Tf7SR1fF2ClcCaw==,iv:GgIgNfP3hx2Qx3lGG3OClobLxJtGtw6pkoczr6Cp+Os=,tag:y9B5i9quThIq/kcDERncrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBld252Y3F3RTFaektnZzRG
            SVZmOS9LZm5HTkxFamI5QTRyYUI1Zms5Y3lnCldWenNtYUtmemZKVG0za1E0c0tT
            b2EvL3dXRFE3em9ud1BBU3lYUXRHa0EKLS0tIFpxaVJtM0twZUI4a05IV3Q1bnI4
            UXhTWkNVbjJCai9mcFlFUWwvNUs0TTAKXYNpGFeLBD0OkmSPOZsl7rIU0X+Wryu+
            IgN7dIJdoKQRiQZj90hQeFYJ13wy4I2bf0ujM5nafXTaJrkj/AlPuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T16:46:18Z"
    mac: ENC[AES256_GCM,data:JlpOaoeibzEA8eiFtrdzZwzDv/c5MSoqrWV1sv2y2ebMRrNpeCbXjBClt14fzcjdYU9cnSufvQi2bJifC6PrqfaDJqwSsELJWmwIN6qQoDeQmDZ0W1zksBEWSnn/ROE7OTlXfW83xLIpN9Hee0TVC9XzqDErzqJBJ260b8aV9Tw=,iv:WsMjnLICobwGsv74yHlLsRcramLZu+LebErtMTdl1c8=,tag:HUU+3d/UUAo9V6gMo7zlGg==,type:str]
    pgp: []
    encrypted_regex: ^.*(provider|extraArgs)$
    version: 3.9.2
