apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZi9sVlFWN0YzNEM1Tjdv
            cXMzV2d1QUx6am5hNk5HSmJJNTFqM05meWxzCjlQYTBHdjNteENQMVZRQTFhTVY5
            NE1GN09jOFVMODM4NHNYVWV3OXhVblEKLS0tIGdib0VlT0RBajZ5ZmVZZlNQa0NK
            aktKbTNBRVJ0MTNSWlUyMzhyWkozVncKQyu+Que2dXrQ26BavoBroDWT8JDvjYgp
            qHuUz0xh3SMKW3KwQHyWGD/rz+09CSXe9In+tRuCtiK1JPNVnwOprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T20:14:45Z"
    mac: ENC[AES256_GCM,data:UVFC5j849f0ywnQ8vPksmZ1ou4WHv0AoL8dolWeBTbud1aCqwOzC7ge4iFztaHaESviJLck0jBTKU7qvLlPSPmM5ipsZLxr0WOJf5vsMoqY9NHkgmfYtw2yuLlGIIacqdzX754d0UvxE/w4NC31rS9rsqLvCPBOyU1rcm7/zQz8=,iv:Bspn4gGhN275GKIlevoEsenFp9DkCnxtiXpSqZi52FY=,tag:6PtvUCzz4ZdCW0QECnL4NA==,type:str]
    pgp: []
    encrypted_regex: ^.*(email|api-token)$
    version: 3.9.2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: jetstack
    namespace: cert-manager-system
spec:
    url: https://charts.jetstack.io
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZi9sVlFWN0YzNEM1Tjdv
            cXMzV2d1QUx6am5hNk5HSmJJNTFqM05meWxzCjlQYTBHdjNteENQMVZRQTFhTVY5
            NE1GN09jOFVMODM4NHNYVWV3OXhVblEKLS0tIGdib0VlT0RBajZ5ZmVZZlNQa0NK
            aktKbTNBRVJ0MTNSWlUyMzhyWkozVncKQyu+Que2dXrQ26BavoBroDWT8JDvjYgp
            qHuUz0xh3SMKW3KwQHyWGD/rz+09CSXe9In+tRuCtiK1JPNVnwOprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T20:14:45Z"
    mac: ENC[AES256_GCM,data:UVFC5j849f0ywnQ8vPksmZ1ou4WHv0AoL8dolWeBTbud1aCqwOzC7ge4iFztaHaESviJLck0jBTKU7qvLlPSPmM5ipsZLxr0WOJf5vsMoqY9NHkgmfYtw2yuLlGIIacqdzX754d0UvxE/w4NC31rS9rsqLvCPBOyU1rcm7/zQz8=,iv:Bspn4gGhN275GKIlevoEsenFp9DkCnxtiXpSqZi52FY=,tag:6PtvUCzz4ZdCW0QECnL4NA==,type:str]
    pgp: []
    encrypted_regex: ^.*(email|api-token)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: cert-manager-system
spec:
    interval: 1m
    chart:
        spec:
            chart: cert-manager
            version: v1.16.2
            sourceRef:
                kind: HelmRepository
                name: jetstack
                namespace: cert-manager-system
    values:
        crds:
            enabled: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZi9sVlFWN0YzNEM1Tjdv
            cXMzV2d1QUx6am5hNk5HSmJJNTFqM05meWxzCjlQYTBHdjNteENQMVZRQTFhTVY5
            NE1GN09jOFVMODM4NHNYVWV3OXhVblEKLS0tIGdib0VlT0RBajZ5ZmVZZlNQa0NK
            aktKbTNBRVJ0MTNSWlUyMzhyWkozVncKQyu+Que2dXrQ26BavoBroDWT8JDvjYgp
            qHuUz0xh3SMKW3KwQHyWGD/rz+09CSXe9In+tRuCtiK1JPNVnwOprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T20:14:45Z"
    mac: ENC[AES256_GCM,data:UVFC5j849f0ywnQ8vPksmZ1ou4WHv0AoL8dolWeBTbud1aCqwOzC7ge4iFztaHaESviJLck0jBTKU7qvLlPSPmM5ipsZLxr0WOJf5vsMoqY9NHkgmfYtw2yuLlGIIacqdzX754d0UvxE/w4NC31rS9rsqLvCPBOyU1rcm7/zQz8=,iv:Bspn4gGhN275GKIlevoEsenFp9DkCnxtiXpSqZi52FY=,tag:6PtvUCzz4ZdCW0QECnL4NA==,type:str]
    pgp: []
    encrypted_regex: ^.*(email|api-token)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager-system
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:H/S3jHhm7ffRpZvhBKdJMEdYblkvpy+cKUv/mKPUHbYXOTtzauk6dg==,iv:jswclIv9NqZisFK7ekPnbzruo1Fr4fixqS+BRpmYPx8=,tag:tCGCc9OOl0zSZ4rmpsCKrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZi9sVlFWN0YzNEM1Tjdv
            cXMzV2d1QUx6am5hNk5HSmJJNTFqM05meWxzCjlQYTBHdjNteENQMVZRQTFhTVY5
            NE1GN09jOFVMODM4NHNYVWV3OXhVblEKLS0tIGdib0VlT0RBajZ5ZmVZZlNQa0NK
            aktKbTNBRVJ0MTNSWlUyMzhyWkozVncKQyu+Que2dXrQ26BavoBroDWT8JDvjYgp
            qHuUz0xh3SMKW3KwQHyWGD/rz+09CSXe9In+tRuCtiK1JPNVnwOprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T20:14:45Z"
    mac: ENC[AES256_GCM,data:UVFC5j849f0ywnQ8vPksmZ1ou4WHv0AoL8dolWeBTbud1aCqwOzC7ge4iFztaHaESviJLck0jBTKU7qvLlPSPmM5ipsZLxr0WOJf5vsMoqY9NHkgmfYtw2yuLlGIIacqdzX754d0UvxE/w4NC31rS9rsqLvCPBOyU1rcm7/zQz8=,iv:Bspn4gGhN275GKIlevoEsenFp9DkCnxtiXpSqZi52FY=,tag:6PtvUCzz4ZdCW0QECnL4NA==,type:str]
    pgp: []
    encrypted_regex: ^.*(email|api-token)$
    version: 3.9.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt
    namespace: cert-manager-system
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:v+3lu/exLlyoaXbB5HtP4+d1m0SBh+Y2,iv:Y/DalpXs/tyvzh0M0kwnM38lK4NoiyYFjGEkduvkDtc=,tag:CzMva7XoRTDsMUx/G7vvEQ==,type:str]
        privateKeySecretRef:
            name: letsencrypt
        solvers:
            - dns01:
                cloudflare:
                    email: ENC[AES256_GCM,data:1Y0Xqp/b055zNFnMy3SGBxd68qA/RoY=,iv:z2tDHlSBXbEHSTItJsjDbU0/bvWqfzXkOS0vNJ4RDC4=,tag:tiFrewDJdAAu17Diyc/AAw==,type:str]
                    apiTokenSecretRef:
                        name: cloudflare-api-token
                        key: api-token
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZi9sVlFWN0YzNEM1Tjdv
            cXMzV2d1QUx6am5hNk5HSmJJNTFqM05meWxzCjlQYTBHdjNteENQMVZRQTFhTVY5
            NE1GN09jOFVMODM4NHNYVWV3OXhVblEKLS0tIGdib0VlT0RBajZ5ZmVZZlNQa0NK
            aktKbTNBRVJ0MTNSWlUyMzhyWkozVncKQyu+Que2dXrQ26BavoBroDWT8JDvjYgp
            qHuUz0xh3SMKW3KwQHyWGD/rz+09CSXe9In+tRuCtiK1JPNVnwOprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T20:14:45Z"
    mac: ENC[AES256_GCM,data:UVFC5j849f0ywnQ8vPksmZ1ou4WHv0AoL8dolWeBTbud1aCqwOzC7ge4iFztaHaESviJLck0jBTKU7qvLlPSPmM5ipsZLxr0WOJf5vsMoqY9NHkgmfYtw2yuLlGIIacqdzX754d0UvxE/w4NC31rS9rsqLvCPBOyU1rcm7/zQz8=,iv:Bspn4gGhN275GKIlevoEsenFp9DkCnxtiXpSqZi52FY=,tag:6PtvUCzz4ZdCW0QECnL4NA==,type:str]
    pgp: []
    encrypted_regex: ^.*(email|api-token)$
    version: 3.9.2
