---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager-system
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ZYySJX2aGU0k+YxA0o8GjDzQKMMS+dVtzINlf+Yfwoxpp35iOrtt5g==,iv:dJbM8fvYzNCaUr5XVMZLLLO7ehLMBMO606RpShYCEo8=,tag:joRvbcix0nP5TWWeeSI1zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZi9sVlFWN0YzNEM1Tjdv
            cXMzV2d1QUx6am5hNk5HSmJJNTFqM05meWxzCjlQYTBHdjNteENQMVZRQTFhTVY5
            NE1GN09jOFVMODM4NHNYVWV3OXhVblEKLS0tIGdib0VlT0RBajZ5ZmVZZlNQa0NK
            aktKbTNBRVJ0MTNSWlUyMzhyWkozVncKQyu+Que2dXrQ26BavoBroDWT8JDvjYgp
            qHuUz0xh3SMKW3KwQHyWGD/rz+09CSXe9In+tRuCtiK1JPNVnwOprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T17:32:52Z"
    mac: ENC[AES256_GCM,data:FnEqDwWnatKc1J2ARkYXP/ZIcRlzSRKIMpCg7Z0zxT9bJ28gsiBbpzB2TDMQI1C+ekK6CaYsIBA2R+E++EzWlkfCtryqGkwFFZBqjMgZJVHOaU19UmeJgcUTfNzYviLE9E7tzyo+tRLoRecqQUa++20Qc2Ebh6Gb1iLy0ybeMkI=,iv:OnBc5nsxR6f3aEA3Hvg4MW+r5Le3QL5nUZ3SmwcI8A4=,tag:QT2LF7tjoXiuFjGyhTpvUg==,type:str]
    pgp: []
    encrypted_regex: ^.*(email|api-token)$
    version: 3.9.2
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: letsencrypt
    namespace: cert-manager-system
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:TepY4vjXo18wnL+j6zOmaw==,iv:8IQvJ3fJYWcvBBlApyj1S/R/VCtveCJwKSd1FWPvxtg=,tag:ObZm7Ft6i2zkDzrNOZOInQ==,type:str]
        privateKeySecretRef:
            name: letsencrypt
        solvers:
            - dns01:
                cloudflare:
                    serviceAccountSecretRef:
                        name: cert-manager-system
                        key: api-token
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZi9sVlFWN0YzNEM1Tjdv
            cXMzV2d1QUx6am5hNk5HSmJJNTFqM05meWxzCjlQYTBHdjNteENQMVZRQTFhTVY5
            NE1GN09jOFVMODM4NHNYVWV3OXhVblEKLS0tIGdib0VlT0RBajZ5ZmVZZlNQa0NK
            aktKbTNBRVJ0MTNSWlUyMzhyWkozVncKQyu+Que2dXrQ26BavoBroDWT8JDvjYgp
            qHuUz0xh3SMKW3KwQHyWGD/rz+09CSXe9In+tRuCtiK1JPNVnwOprQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T17:32:52Z"
    mac: ENC[AES256_GCM,data:FnEqDwWnatKc1J2ARkYXP/ZIcRlzSRKIMpCg7Z0zxT9bJ28gsiBbpzB2TDMQI1C+ekK6CaYsIBA2R+E++EzWlkfCtryqGkwFFZBqjMgZJVHOaU19UmeJgcUTfNzYviLE9E7tzyo+tRLoRecqQUa++20Qc2Ebh6Gb1iLy0ybeMkI=,iv:OnBc5nsxR6f3aEA3Hvg4MW+r5Le3QL5nUZ3SmwcI8A4=,tag:QT2LF7tjoXiuFjGyhTpvUg==,type:str]
    pgp: []
    encrypted_regex: ^.*(email|api-token)$
    version: 3.9.2