---
apiVersion: v1
kind: Namespace
metadata:
    name: external-dns-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: external-dns
    namespace: external-dns-system
spec:
    url: https://kubernetes-sigs.github.io/external-dns/
