---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  lables:
    # https://metallb.io/installation/#installation-with-helm
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1m
  chart:
    spec:
      chart: metallb
      version: "v0.14.8"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  values:
    speaker:
      enabled: true
      frr:
        enabled: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: service-vip
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.220/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
