---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik-system
spec:
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1m
  chart:
    spec:
      chart: traefik
      version: "v33.1.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-system
  values:
    ports:
      websecure:
        http3:
          enabled: true
          advertisedPort: 443
