apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-secrets
    namespace: default
type: Opaque
stringData:
    database-uri: ENC[AES256_GCM,data:ZtD7ugMgnz+C8LKFoyrSeKupqwoSbVkWaQhnMFolk+WGU+JAXQqsHHouG1ry7OcFxwhP1rvO8C2LxBTI2Jz7HJHpRuU0j4lNdUd8cEyHj81P/l1ANy5SVvzOSai1s2dBenG86g==,iv:dN7whQWmi487W41CPY8w8iMoIL977r89awJM0F27vWA=,tag:hzwp2nImyS+xmuX14vNevQ==,type:str]
    installation-id: ENC[AES256_GCM,data:OHf6UC9seVkknp9vfyIpCrXOcosf6Nlgxi9FVKVZyvYk+DMe,iv:lIlpcMHpVA5fMZupHz5EvtCZxa1GZnzkXFlE4DHH+vY=,tag:5AZdhMhNI2UGlrgyUGNyUQ==,type:str]
    installation-key: ENC[AES256_GCM,data:Tntvn+/vMIBn5QE2M1CxaU++Xv0=,iv:5Ra+wj7OQFGB1H5CZRd0UFCet2nwigMUIEagHXNWTaY=,tag:Or7rMmhBijEjozpD6j7/CA==,type:str]
    admin-token: ENC[AES256_GCM,data:wq2dmFpVs6tuoh3zbZ0bDcJCIZ7VzXiu7tSXE/MDxV2poQlWNQ15IvqcwSHcp/Jnk90JW4GDg8pXIlhJDGAxCA==,iv:BbovBmWZXruAkXDtHU0EsvQb+EhWUk8II/CcOlzHPmc=,tag:ju1RSO8susuNb1XT5uIVFg==,type:str]
    smtp-username: ENC[AES256_GCM,data:QfZq5JxL,iv:Cl4IOvzC6EM2hcfgDq/F/cAJfzPxeHCATB69fatY5co=,tag:flB+jvWjAWBsR69ClTGNaQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:LtO/XJAxya00oyEP+zgbvvSGrLNGx0lTqwEmaQ6IwUB469AjlfMJUf+OemRIoXDbYQzTPG9Hl0lQwr9u50FShReVTpD0,iv:2jn36ZgEQIpWrR8rCODGfTmmv2C4GJRIFFanP9J4QnM=,tag:9sIwsLupEW/NYII8hyGpRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T19:53:37Z"
    mac: ENC[AES256_GCM,data:SA/5Yx0Y/ObsWQsgZfgQrmhP4GRZcxlnyAqwlElFIQllTxBjnddoyjDvFaAMCksCCPw2pTkwj3WiHzc9xb3FaJdc+Nv4n9yU1WtSQLdgHrAyw07hd2j1hxjiKshE8xbx7V94kvlc7zdPAbkn0B7eyG4aR6IzLOWUoyTXYHLsLfE=,iv:ZeJQ8Z5fJSF8Xro1VdWrJYLsv/s67Fjr7M6av6CfsVI=,tag:Jmjp2qDysCZ9icIOdiEcoQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.3
---
apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Yuk6xGfPt1OVYTc=,iv:gh9JqhPYyNK6hlgp2sSXma2ebsgwXGRc8e25KRlvrGI=,tag:MMo+NufGQnGhNy6SUjToiA==,type:str]
    password: ENC[AES256_GCM,data:LoSGksQf4so0m66/dlN0KNY4tNqc1cwPnL1eBjYea2w=,iv:ej2DhYI5ziBAB4wU1nKTqKxO6aVTLqGqPqGaDm6YFak=,tag:YpkeIH1+/LPFPvPuiM7hKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T19:53:37Z"
    mac: ENC[AES256_GCM,data:SA/5Yx0Y/ObsWQsgZfgQrmhP4GRZcxlnyAqwlElFIQllTxBjnddoyjDvFaAMCksCCPw2pTkwj3WiHzc9xb3FaJdc+Nv4n9yU1WtSQLdgHrAyw07hd2j1hxjiKshE8xbx7V94kvlc7zdPAbkn0B7eyG4aR6IzLOWUoyTXYHLsLfE=,iv:ZeJQ8Z5fJSF8Xro1VdWrJYLsv/s67Fjr7M6av6CfsVI=,tag:Jmjp2qDysCZ9icIOdiEcoQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.3
