apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager-system
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:GDb/I4Y2I5yyIMAyxGX5egO/a5RigZU5mTVvCXzUmfGIjTJwYtAWNQ==,iv:NCiMNR7ApipVKN1ErP8OJeLo7TEtNFJWv005KD922RY=,tag:01xUUv04+c0NIUNNgRlxVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZW1vUGNuSytNQUdqMmNp
            aXRmNXRJVXZkbkhKUEsvNjU2aUdkN2g2ZWpRCmVlMEpZRW91MnlJbnkxM0xBYml1
            VmdPanhKS0Y1cDk0cDc3MWdWTEl2cDgKLS0tIDVLbjBGMU01Z2dIR05uZVpaVVlG
            bUZZMEU1Sy80b3RrM0JCZEpwQ3hkV1UKzgriS8PKuNe8JVOVE/kJ0txaRO0/FaUb
            XT+fHsj05JEuIXw9axbxU1uY5I/Jp1bEWUxiZDr+kVqKe4IRcC1azQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T11:51:24Z"
    mac: ENC[AES256_GCM,data:IZqeSy0au7sI58DohmynJstiqUMyEGrG5IcyEJvt9TgVQ+L9WnWN+vcX5sXJFofaVTVA5uKiFrfQz8WTi7iKdIrpV7Zt6ImuLyGJjP3RsE0gw3yNcOoKX7ZDt2VvvMSYdS5L4aMlPImZEFod3gmnRUu5ps7fFYymbA83g9qAEcE=,iv:gPSLPrXYaxqq8X3/pTDluw2GZMiHy9TA+NMNSA8LAzY=,tag:5I+uYgMgFkdHp+WiBgaRnw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
