apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    FREENAS_USERNAME: ENC[AES256_GCM,data:QYKIBg==,iv:tVXYoIfzRg8dC1TUw0ziHaQl+htBVVaGv92FhJ7N3yY=,tag:luq7wpro00L4A4MPP3cZkg==,type:str]
    FREENAS_PASSWORD: ENC[AES256_GCM,data:Dmgyl3wjE4i5I3BPHbvQhFXvLw==,iv:Z3gh0ZDEV89N94LLsCZKb+YY5Js4Hk88NOPAxysOa7c=,tag:KVoGZ9Yv/ON3izlw1dE+Rg==,type:str]
    SERVICE_DOMAIN: ENC[AES256_GCM,data:2YhCGJ/2Uus6SAZv,iv:5/VdbcXvsNUCJFwUxLszz9YNBIkx2D7LGjVhVneY1oI=,tag:jDRnV8Ck/72QX3DecPqjFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T12:59:57Z"
    mac: ENC[AES256_GCM,data:M0W1USFesbb0uz7zoyHDFHR0KqBOWNZmZwrg42KBQTyM0rBvQVLas4VKddtnUqI+Xk2iApgMptK5TU1bfNMTk9BfN19ySU0bR3Y4YUDpG6z/ywic4P/yPZpObc65n4bT2dKWZbcUGb88I4C1T6eQh1cm5Cdx4p4X4t/cEVKJfx0=,iv:6rGYWlPhMLNaFnkH9C4WyXOMxk0c39k9cU8XC9ltkeQ=,tag:bS572Sn3lnilk0OTu9rE7A==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
