apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    SERVICE_DOMAIN: ENC[AES256_GCM,data:2YhCGJ/2Uus6SAZv,iv:5/VdbcXvsNUCJFwUxLszz9YNBIkx2D7LGjVhVneY1oI=,tag:jDRnV8Ck/72QX3DecPqjFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T11:51:34Z"
    mac: ENC[AES256_GCM,data:lSMcgXwTgEp5eU0j7tKjcYA6gqQwDBtHPUBNw2bjgf6BU9M0BijhxE1dHGs3GFx4Wtn8gt10SazaRBmHouE/h0jmUzoO2aAcZh+AJ34xBij5KA/Npkp7quHbcgzOD6ne2I0W3zLlwH4pgx/b5mWig9k04CFXsyFs87+rEP9nznE=,iv:Ztdb60PnggkJBAX8pXCcpyEkCBwL7J1YOW/YbMsWSyw=,tag:wrKQcq7Qem6N/udQY0Jk3A==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
