apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
stringData:
    FREENAS_USERNAME: ENC[AES256_GCM,data:QYKIBg==,iv:tVXYoIfzRg8dC1TUw0ziHaQl+htBVVaGv92FhJ7N3yY=,tag:luq7wpro00L4A4MPP3cZkg==,type:str]
    FREENAS_PASSWORD: ENC[AES256_GCM,data:Dmgyl3wjE4i5I3BPHbvQhFXvLw==,iv:Z3gh0ZDEV89N94LLsCZKb+YY5Js4Hk88NOPAxysOa7c=,tag:KVoGZ9Yv/ON3izlw1dE+Rg==,type:str]
    SERVICE_DOMAIN: ENC[AES256_GCM,data:2YhCGJ/2Uus6SAZv,iv:5/VdbcXvsNUCJFwUxLszz9YNBIkx2D7LGjVhVneY1oI=,tag:jDRnV8Ck/72QX3DecPqjFw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:chdlfv40KNpTCoqztoux3ZI=,iv:KlW3KzscHSLLJLMFF3SvZqx+XPC9caHRkdJV1E+L39I=,tag:yHtT/ckw2TTnHAAn6DxdwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T14:35:35Z"
    mac: ENC[AES256_GCM,data:9mEy5nDQRFii07WOGanF+Yvjv4lm1Nwnw2z57nWXpdaqwMBkAl0mOpg/q6zEqiDsXF0V4L8EzRoNCNmQe05W0SyFQ4WiUMo+EIBuc1f7UTtRq+QgBpUKrMP+BK1OVWvEr20y4LAC7+t/We1udkcC+aw4fMTf0O6BJYWj4hsPrDA=,iv:EVQ5D854WZ+dnxpLTl4coSgVsMtQ8rd90Nwvip4sk8U=,tag:+R36v0fwRxJ6R2QIVVhwow==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
