apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: external-dns-system
type: Opaque
stringData:
    opnsense-key: ENC[AES256_GCM,data:TS5G3GEtC9cph3j23mBfPMMWwuVF80d+u2u5zzstr9SYatFlcWD2t0gjuA8+zchSG8MlJF3M0Y3HWY0eQkQQxz3zh1maH4To/0Hfw6fXgCg=,iv:Su2dwWJtmoWa6RCWgLCKFITYb1pbV6QWJlD3l2n4PAU=,tag:d8icC0yiTGGjSFhy+0CDig==,type:str]
    opnsense-secret: ENC[AES256_GCM,data:MVJfyvbtm6bNGctT/+1EgrxBHHR8s2R7FVAdmxFTJjMJXevPKQruoR54bxxI54VG7y+ztPe7Y9WGlscBlTXbsh6nFpOoNTo830DHSqyxY+M=,iv:B4uLfcWEOfY2EuC17EanE2RKs1YHctnXY6rHn4Vhlg8=,tag:rFCjsirr9GrHxKF2FhCZFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T13:09:58Z"
    mac: ENC[AES256_GCM,data:rHYTE7gv3zYKT2uXgiocXq31tOIn7TD4WQCUyKUD+o05BXJGoYc3Vhbr7SiqXa5wMHyhKLLsX+m/euvGLE8EaSeq6yIvlpLlZkt8O5k52RM0QkGqafnH2nP4YobLAjPoIH47p4YcUgHkDZ+pqfw95IlXaVt26eF37uKrJ/Qgcco=,iv:mqkMGcW+XkNAnGun8GHhN3Idw7fDZi+nic47x9yiQtg=,tag:TdYip9RAdjYsFOkaMgn5qg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
