apiVersion: v1
kind: Secret
metadata:
    name: firefly-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Kb3N4kUUQg==,iv:byvO6yDxMfjHUXx1UHRnRBYJ8yQDd+6Bb4u6PC8JisE=,tag:F7G3rw0dxvAar0e7xmyxcQ==,type:str]
    password: ENC[AES256_GCM,data:Y/akNG7b4DIPbXWwBoe0xtSQYQoC5Nl/KOSXZBmHk8Q=,iv:ktMKJyhaIl3gjoKggAgbbVn6oVBr0RCRNhXGUp4WyrM=,tag:7YeYdzY6wDMtRhLS1g7Aag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T17:31:37Z"
    mac: ENC[AES256_GCM,data:7iVNJb/BkWCfpA5rq/+7HEWG4XloIOB/CytXsWDdbFaaQripDXzpl5QYyaSAc2n9VT+eIRJOqNz7fbRiw97sTsLvg2Wtw0VeNQAG+S7KQBIRJCBJSFRNF9QwxFTlavEROItja465LHR2UZzswQnIC7l3c3pF5f1nU1kWRGAf6s8=,iv:YeYvGOeoSKh6xWvdrt6XB9rXJY0BKsGsAEt8WoAnfwI=,tag:Gc04btMT+36gy7PS74l7hg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-config
    namespace: default
type: Opaque
stringData:
    DB_CONNECTION: ENC[AES256_GCM,data:6LBFbqI=,iv:wqRGHa5y3JjAcCGaBk8AulIiF4TM8kFhc+x07aYhMHM=,tag:6MnGu6Z/GRpgLv66/lXqZg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:92BelodPZoN85HBagK9i9lEFDI3B,iv:AYjYidFgEkzFG5UtSTXN1upJB3MSwymeCSLGM9s1nJQ=,tag:81bB5MOzonJNF5heCUGSuA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:+9Jrog==,iv:nEytCwgp9XImqVcQtHMtJ230emOEyp05Ht3tfQX2t30=,tag:CLyiX2wNiHW7ODTUapt6Tg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:MyLQcmWaKw==,iv:sx+L/ftuFts4JRJHypsKiVsKGoUSwSjetHtYho9ImtA=,tag:wwFmtfXQBy7NE4C5xu9nIA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:n5G27W9U0tLol9LzPvma9AeJ7iv383OhOYzl0TEnBNs=,iv:25F59sga9L14pdOVFjE4LEn5ChJmMKQmiJSZ2zVp3HU=,tag:fnC9r9pdQo2VpkKCBnFo+g==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:pLHXeiYylA==,iv:HcHVqxJuBbtWCbt3Z4JU3WqtqanAYKcJ44KQ/PJwdvg=,tag:/cNnTJ617rdRhoB1fKCwNg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:R0ZHnw+ftInxi/tjsmLbfW7ldelBH7nCBR9JQOn1LPw=,iv:9nhSOsvDh6uRPbz3wv4kS0T7nZhGEHgRZ+W8P99s12c=,tag:QQP7t9qNRhhxckKm0OS0rw==,type:str]
    APP_URL: ENC[AES256_GCM,data:8mQrXKWgLbeROL0FZI7DrvplexU23FrcQPR65g==,iv:fPWnMQROT3fX6CH6/Q5qQT8H5NewhtX4RjVhpicQYMc=,tag:1xr1Gb5G5jfbCtNyKb/EkQ==,type:str]
    DEFAULT_LANGUAGE: ENC[AES256_GCM,data:lmb4J+E=,iv:AJuIv52rIT+arnL4LaoT8njadMGUj56HU2FTPMb9WNk=,tag:ytKoC4dqXPqZdPEbKRV9Vw==,type:str]
    DEFAULT_LOCALE: ENC[AES256_GCM,data:NahII4A=,iv:wuKEOVIlJBnqy7HTmMhGBAZLjlcRElBRT1BhC4atji0=,tag:0ofSEAuAGf2/Fnb9+QMofA==,type:str]
    TZ: ENC[AES256_GCM,data:n0dV76ZeUQEIkzCpjA==,iv:uSRfpMTdZfny5ePQsygGzT2cV8VzWa5pppLwYSbY/zY=,tag:xDXupsQUsXKh/bdCbeq3Lw==,type:str]
    TRUSTED_PROXIES: ENC[AES256_GCM,data:BOI=,iv:1qkapz+K+KgMFhNe8/BWmNVjeJ7lCdniG3B7WfVWV20=,tag:6mKgwS4nkQQWqtLCfM2Pew==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:6FiNqg==,iv:k2022zYry4HIGKVLhQ/1016yJ3C/amx89VW/61J36qs=,tag:nkP5Zcd3M+S61ki82Y1M6Q==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:6OmVX/M0SA/bj72y3I2TWro=,iv:NnqXmLwvENoq8Kxo6SJFMQxs2Im+gJDBOSTwc+mRFAo=,tag:RS1UMMef+z1pNrkhF/xasQ==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:Irk=,iv:aN1UnJj4PT345RkvPdGisYEdaDbI7hCIzsz/Ok8szMg=,tag:rPC9Nf4qjWdQ18rrSuwd7g==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:gwK8ma4IXBwNV0gzdlVxUoum4QY=,iv:Xx7NXux9hOg6fz4UwEjm1KeFvP5ipA2Wlg5UxgllH8o=,tag:PBSkHdhYdum7p8b1f37teg==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:xbdq4f90,iv:RxQSU3UwykvRb9Y3s+CF6hPaGwiG/ZPmXixhmWGFztQ=,tag:7z5Fh8G/mQ5B004onJF1dA==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:8BxP8XXWWb5DH4CAe2rfKLCxWx0l8Wc6rGnIprOuYkQXDtE4x7v9KNNpmmIG8OxVt11kiTwO+k8BVDKG79HLiRdp4O0a,iv:8qdNNziUHQZB7+OkQaRoPLy8+FYJurM4e733UYwvZPw=,tag:r1A1pynLSEsDkX0UmiakDA==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:9wEU,iv:Es/5EmryYamebH2CpiJLbhN5aBjeXHHgKX+QlGCFacU=,tag:RAzmWJAInaAguFTTY7d0LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T17:31:37Z"
    mac: ENC[AES256_GCM,data:7iVNJb/BkWCfpA5rq/+7HEWG4XloIOB/CytXsWDdbFaaQripDXzpl5QYyaSAc2n9VT+eIRJOqNz7fbRiw97sTsLvg2Wtw0VeNQAG+S7KQBIRJCBJSFRNF9QwxFTlavEROItja465LHR2UZzswQnIC7l3c3pF5f1nU1kWRGAf6s8=,iv:YeYvGOeoSKh6xWvdrt6XB9rXJY0BKsGsAEt8WoAnfwI=,tag:Gc04btMT+36gy7PS74l7hg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-cron
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:5N7o+BJXGIWJHuMZsY1Fhn15s35AWD7tBI3whORIu+E=,iv:ZCW1cbnVOEsNGKXXRojYmyqLMEltICvLixrhixaR4uM=,tag:INbfC6bSQvN59sJGtB/ZWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T17:31:37Z"
    mac: ENC[AES256_GCM,data:7iVNJb/BkWCfpA5rq/+7HEWG4XloIOB/CytXsWDdbFaaQripDXzpl5QYyaSAc2n9VT+eIRJOqNz7fbRiw97sTsLvg2Wtw0VeNQAG+S7KQBIRJCBJSFRNF9QwxFTlavEROItja465LHR2UZzswQnIC7l3c3pF5f1nU1kWRGAf6s8=,iv:YeYvGOeoSKh6xWvdrt6XB9rXJY0BKsGsAEt8WoAnfwI=,tag:Gc04btMT+36gy7PS74l7hg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
