apiVersion: v1
kind: Secret
metadata:
    name: firefly-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Kb3N4kUUQg==,iv:byvO6yDxMfjHUXx1UHRnRBYJ8yQDd+6Bb4u6PC8JisE=,tag:F7G3rw0dxvAar0e7xmyxcQ==,type:str]
    password: ENC[AES256_GCM,data:Y/akNG7b4DIPbXWwBoe0xtSQYQoC5Nl/KOSXZBmHk8Q=,iv:ktMKJyhaIl3gjoKggAgbbVn6oVBr0RCRNhXGUp4WyrM=,tag:7YeYdzY6wDMtRhLS1g7Aag==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T05:44:08Z"
    mac: ENC[AES256_GCM,data:0bYA4lkGWTUwh27POvdKGFdgbyimkLA8MwVSSl8MiwVX8y3bUPWPQT+B0/byBQuF6kp+cL66KjZaIUKN1KVr7pRJkycejQUUJXV2LAcmy8jhAMLOhYgDIFG9y5hsKgG9C3s+RnYqyHsF32CsIDwlFtAid4IbWtYp3K/7T8z/VVo=,iv:6jZpDmSPVdjTCEFRBzXpnwV3Ajwyna530UP4SYMYqM8=,tag:g5G2eysPWlbpJsN6CAgpUA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-config
    namespace: default
type: Opaque
stringData:
    DB_CONNECTION: ENC[AES256_GCM,data:6LBFbqI=,iv:wqRGHa5y3JjAcCGaBk8AulIiF4TM8kFhc+x07aYhMHM=,tag:6MnGu6Z/GRpgLv66/lXqZg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:92BelodPZoN85HBagK9i9lEFDI3B,iv:AYjYidFgEkzFG5UtSTXN1upJB3MSwymeCSLGM9s1nJQ=,tag:81bB5MOzonJNF5heCUGSuA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:+9Jrog==,iv:nEytCwgp9XImqVcQtHMtJ230emOEyp05Ht3tfQX2t30=,tag:CLyiX2wNiHW7ODTUapt6Tg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:MyLQcmWaKw==,iv:sx+L/ftuFts4JRJHypsKiVsKGoUSwSjetHtYho9ImtA=,tag:wwFmtfXQBy7NE4C5xu9nIA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:n5G27W9U0tLol9LzPvma9AeJ7iv383OhOYzl0TEnBNs=,iv:25F59sga9L14pdOVFjE4LEn5ChJmMKQmiJSZ2zVp3HU=,tag:fnC9r9pdQo2VpkKCBnFo+g==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:pLHXeiYylA==,iv:HcHVqxJuBbtWCbt3Z4JU3WqtqanAYKcJ44KQ/PJwdvg=,tag:/cNnTJ617rdRhoB1fKCwNg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:R0ZHnw+ftInxi/tjsmLbfW7ldelBH7nCBR9JQOn1LPw=,iv:9nhSOsvDh6uRPbz3wv4kS0T7nZhGEHgRZ+W8P99s12c=,tag:QQP7t9qNRhhxckKm0OS0rw==,type:str]
    APP_URL: ENC[AES256_GCM,data:8mQrXKWgLbeROL0FZI7DrvplexU23FrcQPR65g==,iv:fPWnMQROT3fX6CH6/Q5qQT8H5NewhtX4RjVhpicQYMc=,tag:1xr1Gb5G5jfbCtNyKb/EkQ==,type:str]
    DEFAULT_LANGUAGE: ENC[AES256_GCM,data:lmb4J+E=,iv:AJuIv52rIT+arnL4LaoT8njadMGUj56HU2FTPMb9WNk=,tag:ytKoC4dqXPqZdPEbKRV9Vw==,type:str]
    DEFAULT_LOCALE: ENC[AES256_GCM,data:NahII4A=,iv:wuKEOVIlJBnqy7HTmMhGBAZLjlcRElBRT1BhC4atji0=,tag:0ofSEAuAGf2/Fnb9+QMofA==,type:str]
    TZ: ENC[AES256_GCM,data:n0dV76ZeUQEIkzCpjA==,iv:uSRfpMTdZfny5ePQsygGzT2cV8VzWa5pppLwYSbY/zY=,tag:xDXupsQUsXKh/bdCbeq3Lw==,type:str]
    TRUSTED_PROXIES: ENC[AES256_GCM,data:BOI=,iv:1qkapz+K+KgMFhNe8/BWmNVjeJ7lCdniG3B7WfVWV20=,tag:6mKgwS4nkQQWqtLCfM2Pew==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:6FiNqg==,iv:k2022zYry4HIGKVLhQ/1016yJ3C/amx89VW/61J36qs=,tag:nkP5Zcd3M+S61ki82Y1M6Q==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:6OmVX/M0SA/bj72y3I2TWro=,iv:NnqXmLwvENoq8Kxo6SJFMQxs2Im+gJDBOSTwc+mRFAo=,tag:RS1UMMef+z1pNrkhF/xasQ==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:Irk=,iv:aN1UnJj4PT345RkvPdGisYEdaDbI7hCIzsz/Ok8szMg=,tag:rPC9Nf4qjWdQ18rrSuwd7g==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:gwK8ma4IXBwNV0gzdlVxUoum4QY=,iv:Xx7NXux9hOg6fz4UwEjm1KeFvP5ipA2Wlg5UxgllH8o=,tag:PBSkHdhYdum7p8b1f37teg==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:xbdq4f90,iv:RxQSU3UwykvRb9Y3s+CF6hPaGwiG/ZPmXixhmWGFztQ=,tag:7z5Fh8G/mQ5B004onJF1dA==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:8BxP8XXWWb5DH4CAe2rfKLCxWx0l8Wc6rGnIprOuYkQXDtE4x7v9KNNpmmIG8OxVt11kiTwO+k8BVDKG79HLiRdp4O0a,iv:8qdNNziUHQZB7+OkQaRoPLy8+FYJurM4e733UYwvZPw=,tag:r1A1pynLSEsDkX0UmiakDA==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:9wEU,iv:Es/5EmryYamebH2CpiJLbhN5aBjeXHHgKX+QlGCFacU=,tag:RAzmWJAInaAguFTTY7d0LQ==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T05:44:08Z"
    mac: ENC[AES256_GCM,data:0bYA4lkGWTUwh27POvdKGFdgbyimkLA8MwVSSl8MiwVX8y3bUPWPQT+B0/byBQuF6kp+cL66KjZaIUKN1KVr7pRJkycejQUUJXV2LAcmy8jhAMLOhYgDIFG9y5hsKgG9C3s+RnYqyHsF32CsIDwlFtAid4IbWtYp3K/7T8z/VVo=,iv:6jZpDmSPVdjTCEFRBzXpnwV3Ajwyna530UP4SYMYqM8=,tag:g5G2eysPWlbpJsN6CAgpUA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-cron
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:5Sfpt9pwAziA5zJBl1MUzYb5ffQ7oxQK0zux8pQyy68=,iv:sZ4LyXi6LidSy2HmfpdKtsEAHH97ACOVmWIAieUwR5M=,tag:lMoybIXgrsWYj5cg/hZp5A==,type:str]
    healthcheckUrl: ENC[AES256_GCM,data:uMZs+6Kx1mSi3heDY6K6u/lV6nNx1iUL+HQD8Zd2jmliXcjEf4zIO8La5mO3mObUJQfTdIE5Zju/uh1RkyxHI1xQsPdOQEcOxAZNfpcM0W0rluskHXoaZbPJVFavGQ==,iv:UUXsTlecmq+S9gD1KFJTlYKklA64CbkHNbwF2GXnKqE=,tag:JdkGzC+NwUO2PHVemNIIuw==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:/7ZM8SibyaBeVEWstliVNTyEFhOeMDVZ6ey3Pw7J/LC0WlLRmDPqTyGDBUBA9EeZykd7YsfaGLUdtI8w2yC1nw==,iv:biUI0U9zC1FS+GBUWO26j/mmGy6EGdv8AgGCyDz93qE=,tag:I0j6Yhr2KLPAnDqazVU6QA==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T05:44:08Z"
    mac: ENC[AES256_GCM,data:0bYA4lkGWTUwh27POvdKGFdgbyimkLA8MwVSSl8MiwVX8y3bUPWPQT+B0/byBQuF6kp+cL66KjZaIUKN1KVr7pRJkycejQUUJXV2LAcmy8jhAMLOhYgDIFG9y5hsKgG9C3s+RnYqyHsF32CsIDwlFtAid4IbWtYp3K/7T8z/VVo=,iv:6jZpDmSPVdjTCEFRBzXpnwV3Ajwyna530UP4SYMYqM8=,tag:g5G2eysPWlbpJsN6CAgpUA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-importer
    namespace: default
type: Opaque
stringData:
    accessToken: ENC[AES256_GCM,data:rNNQZ9WL1+ifNfHD4nxAIb3TMqeZeVUeK0Eeh+JC7usY9Kt0cRgjSuhsaLlnCHIYqiZ3JRL77QabHu5blPKXlG87v4VeNwSLVSnHn3DaxeEByssnzfgwMKfwG9IlxsRI+4RMRXzpPCv3c5FUO5BlYJy3g4CGWgKSzts0Di3SrwyUYFy+w++ZYPkWrDIo/X7XLCONBTy3PtpRyumJHOtPLF1CLqnxsJBRROuTWYw11IjDauiFK9FaKeZ8zZaFkI6bwO3DtOLwX0bMbQMxYdED59X0A4UugO7w1LOIsZ4cSXc8hzQJ5/Ve/H4yr78wYhMgXAsX91sHabYbMgSd3NZ3NSCelkjj61KmprcsGbFAaYFW9UMRjVuPHPdf4IiwLHMc26IJdfouzAQPd2PPJrvLbU+NbeuitA95W0sohKLzYKp7HsZpXgLudJcyvYSUnoQFixKzPBD8w8kC7gaxAK8L6xbx8WOwWjs3y8nSEIck4aQwXNbM5OaAKtzAfsNiX+xqwJhgitau/MY2b+YT2RBKr3NVIeubrUb2UdqJWvVVvmtsmVi7Cx9uZCbEVaMGj5d3B9gkmClS0to5Uu5N2X66FfER5u32W/RkhRKjTyUGb0v4he5SD1d3iPJfETHyrB6woxy9Zhjq9WEmpY3mp+bQxYgfyvGFbtl/X5BoE/Pe1s6PezU5WtsSmk2/V6v0RJGf7ESL2zPW9e8ThAfocxEAAUCg0pctgvyimKH29xrXXEziSZsFrqDNSxUt1FlBFJ/X/48VDQeF4Oas5DpXdwyqBJAz66w9/qloAylphsEOAPlLgyre/1hgTTa30+GqwaGmpFDrKZjafW5YVVivTnyD6D/XasgDQx4OxaUOT+1J7/iCilIQdEv/zqt2oKO6ejcsEDX0lHR2Q10xUmaHDMWkftQe79D0AEfTOhPtEi74tg3Vz3D265y73pnz5naAjn/WrsBFldoHfZ3BH1W4D9YTiMeHvCfgXsZerZ3zCIjkFc7eH+IV+jT0alsnf9RGWjVV/pe6bkH905pF68uzB77Nc7wAcnUdLFaFjS3Go+3aMp5tGjvn8THBwKDLrxqYvZnfQ4Hw/Isq3sBDE9lFTlrlVOjxbld3PXmPzprTW5IT9h9qOiPOv6EzAoNepDO4fa6rog1rgb22wmCKyR2uILZ1ksSzyboeWV6pwHtKmDRLHkNjYhiK0OvV1OsTfmmr8qJPsdy9vucMoM4yeUXvvmf1EPXqsrCucaVpOtFRhkqBw5CPuiy7WikNTs6QXTjhUi/+fvNxe+UlCrfkB9d42r7RPg2kCY1hKHAb,iv:afWu86capiyzRTAe8WpwP/y1CHb23AIhqwMr97VgzSM=,tag:6mKn/tmjtlP43+8NM4uOyA==,type:str]
    SPECTRE_APP_ID: ENC[AES256_GCM,data:A63wRmFpW0baGBvAwRI9kNFGIFIPCcCr89N1ffHb7/HV0nwXHfudRkhVcg==,iv:a7CO6rDLTFJT5KjhwIT/qfTwbTosD+9geMVcSxGg+hw=,tag:UKZxWNAcQDiwLnLF0Nvcfw==,type:str]
    SPECTRE_SECRET: ENC[AES256_GCM,data:rgyCe3KDoK3B70WHMuoTdgtEdW3fCddd/VxQf56wCYlTFE1s4hfo36z1NA==,iv:hLhVp2GJcgxYBxhJGvH+fSBVKISDvWJRmT5PJwEEuls=,tag:OECofiCisud0EP/TR/LfCw==,type:str]
    NORDIGEN_ID: ENC[AES256_GCM,data:OigjV4mf4N2QjAG7xfD8/cUlKt01w7ns/2eu3PWY+8XGqZYg,iv:tQ3XtpQ25i94cny8IlRIdf38+/f59eFUvXjButa3sJ0=,tag:ggiQVVQDdcgk5caVKDP+/w==,type:str]
    NORDIGEN_KEY: ENC[AES256_GCM,data:xMrF08tQFIhXZxaoTXxo9rS/ZhIgBQDqQTl12mk5qLi0tNrwhCXmQgtQYNaXHyy07Aw7cATbV4QRIZzWJqrWsC7HiVWIdecmZlrhtZZWPRiQVQL2jic8U3oBFcqyMG/GmXZhNNdhcIi54kc2779EAAa/BpM0RXRW6GgMBzYGJTQ=,iv:nmbgPcBq3FnzULNNj2dvjlPCaxUP98fYEhU2eUwpj8k=,tag:QiYdj+/Bp1Dh0y5h9sCllA==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T05:44:08Z"
    mac: ENC[AES256_GCM,data:0bYA4lkGWTUwh27POvdKGFdgbyimkLA8MwVSSl8MiwVX8y3bUPWPQT+B0/byBQuF6kp+cL66KjZaIUKN1KVr7pRJkycejQUUJXV2LAcmy8jhAMLOhYgDIFG9y5hsKgG9C3s+RnYqyHsF32CsIDwlFtAid4IbWtYp3K/7T8z/VVo=,iv:6jZpDmSPVdjTCEFRBzXpnwV3Ajwyna530UP4SYMYqM8=,tag:g5G2eysPWlbpJsN6CAgpUA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
