apiVersion: v1
kind: Secret
metadata:
    name: fresh-rss-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:rPBXIPh3pTU=,iv:ifWyc+2NPMt90/bvWWXTAgoz0/m6olh840CVzjdm6yk=,tag:wEDmdVeEJqlelHWu7O2wtA==,type:str]
    password: ENC[AES256_GCM,data:/sxDaR1fsMM3MuQ6zJJZHNxIESUf07vjMXFyUizV7cY=,iv:ZffBQz/4dNi7+au19TADo5i0bbGiFoKQmf+OIiO6b8g=,tag:PKvKfynLWsHkHm4pu9i3hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T09:15:44Z"
    mac: ENC[AES256_GCM,data:8kzEseQHAafDFLvDquOGIm7SZgaGadX4OiW1hBa9IpXMpzGyDss8fERaBRi5XnEKLdsmPfvA7Ybm/2Ju9ZXcDln1ik9uwwq9TbnqclAEFwZ5PSwulTjHjlsn5wEMqvRiZU/rYl0z/iNkFcnAnGeVu8AeW2wzkRV2CcgWo/TOKcE=,iv:lEeOBxehiMfGmsfzrJGmtgy3geCXUfILRt6z+/FPzH0=,tag:hwHOeDbsWNZDraJ7zdvjhQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: fresh-rss-config
    namespace: default
type: Opaque
stringData:
    freshrss-install: ENC[AES256_GCM,data:/9iY5lK8yBcwnDI4dyDMj+tF8Xb+f/+CBhhMpyH12DnZ+xiOAWwM7M/WsW/qtF34yKZV30JM1/iaVaVGhfj7zGnECxD8D8N1n3xHXIEg/XdoAK2UJj8kOTvh/heaAUep5GEoH+9KyteiPuVPXDjlBPBy5RFKBCsvpe+COsrhHwSU6CvMbWul6PrP5N8eAV8x7xtBQFE74KtzbTqU/pe3V+AwG1Dg6W/SmqQfXKPw9CrP3o6bjSonU5k9HKRkxhi3gXZ1Rp6zMNRp2bSdUZMd6F1VLQkAONfyk12szzs1fg==,iv:sg0Y5nrS5SunwD12gInGRAnnrSZlLnjB4YFj+uoaY1I=,tag:+ZeQTpEraxNhG3tiaSTo1g==,type:str]
    freshrss-user: ENC[AES256_GCM,data:UkpH+ocYvzenmVbyjH7VBV3uwuFX+V5+mO3DhS/7fLWgcbWsfBX+C2DAK8CG1UXlMC35pCpbUgwE7tfM2/I6BlMec7XiT8SGQTN75GkXX7EQhkkM5g==,iv:uH5aK8pJg/wod5jUBEceEagknVxI0m1VeuGzmLCw6hc=,tag:w1rnZ9A6q+MHE/pf2aZFHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T09:15:44Z"
    mac: ENC[AES256_GCM,data:8kzEseQHAafDFLvDquOGIm7SZgaGadX4OiW1hBa9IpXMpzGyDss8fERaBRi5XnEKLdsmPfvA7Ybm/2Ju9ZXcDln1ik9uwwq9TbnqclAEFwZ5PSwulTjHjlsn5wEMqvRiZU/rYl0z/iNkFcnAnGeVu8AeW2wzkRV2CcgWo/TOKcE=,iv:lEeOBxehiMfGmsfzrJGmtgy3geCXUfILRt6z+/FPzH0=,tag:hwHOeDbsWNZDraJ7zdvjhQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
