apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secrets
    namespace: arrchive
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:lqGtOQ1N,iv:CS1Wo1LuSn0/sGh2ymYFRk02HC7i5lrHnbPF0IME7gs=,tag:DCiOSyYS4ndbEM7lTLBupA==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:S7IIJTCwo2uW,iv:4FNcwo35fW5OBp3mjJPGs4YIGrgy3SFsZFeD6nhGHUA=,tag:7vBBMKDnrPCtE/xL0olTCA==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:DyoOTfYcv7nognHkyA==,iv:I0JdfB4UxFaBi+DG+rTcrR59MMBAVsQxtTI97hSG0Qc=,tag:12kxKrtMtUpRBsexBBv3QA==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:z7yoNA==,iv:XI27vuysdsZV8EqHnn9soIvKyMFTLd6Ucx0Fit1mthg=,tag:Ym+N67+WWEIn5+A9Yqz3mA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:p7YGy2/pJjFQycW+5mMVIr4dDWZtXpkAKaZ3Q68QykLBxPtgAIK/K0SRi3I=,iv:4rhu/67646EFVZs6xb9w5XR75+8+Vx6NSZekKjc996o=,tag:EaKgIrMIIl4OOiEi9QOL8A==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:y5RUDgK8ZeKVRarv16jHKTC8L+D/VMfpn6BF8OsjI+XRNLX67zqCg7dRLm8=,iv:68oUgK/1Jb+oSHVniBNqPzbjfEo8gYkE240uuO5FCDU=,tag:NRYiq9UBt2Cy9hZXS6A2iw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Etu9IQUuzOed7oWghXOKtA==,iv:0htJPxoyT81DaAhIjWe+yLtly7Tw6tgnBLT+H117vmM=,tag:esZHefwMZV0spFmvfc8mDg==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:OqA=,iv:GjdQnrvzgwXLcDyQHqCDlrXqyXkEh/ojcbcUwk0n1us=,tag:uFkY1Ojw2JR0nSOUNZIjZg==,type:str]
    VPN_PORT_FORWARDING_PROVIDER: ENC[AES256_GCM,data:bzSiDuBvWY+AOCGWhQlJ+joxrM/7T2w=,iv:MIFXj4Q6FOKWgYguHdblyVvLj3GF09RiCFC6i763f8Y=,tag:ltWD3OMak6mhluTjWUndHw==,type:str]
    VPN_PORT_FORWARDING_USERNAME: ENC[AES256_GCM,data:MPe6m11TdXU=,iv:E1OktQ4ubGBMk2vVz0HfwmT3u0qpIqKXvIrcguClGZg=,tag:/X7hilcJrevxsV/epGGAUQ==,type:str]
    VPN_PORT_FORWARDING_PASSWORD: ENC[AES256_GCM,data:F/ykOnUjojfel2cCctEGlKTdYTJTEZ2cdErNNr8dE5s=,iv:azild966OjBQQQeyj6r0Y38qF/bD4vUjQtDZP/CAoVs=,tag:HEZ7qFgw3zCzKw8ej+sMOg==,type:str]
    SERVER_NAMES: ENC[AES256_GCM,data:+nvNWHXjSSMX5wn+,iv:p2s9oshoRH1LY6AqJUzytLPQHqgvYv/GWShAutAeyOo=,tag:eNjGdfwks0X+5f0BjeuFeA==,type:str]
    FIREWALL_INPUT_PORTS: ENC[AES256_GCM,data:1vQ79w==,iv:IFZKjG+TEeoA4F+CYY01FFKqr5VjjvhZyrurXy4MWGA=,tag:F6vLPRALPCJUYUc85IkJ2A==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:odx7KYqQMPro+LVNVVSd1evyCnCdt8vApi9l,iv:TFpsU7FNycIYaw92YcG2X7pkL9ioQjTIa1rfb4GccHs=,tag:f2mZseh1fGOyaelk7UlQxQ==,type:str]
    DOT: ENC[AES256_GCM,data:bCw6,iv:Reueqf39HovBqr2UNQCHE2o7vkq1exC7ya4Q74owXDU=,tag:9VOgoqzmI6qvi6P0SJ2JAg==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:XA2Kqt5t5Q==,iv:c+rLJLys6pm2K6OBM7NF3eokSVlJjzo8kYRj8ph8Bq4=,tag:FvToxbOiIOj2ddrW1OOEaA==,type:str]
    HEALTH_TARGET_ADDRESS: ENC[AES256_GCM,data:l2ZA7gyExpBg6RU=,iv:5zWEC4Up41Hl0PtomFrt6JO9yFEAxyzOjbWKpRO+1Y4=,tag:Cj+wnh6vInVvGHL/05xg4Q==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:3SoyGZ4=,iv:RYWu173CCnpqcPxbSmJRewLnGgkjHs5Fs1K1m06bDhY=,tag:Sx2sWhoR7bXq4V+74vW3VA==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:cGLWcU+G4g/SwCUspE2+/6uaKsxMdcsqNzDlbDa2nmg=,iv:JbTlSfsPfA7dF/tQE+rtA0Yq7yzui0/asKZ1z6FQiIU=,tag:pnzvP2cp7G9F/EQi6XyS6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-21T10:56:30Z"
    mac: ENC[AES256_GCM,data:nO1Hw7SKwV+7XIvIP/PjNFtOmFJ6oZsBge88xAXobxR1xvNx6bAg+SE0JVtd2x7mOHkIps/KjExqsc22i7YATsvwbzT6dqsSOLl5Q9kL/84WwpOIqyCt1Ps64NKFctlZpZ0I8vzvHDczjl0a9OwTb13nUMKorhhw3dGbiGHzpDI=,iv:89NCea5bpMFXeZOUF/zwUnOXr40+SGmX5RIZ7iAOaZA=,tag:YkzP0u06YGN8nX2G1hFCFg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
