apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring-system
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:SOkfTmk=,iv:g8REXO7j0m9BiYvhuCRhnjwc5OGvkcSVynzXzeLq7ws=,tag:RaWbn2qpovCXnMjvXg/hGA==,type:str]
    admin-password: ENC[AES256_GCM,data:/diz9/D7eA8JWPnKES0ZZohnqLzlIaHyVtNhG2ud8MM=,iv:wn1WA/UpqPIaKtrodOxD2Bl7914BucMFCknURdxXxLQ=,tag:WnfxPy+HLHA4VXtcsihKeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZU54VUxMdTZ3QmFUTFJz
            NTVObzgyUktEdWpYcnNRMjVjQmJPeFB2K1FJCmEva1lYcGV1NUpjMWNIVkJEeFVy
            Vk5uZGpzenJ3ZUJoQ2hFUkp1YUhUaHcKLS0tIEgxRjdob21zOHJkMkNEZWRqaWdT
            aFhuMVJuNGxPbCtFTXdUVlUwWmRPRnMKbfZiDAflOkdHhrRp2gomCyTqBT9tqOBn
            iOB1FFQ+ZGSBociQzdbkMnYNkJIUDP3ezi8cBC5nI8d5cw8cLDQ9vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T13:08:50Z"
    mac: ENC[AES256_GCM,data:8EJMAU3hKYf9IJZQhApKrlavm9Gdtd/SNXfkYlr0sNyHDxOvThY5m/gqTlQ7m27uZXe2uh6KBbsqhSEziwcAWZ7+CZmE59hBdzdJIqs1nzcGTTi/ESw2mftc5egRKrSAdk/d8gOX03NcpG3yVVKgJBPX6ABFD82i3OHE0CCogtU=,iv:lRLNkoCsPlnl2VJwvI6AlJeT4epvx+TvB6ZsbxCZL3c=,tag:rdk6pXC7dKlEA0itXOPWRA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
