apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring-system
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:SOkfTmk=,iv:g8REXO7j0m9BiYvhuCRhnjwc5OGvkcSVynzXzeLq7ws=,tag:RaWbn2qpovCXnMjvXg/hGA==,type:str]
    admin-password: ENC[AES256_GCM,data:/diz9/D7eA8JWPnKES0ZZohnqLzlIaHyVtNhG2ud8MM=,iv:wn1WA/UpqPIaKtrodOxD2Bl7914BucMFCknURdxXxLQ=,tag:WnfxPy+HLHA4VXtcsihKeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZU54VUxMdTZ3QmFUTFJz
            NTVObzgyUktEdWpYcnNRMjVjQmJPeFB2K1FJCmEva1lYcGV1NUpjMWNIVkJEeFVy
            Vk5uZGpzenJ3ZUJoQ2hFUkp1YUhUaHcKLS0tIEgxRjdob21zOHJkMkNEZWRqaWdT
            aFhuMVJuNGxPbCtFTXdUVlUwWmRPRnMKbfZiDAflOkdHhrRp2gomCyTqBT9tqOBn
            iOB1FFQ+ZGSBociQzdbkMnYNkJIUDP3ezi8cBC5nI8d5cw8cLDQ9vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T09:58:02Z"
    mac: ENC[AES256_GCM,data:UkEUz24dRxT/GnftV7v+2AQRbMdtbG9xCv2u9+m39M+gqepw9nC1D0f8XNiW08EaaE+C12t0g5deY4TJMqo0rPIq9aLsE0+KPTTlnAzUOO4x8Arju4KzFCpsiMp68/0/CDWBPhxYVXeOuyGwPcq7k+OC1dB8JQ0si0fFIHYFPg0=,iv:Ne0vLGuGQHQzAnJh4LQE/IG7JMLtHP2PrNldwlbhxpg=,tag:4VGwDPaTGjE96TWwn2MPhA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-pushover-notifier
    namespace: monitoring-system
    labels:
        grafana_alert: "1"
type: Opaque
stringData:
    pushover.yaml: ENC[AES256_GCM,data:DKzvZaRnKUhLuygLj/Z6v9JRy9RINBtaBjKBOyRZyvFkutLDOnmy8kQg4vwoqqNGjz8ADD/xkquUvlJYBLw+CoDsIRC17wQlcvMzamJxv3/zVCu5TILnaW22wmcA68Xn/X9jaWXHi/eHyPtuSKnnqNbX2DG4jC4JE1eaxzu5DtMoPQO54j1/QCaoIswzrARdHB6DUNhWDkwAYec92pjCa72GZ+J3a17p/93c3EdxBZ0tY++YskA1F/uDY/LGAb1+iS6eegCrqxOKbkFe/5hAnvpJq1JP+GjOOgq4so5n3dKtjPgyCkCSb7ZhdoqwF7c=,iv:QqTacHuowPxc7D1JLV+QcQlWz9qRBkoqPL0XYu6ALWI=,tag:Zd+dNpCg8GQswRGvF+Tfdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZU54VUxMdTZ3QmFUTFJz
            NTVObzgyUktEdWpYcnNRMjVjQmJPeFB2K1FJCmEva1lYcGV1NUpjMWNIVkJEeFVy
            Vk5uZGpzenJ3ZUJoQ2hFUkp1YUhUaHcKLS0tIEgxRjdob21zOHJkMkNEZWRqaWdT
            aFhuMVJuNGxPbCtFTXdUVlUwWmRPRnMKbfZiDAflOkdHhrRp2gomCyTqBT9tqOBn
            iOB1FFQ+ZGSBociQzdbkMnYNkJIUDP3ezi8cBC5nI8d5cw8cLDQ9vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T09:58:02Z"
    mac: ENC[AES256_GCM,data:UkEUz24dRxT/GnftV7v+2AQRbMdtbG9xCv2u9+m39M+gqepw9nC1D0f8XNiW08EaaE+C12t0g5deY4TJMqo0rPIq9aLsE0+KPTTlnAzUOO4x8Arju4KzFCpsiMp68/0/CDWBPhxYVXeOuyGwPcq7k+OC1dB8JQ0si0fFIHYFPg0=,iv:Ne0vLGuGQHQzAnJh4LQE/IG7JMLtHP2PrNldwlbhxpg=,tag:4VGwDPaTGjE96TWwn2MPhA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
