apiVersion: v1
kind: Secret
metadata:
    name: k8up-secrets
    namespace: k8up-system
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:wmPHtNL/yDxpQ0wahB2gF/BbX5F0VOxoWA==,iv:QE01elCOsnlc75URyJ5EKF3ZiUXW3BTQkCr8RljSX60=,tag:9Jy76jyPfLui66rsUEkgFQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:um44c3aE1vzeETpXE74/DMxnLhICCqTdBHCrRUIzSw==,iv:DAKYgDKRcksRKuEP7OfpYJIh6RDGdUjS8y7RuvY3frg=,tag:EYLeJkxgh9nrutKOvQMnkQ==,type:str]
    s3-endpoint: ENC[AES256_GCM,data:kuIeKKGJ2V53UR80Lku80NAp1LqN6Osm33K/w1tR,iv:SUCNY3n8Ntr8XztC6HlZqbvyonq3N2jArUtelCEKztc=,tag:nfoYLaCQq1d04hIKJVa0Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweWkyelowOEJsNFo1SjNx
            SmozdUY4VlVsVHFIZmxSdENGZG1VYW54VHp3Cnh2YS92c09SbnhQbXU5ODNMUWlQ
            UDFPaTZRaXViVm4xTDVhUjNYbmFHM2cKLS0tIEI5NVc1d3NnbG9GTnA3TmRrK0R2
            d1JtcXVxbGpXYldXQmlTazQrMFRQaVUKiYmXESiQF6rA+J+zC9ReGVFeiRBvvtGe
            WgAmZznt5qaeXiOfh38iVqt6bY4q/1pPSaPHXJxd6jXIX+SsbX0MlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T14:32:11Z"
    mac: ENC[AES256_GCM,data:4qPMezlLWnYPsNVmMSpkPEImRpj9ob0dMJWiCM6bisy9i0LaIfMueBeID/u0/Uff9Yfcag6ZUGBYQCex9ztBCv/GvXAlIko89wYsELDgECLqyB5PGnovQk4X5NIb/LZKe24vTm02+ymcVvYPapOCK0JWJbsAMDIBxMQp0JpBA/o=,iv:8gCrdSmwPk4eriyspfaFb0takLPz1Fa0SMY7hz9p4fk=,tag:/Gbjzqjw+0m+YMyy94XciA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.3
---
apiVersion: v1
kind: Secret
metadata:
    name: k8up-restic-secrets
    namespace: default
type: Opaque
stringData:
    restic-password: ENC[AES256_GCM,data:BbyfUgS+rAVhwG3jxCXsZHLIithjlvU1C6TK2l3jrck=,iv:jloTs0DVljR6BW4RWZiRr2q8DT/cpcC0zizLvTC3SbI=,tag:FQfW8wKpT+SNOFrCbHQ7VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweWkyelowOEJsNFo1SjNx
            SmozdUY4VlVsVHFIZmxSdENGZG1VYW54VHp3Cnh2YS92c09SbnhQbXU5ODNMUWlQ
            UDFPaTZRaXViVm4xTDVhUjNYbmFHM2cKLS0tIEI5NVc1d3NnbG9GTnA3TmRrK0R2
            d1JtcXVxbGpXYldXQmlTazQrMFRQaVUKiYmXESiQF6rA+J+zC9ReGVFeiRBvvtGe
            WgAmZznt5qaeXiOfh38iVqt6bY4q/1pPSaPHXJxd6jXIX+SsbX0MlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T14:32:11Z"
    mac: ENC[AES256_GCM,data:4qPMezlLWnYPsNVmMSpkPEImRpj9ob0dMJWiCM6bisy9i0LaIfMueBeID/u0/Uff9Yfcag6ZUGBYQCex9ztBCv/GvXAlIko89wYsELDgECLqyB5PGnovQk4X5NIb/LZKe24vTm02+ymcVvYPapOCK0JWJbsAMDIBxMQp0JpBA/o=,iv:8gCrdSmwPk4eriyspfaFb0takLPz1Fa0SMY7hz9p4fk=,tag:/Gbjzqjw+0m+YMyy94XciA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.3
