apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1I2H79qIptWpc2o=,iv:eD/TF+Djeu9bRpt9LBiHYlOIH+AZ1f8mJg2rB6NU20E=,tag:um/e9fquQmPSaFbv7xAQBQ==,type:str]
    password: ENC[AES256_GCM,data:wB1StdQGXALee/wc2zrN5PWJ+mBnpGH1HCNJWTO3lmQ=,iv:wYjoWR4E92vAeBAqF51+3pFH9eI6JlDbMA1Hz7aDwZI=,tag:NeSJmtVAgLgqTHy8wyPsjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNFNpNVZaNVNDNW0yMXFE
            K25JVWN2WG4ra1E4bEZMYUpkT2xON29mRVVFCmN0dFJWNjF3QUw1VGppcGFpTThh
            MVNndlliMzZvbjlrZXpCNnRjTFpZemsKLS0tIHZqeTZTVlRxYWFmdXRPQ09XZHlr
            SU5LeVJGWThoZ0RoWWdwdTVucmVJeUUKrFPaIDk8YuFBbJQGeUeeOhxb+nVGrcwJ
            5tQo2uN4mg3ha5aSTpvyWOoKnZ4kIvQE58OqUWp9IzAcKk1w8875tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T14:31:08Z"
    mac: ENC[AES256_GCM,data:HnWld/yWsQ67J5dhN7nDhUAvpgCXZhRYe+wqO6+27XyuVrbh7f+/LHU3U7uTUScrlCYdN15QN+hei9hMfdCxyiRG/wj0d0drpgTlJzBK5RgDPtrCCOyb58JA7Fk33bojNifo6j9HIA0ITvE2OFZhjKuBTEHaiEf2o//cSDSgvbg=,iv:ZkfFhMMuNAE4oZiZ99rpN8YEfYvyStvSQ5Fxwf8sUZA=,tag:+/OXjnlmLk/rLEPw52LGig==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: k8up-secrets
    namespace: k8up-system
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:+ySqrVndgk0yC3LxopTAeB/jM3AUiLcvww==,iv:Jyx18rtMqzgDRSjm1Vxqj5zXX0k9dPzsgSylggkXXz8=,tag:mYAxtqQNfXsrHd3tW3dqeA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:z0zdVthkEOuztL6oVFi0/Fn8fjbZJ5lUeG6JtKDhYA==,iv:Mh9xhKCllM/Y8waeMsG73wJLEeZnP+2kTlfgJ74jQsA=,tag:gNy0hOanavNUQR6ZfGNuVg==,type:str]
    s3-endpoint: ENC[AES256_GCM,data:+w0hjfA49k9HjIXyA6g33RyOCUDwZ/KHjfEonKCM,iv:o8fRbOk4za/JbSqHRO1PqZx9Ct/DxGWQx3O5oWrCG9E=,tag:yWG4X1V+5sbwPjG2VSR9xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNFNpNVZaNVNDNW0yMXFE
            K25JVWN2WG4ra1E4bEZMYUpkT2xON29mRVVFCmN0dFJWNjF3QUw1VGppcGFpTThh
            MVNndlliMzZvbjlrZXpCNnRjTFpZemsKLS0tIHZqeTZTVlRxYWFmdXRPQ09XZHlr
            SU5LeVJGWThoZ0RoWWdwdTVucmVJeUUKrFPaIDk8YuFBbJQGeUeeOhxb+nVGrcwJ
            5tQo2uN4mg3ha5aSTpvyWOoKnZ4kIvQE58OqUWp9IzAcKk1w8875tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T14:31:08Z"
    mac: ENC[AES256_GCM,data:HnWld/yWsQ67J5dhN7nDhUAvpgCXZhRYe+wqO6+27XyuVrbh7f+/LHU3U7uTUScrlCYdN15QN+hei9hMfdCxyiRG/wj0d0drpgTlJzBK5RgDPtrCCOyb58JA7Fk33bojNifo6j9HIA0ITvE2OFZhjKuBTEHaiEf2o//cSDSgvbg=,iv:ZkfFhMMuNAE4oZiZ99rpN8YEfYvyStvSQ5Fxwf8sUZA=,tag:+/OXjnlmLk/rLEPw52LGig==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: k8up-restic-secrets
    namespace: default
type: Opaque
stringData:
    restic-password: ENC[AES256_GCM,data:FqORaBVtlDWewj2B5w1tjruGtNcnmNgzUMcHa6/bE5g=,iv:BcyiABaD9uLPLVEcykWCfXizSwlj2f4U3WzqQonHL3c=,tag:MqopC5AptcQUemKl0vfhCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNFNpNVZaNVNDNW0yMXFE
            K25JVWN2WG4ra1E4bEZMYUpkT2xON29mRVVFCmN0dFJWNjF3QUw1VGppcGFpTThh
            MVNndlliMzZvbjlrZXpCNnRjTFpZemsKLS0tIHZqeTZTVlRxYWFmdXRPQ09XZHlr
            SU5LeVJGWThoZ0RoWWdwdTVucmVJeUUKrFPaIDk8YuFBbJQGeUeeOhxb+nVGrcwJ
            5tQo2uN4mg3ha5aSTpvyWOoKnZ4kIvQE58OqUWp9IzAcKk1w8875tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T14:31:08Z"
    mac: ENC[AES256_GCM,data:HnWld/yWsQ67J5dhN7nDhUAvpgCXZhRYe+wqO6+27XyuVrbh7f+/LHU3U7uTUScrlCYdN15QN+hei9hMfdCxyiRG/wj0d0drpgTlJzBK5RgDPtrCCOyb58JA7Fk33bojNifo6j9HIA0ITvE2OFZhjKuBTEHaiEf2o//cSDSgvbg=,iv:ZkfFhMMuNAE4oZiZ99rpN8YEfYvyStvSQ5Fxwf8sUZA=,tag:+/OXjnlmLk/rLEPw52LGig==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
