apiVersion: v1
kind: Secret
metadata:
    name: kitchenowl-secrets
    namespace: default
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:twIlgwm2zRM//7ze98mSuPFzj8TaWtRZhmT290bTflk=,iv:lwBRKchOkQgJezd8sAmzHvo+eQIWyYwYdcT1ktCHMy8=,tag:UEQb9V4+RH7lSUYHWJUBsw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:dtTnrB4z,iv:OxVPBGIMqxrUSVoY2S7504Ls7g2JHuK0I+Busq3bNmQ=,tag:bJhedgU57La9wbMnUAXkjA==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:2ulC2dhzs6uYHTmn8XwwmhJhnAiPh8fQRqXRP7z9VU4T16tPxEMJDmIBoE2mcbmtHPTtxHzVzYmis2SDo2cxNrvdk03u,iv:RWBEpgeuL/Tt1HQ0P3W0Fu7B1xH5MuPUWjyzskqULmY=,tag:o/Ac32m/d2imSDh7njNOOw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T05:05:38Z"
    mac: ENC[AES256_GCM,data:Q/4pM3vNrWN5uutnwTMaTeZ7I9zGGOlAslETnXxy6za5TB/WfJ1aOoUuJ09Wx/HhkiZvWBz7YdaZ9mj327fvZRdqRAzHfdHJ26gQORq0ARDdBiPIdkV+PuAfLhwGvRdMkwtHG5zFcUqhTL1/Y58TJZI3QtmmdfIWNFzYOp9xiTk=,iv:iwLgz7hoRXf18BRaANiDSkmd+thSQ92d4G3Wrun18DE=,tag:c30635kVx4TTHT+sGoj61g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.1
---
apiVersion: v1
kind: Secret
metadata:
    name: kitchenowl-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:S11VOOTSCI9YhQ==,iv:3+41M/bL7C90x0Th6xEBXT16DA56u5AcCbDQSTGIPEc=,tag:6KOLtqfb+Jpia+cZavC5Wg==,type:str]
    password: ENC[AES256_GCM,data:ks932bkNABKE/J3kLE0e/gCpFb2F0coN75NzItzl+sU=,iv:ZtD5C5HSGrBAz5fo4zKBko2LcXOYk0AAG70YfUFDB9E=,tag:dZ6GT6d34zh+tqcBqJL+3w==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T05:05:38Z"
    mac: ENC[AES256_GCM,data:Q/4pM3vNrWN5uutnwTMaTeZ7I9zGGOlAslETnXxy6za5TB/WfJ1aOoUuJ09Wx/HhkiZvWBz7YdaZ9mj327fvZRdqRAzHfdHJ26gQORq0ARDdBiPIdkV+PuAfLhwGvRdMkwtHG5zFcUqhTL1/Y58TJZI3QtmmdfIWNFzYOp9xiTk=,iv:iwLgz7hoRXf18BRaANiDSkmd+thSQ92d4G3Wrun18DE=,tag:c30635kVx4TTHT+sGoj61g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.1
