apiVersion: v1
kind: Secret
metadata:
    name: microsocks-secrets
    namespace: default
type: Opaque
stringData:
    SOCKS_USERNAME: ENC[AES256_GCM,data:SkGiwQAuEIB7Jw==,iv:KvwAkD4Ux/9IhlmM/QFPhsDPx/AtboHf3KjYyDqBPOo=,tag:VHdHnnauhswIFrhjTzgQKA==,type:str]
    SOCKS_PASSWORD: ENC[AES256_GCM,data:fPru7+HWKOMeJ7R/sZHBUgKa/IYrhb4S3Bqe3yOCiX4=,iv:Vu5xeyOIhRNPN0HObGOvW4TJ2rklfofjqFQxQgKXXUU=,tag:v51CSfjb6uf+o4kHk0572w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T13:19:24Z"
    mac: ENC[AES256_GCM,data:5seg9yW5E1OphgnauX/J4h9k4kEk5jJy9JysfyiYMXlFCAAcMzldT3gp2thQW5yWxq057Kmu2C2RSonCexBCXp9BZbsvcbzOKOCuEYvjkR+V+ITU+0vBXy2cm0xUUbRe3Su/j9VZQZ2YpaZbOikIg9fw0D8fgMVqVJjhiaEw6Q0=,iv:IiKyIKz8BIEhySLuYbYxD8CArGsiPK3wwUzharKjPo4=,tag:dKZUz1ERkLKOo4XlHM51yw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
