apiVersion: v1
kind: Secret
metadata:
    name: n8n-config
    namespace: default
type: Opaque
stringData:
    N8N_EMAIL_MODE: ENC[AES256_GCM,data:VK4EKA==,iv:ifBs65jpRtFlL2fwaXt2x5OjCgXWzNTpbIQKV0KI2Es=,tag:UldfoHzd7ZVWq0vSSVrvDg==,type:str]
    N8N_SMTP_HOST: ENC[AES256_GCM,data:j1XPEyotDiZMuhO5Rq+cOhY=,iv:XmfhEua0rz5sSV8vEi2ptnjPVOgu9EAIV1h7ocIb3PM=,tag:F3kFZSDN+TXHFDLNfw9ajg==,type:str]
    N8N_SMTP_PORT: ENC[AES256_GCM,data:U/qS,iv:MNLX5+kPGH0c9gzbEgQRh3OfqZ6Gsbi7YCn8DV6a2EE=,tag:rMB2TF/6YUkwCxrtWQABaQ==,type:str]
    N8N_SMTP_USER: ENC[AES256_GCM,data:lNRi90sC,iv:9WkXQqleCMHcLTor2BZ5eh/owrPVF1NlqqdrlFHalhM=,tag:MaAtX483k6XArqj8Z/X0yQ==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:vgudSmSEj5Y7qz/2uT1VOj/GAqPb8752e+U9NRCT+pePYCZqNqdXHqxaD2eza5Nwx+DAqdMlbeKNIqI6IOigfFe3497a,iv:yDGXXZDoZrP1jnPlD+vrFCE0C2GEaxDMhKADSiT6NNc=,tag:TB5+kLwVyq+qiKC6HCp2cw==,type:str]
    N8N_SMTP_SENDER: ENC[AES256_GCM,data:LphP8B42HsVi30bZBKKZug==,iv:FOlJQlvBbyTmFIwrHILFFeDtLzpcMiGIMe1RZTVI3qU=,tag:zbYbf8rWQTOynsX5+qQvsg==,type:str]
    N8N_SMTP_SSL: ENC[AES256_GCM,data:kNs6yA==,iv:P1SRDKuuZyCCtTm82aqv9LgZdmlwCfG3wSGChuCBDqY=,tag:9wf1HWz/iTx+cVeaesfwXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T11:58:09Z"
    mac: ENC[AES256_GCM,data:qhSp5c3LYq/cya4t5+I/YC3XN+185iMJ6JMzmSvwPj4eQj+KgPdrHlksN4122qN9m1npqmGh57uhChgBN2iXYqrNmgCmWeOyMIkWzTUbIkAaRLKE4vRoG3tAb/HY8B6tb4dFocr01B8sXqOiQFR4N+eqGhWuoAbn5DJkVtp6SFw=,iv:GG60cabjOaF97C8SabLZbgcjmD5K0Ki4oxHaZJZcdEQ=,tag:VStUGpRwFRnxP5A+s6P1pg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.3
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:dKR7,iv:Rp/o/Uouq4aCwE3mOmfTSZqiiWhpYT9by9VxuOv4JLM=,tag:0fOb5FX4ora0IgUzt3X3jA==,type:str]
    password: ENC[AES256_GCM,data:RWt0eceTG+DFyPpu9ICbJGhBrFCUEZ1rAOj9SnNWpiw=,iv:XON/XFqmofCBHYTXZdqEdGNrEDJj33nNsVdm6BUrBkA=,tag:I4jZszeb5DjkeCVdLbq3PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T11:58:09Z"
    mac: ENC[AES256_GCM,data:qhSp5c3LYq/cya4t5+I/YC3XN+185iMJ6JMzmSvwPj4eQj+KgPdrHlksN4122qN9m1npqmGh57uhChgBN2iXYqrNmgCmWeOyMIkWzTUbIkAaRLKE4vRoG3tAb/HY8B6tb4dFocr01B8sXqOiQFR4N+eqGhWuoAbn5DJkVtp6SFw=,iv:GG60cabjOaF97C8SabLZbgcjmD5K0Ki4oxHaZJZcdEQ=,tag:VStUGpRwFRnxP5A+s6P1pg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.3
