apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: default
type: Opaque
stringData:
    smtp-username: ENC[AES256_GCM,data:fZT80/Fa,iv:6pLx+n06Toma8jLSLK0gkuTndT5jcTREf0axrxCHxeI=,tag:/qviyLLuyp06N4suDy4XQA==,type:str]
    smtp-password: ENC[AES256_GCM,data:yqGt4Iqt4Hpgv6taCY2M/QgI0ic+kjio0ix21+DQOZKMfLf3NO9umk9E40CjXZZipjIn/1BHll6+OsO5zUJ19HvFf++h,iv:SHwu6QiYlA1qK1Ey4qS+sN6vQ093yqILUwouoD89Ris=,tag:U29llIoOdIgntwEhUb25Ww==,type:str]
    smtp-host: ENC[AES256_GCM,data:yHOm+HnoSBjKQ79U4CAe9MA=,iv:wNXpGmtQYJGEwpmX6HAAvCGEyP356JaSsD8hPRenH8E=,tag:6He7MxxRv6Oak3z1am2dGw==,type:str]
    redis-password: ENC[AES256_GCM,data:tIpJ/Y85Cb+R2ypNyp3+o90UDjSKMXmoBgHO0HxbqJw=,iv:8r633Qnx1DjShfsBb98mKe/0Q13v0oTwwhUbCWrR5Ug=,tag:IXHHxVCjlDPMkjrmVKOcfA==,type:str]
    nextcloud-username: ""
    nextcloud-password: ""
    metrics-token: ENC[AES256_GCM,data:TrEj6XRN909L1JJoIOxX328N9+YzdHmIILOZks5tZuOWADSiLYHhkEl4rAClwHROrajS5k8m6j6UE5K/e5CZZQ==,iv:yGrJ0vjxQDuxdijDtBv0+3EsdE+gdhY8dqTDQL1TTTU=,tag:MQE3kB6Nx4T0cZhYDzVSXQ==,type:str]
    healthcheckUrl: ENC[AES256_GCM,data:vhjcIerWaBZ1LA8pwlM9vMS/yYkKmhnu26nmI4M60g/VkW4bLXjCO/DiJMJWgoebnogR/e1YHbxhAU4fOZ/7YqgYzrqxcUQWc6+9,iv:DnQNfayI026nARpH3HDSln59vAwq3QIxKE3PRLPpGuw=,tag:K9K+MUgLgx8KEs415JC8bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T17:21:10Z"
    mac: ENC[AES256_GCM,data:cODy1UGjeK1wvdPQP6joQDf9E3p1aEc0/tUbrMdniw+CkCB3utCEqD5cddRY7ycG6Txpr9OJH59cFV6KVAJ5jAA7IOii2uZNy65RcuHYkd5TKXaefTjTD1+7k0MXJbKfko+p1eT8lPVvatsVMZosDDZm/qM0W+4jwAfpEY4rHRQ=,iv:T0jYFHbKhmSdnEpY1a1L7B/Hw7+GjlII33cGZLpQ1Ok=,tag:luUEpas35fz4kkOk5u+E5g==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:bYCCTh0B+UfN,iv:p2rrI3p2i78IhyUH7Kfh2IRtD9qdTkchXd0DJHzpilY=,tag:RsVYArRdZmIdwziJKzH6jQ==,type:str]
    password: ENC[AES256_GCM,data:+0YYi9fQRwri/XvLF167Gg7G8iirlvAnGoEJhMeyBRk=,iv:91NcT3cyPi4h3VhLeTgmGh/5zNJJ6O38NCjheoPQVNI=,tag:ufj5kitJRMw1aOqrMcXkng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T17:21:10Z"
    mac: ENC[AES256_GCM,data:cODy1UGjeK1wvdPQP6joQDf9E3p1aEc0/tUbrMdniw+CkCB3utCEqD5cddRY7ycG6Txpr9OJH59cFV6KVAJ5jAA7IOii2uZNy65RcuHYkd5TKXaefTjTD1+7k0MXJbKfko+p1eT8lPVvatsVMZosDDZm/qM0W+4jwAfpEY4rHRQ=,iv:T0jYFHbKhmSdnEpY1a1L7B/Hw7+GjlII33cGZLpQ1Ok=,tag:luUEpas35fz4kkOk5u+E5g==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
