apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: default
type: Opaque
stringData:
    smtp-username: ENC[AES256_GCM,data:fZT80/Fa,iv:6pLx+n06Toma8jLSLK0gkuTndT5jcTREf0axrxCHxeI=,tag:/qviyLLuyp06N4suDy4XQA==,type:str]
    smtp-password: ENC[AES256_GCM,data:yqGt4Iqt4Hpgv6taCY2M/QgI0ic+kjio0ix21+DQOZKMfLf3NO9umk9E40CjXZZipjIn/1BHll6+OsO5zUJ19HvFf++h,iv:SHwu6QiYlA1qK1Ey4qS+sN6vQ093yqILUwouoD89Ris=,tag:U29llIoOdIgntwEhUb25Ww==,type:str]
    smtp-host: ENC[AES256_GCM,data:yHOm+HnoSBjKQ79U4CAe9MA=,iv:wNXpGmtQYJGEwpmX6HAAvCGEyP356JaSsD8hPRenH8E=,tag:6He7MxxRv6Oak3z1am2dGw==,type:str]
    redis-password: ENC[AES256_GCM,data:tIpJ/Y85Cb+R2ypNyp3+o90UDjSKMXmoBgHO0HxbqJw=,iv:8r633Qnx1DjShfsBb98mKe/0Q13v0oTwwhUbCWrR5Ug=,tag:IXHHxVCjlDPMkjrmVKOcfA==,type:str]
    postgres-password: ENC[AES256_GCM,data:EnYKFF9EgmFOMnqTty+nV07ILiFGDgTvb1fFoEZRHNE=,iv:M+qosMIfdYBK93I2vceDLdhaikVF6Wkt6gD5K9boUjg=,tag:AJxqoNVNP3Xt7PeRQDA83A==,type:str]
    nextcloud-username: ""
    nextcloud-password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T15:04:41Z"
    mac: ENC[AES256_GCM,data:KTCslxPm7i052SpW/5p9WuJ4ygu7+yn+lb1v+tvlbvDXfE6Ra834C/5ooLL5VZqAsX8AE6bf8bb8nelK2FdBC8rahUkxae6vy7uMjL8N2yk2rvT/zpiFqn8FICTN+NS7Q/+Wvu0Wb3a0MqMYzetntoNmEbCDV+E59WxpvGRdRcg=,iv:c0GumHF7DfEL6++U59O56DYZ9vX6cTKS+9Ucp7ROouo=,tag:d4otz1lF8tRYxDFOfxyEzQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
