apiVersion: v1
kind: Secret
metadata:
    name: opnsense-ipv6-prefix-update-secrets
    namespace: default
type: Opaque
stringData:
    OPNSENSE_API_KEY: ENC[AES256_GCM,data:RkFZLdsP+bnslmbhcsvt8YV5QFKm554XSocKvZSU4CchSGfYjwuUUVk3h4ZFRMGIyHdXGgRxsJBa0DIzR0ROThqX8uAUP4s3QagjavipSuE=,iv:ajhYw6VmWQ6YkO6lJ05hnxKwsd7lHA77jlHbhJxPE1A=,tag:EYugR6GR62b/Y66xwuAWgQ==,type:str]
    OPNSENSE_API_SECRET: ENC[AES256_GCM,data:p/qx/uhm48vbGdcQQJLfeAbBI+dsU27cDlYroRBdHYUWH/nVaxEhd/5UcdXMPTQOffZC8sdLVHCDzGZsP5PYGgbJBgPRk+jwy9QxMjB0O/4=,iv:ZBjnULzwJERp4NOHUiIj0WphPoa9dXb1CYD86rUtp/o=,tag:YU0Vtx2KaJC/pwF3q1e0PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T17:24:29Z"
    mac: ENC[AES256_GCM,data:1qbF4x4aEMRWPgVr1PAAn20BsP4DRlWublF/P1NWfmd3bhrdOhmhCNqhGEq78J3oy82CN3HP6mtrIwKDmFbFRZjE5cCzV5SMd6L5MGqReHQ+ejtvmcN5O76AUf6DopVQeAjGym2tmAlIIfgo/doD1vE4cTcH8xBaK9c6lXJiZBU=,iv:X/lQbDX+sY243jd6HssEGTeapbwLM/UqDm7xMqQBPZY=,tag:5Fn0aWxNxcLlKKvN5KGyRA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.3
