apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: default
type: Opaque
stringData:
    paperless-secret-key: ENC[AES256_GCM,data:LANS0/spd0PheqGqNkOhW6svTK9Lm+AbNHqmuGYuN7U=,iv:RvELZc/OOR3B8aMFK52qh2CKO4nOy9bqWr6NUYLvQa0=,tag:UP0rsGlI/jz/UykzXVp9Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T09:11:18Z"
    mac: ENC[AES256_GCM,data:LvSIrLGIs+8e3JVzx6ijMDMoHaiXMhVyXxO6TeBoEQqPRdWfsE2RrXfWLJI8Lmq1rg5lzjN9txCbPIEwhHgBiei1pxUhEN6icW1W+X4RPlbs5g6C/MJPH+0dDHAqWLhFOoc46HVuh4RINxxVvu4lZGiw/9ZKKZK3mOpqfyMem1Q=,iv:CgCIwoRoUjl8AwAf5pphLjpnEnujsVR+lqzNg3k/BfY=,tag:eKQgV+rds4Ci+As9QnMJiw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.3
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6gk2qOyHXFb0+INEQA==,iv:DX+6BLUzDnO9r5HA219u4gqfWCbYG7rJ59z5IftxNnU=,tag:eHEZm9zazZxoH4ckeiL8IA==,type:str]
    password: ENC[AES256_GCM,data:jaZ++j09Jhn4ElliKHuyc58U2HJVAsMwFUXKJK7uOFs=,iv:6IWEOUGXYjGwQprNrC4Jjf1mY+ANuGXVDOiezvP6vw0=,tag:d1jbB3oNOLlqNLgRy1lXSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T09:11:18Z"
    mac: ENC[AES256_GCM,data:LvSIrLGIs+8e3JVzx6ijMDMoHaiXMhVyXxO6TeBoEQqPRdWfsE2RrXfWLJI8Lmq1rg5lzjN9txCbPIEwhHgBiei1pxUhEN6icW1W+X4RPlbs5g6C/MJPH+0dDHAqWLhFOoc46HVuh4RINxxVvu4lZGiw/9ZKKZK3mOpqfyMem1Q=,iv:CgCIwoRoUjl8AwAf5pphLjpnEnujsVR+lqzNg3k/BfY=,tag:eKQgV+rds4Ci+As9QnMJiw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.3
