apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: default
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:LM8iS4TaN9fR2NOsnBc6uUV8eaW0ANDVwfQsuSn05t8=,iv:v7xHsUahx0YzlEANRQWMqvQ1H14+BRDAAw5pmI+TS0I=,tag:sq0SoE0aCbXMHh0RXnSIHw==,type:str]
    paperless-secret-key: ENC[AES256_GCM,data:LANS0/spd0PheqGqNkOhW6svTK9Lm+AbNHqmuGYuN7U=,iv:RvELZc/OOR3B8aMFK52qh2CKO4nOy9bqWr6NUYLvQa0=,tag:UP0rsGlI/jz/UykzXVp9Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T14:54:57Z"
    mac: ENC[AES256_GCM,data:WJvDENWzVx5QfHEVspAmELJLdKaK27AH/SyggbGxUZl/7RT1QRprWvpsiAbVJ63Jc6VQIqISzylDbu5rIy2ed3NBe7G1nG4oeRiHjvkm4pNEeISJ1N2RQkS3lkLiyxOAmCHgsCpItTl7XjWmDWVHjndDQwyXZIgIq7lJyezImr0=,iv:5w2aXAFcQJvwAf1oRmTFeaqHP6vDDQQUoYVG+rtAkYw=,tag:ER+LK7BRjGXgnOmNp4prBg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
