apiVersion: v1
kind: Secret
metadata:
    name: renovate-config
    namespace: renovate-system
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:eyzFWc9rai5xLEr/NcdTkQR/QeuGmT5WBTzWAhi7mEPz5pWddHTvqyaKPkCB7eE5KjAtdl+Mibs4Z158XQiENgnYAZa+Us+1MYRsGjF1NP+6tzEGbGbp8x7Y1mkeS/XJvLenU+cRPB81u/djErSLyDi4P9Rpv7bgNNBP9n6kzdR4MJBVS7KBgUBNLqg0TunQEo4sfJf+2xt5recSm6of+sDm+HyEV5AeLWcBQAn/ed038XV323w3R2tj7m184X7Qysp48lElTje2pH/+ndun1tdsu0QZ/C9qQQIp6sach0tsLN72nTjwS3CSnen/rQgtuyKsLA5ZgLHodVxRX4fSdiri+v9ewHHQZ7T2OsKNrU7kco9K0yCsIgddQxnb5U08UT3OfaOQp6w1cx8JmBQtf2pa1WGF4N4zDBsxz0gU3u/xeC3YKXvjfe6dp2cejQiJ8mekNLUp73pvSPEYAHBvzFsAOkdx1kjrA8kG//1MyuSIGmDDon1mAhTdgympacQXugTPIC4FBp6f2qWZopbX+rLCL07mtaX6c6ysp4AIki7pOGU4MeyFy+yCkvgJcZHY/oM/DkjToI1hJsa7WRXOzK5OYophClcP02RsttRI2s5yZ6paDBDFVI1Mt3m9ZAE=,iv:OZVBQ5UB3kDnjle74cDEuRNnSveO7ORpIrTQleMtQLM=,tag:fnwUOsRIaTCSpivrZZVJQg==,type:str]
    healthcheckUrl: ENC[AES256_GCM,data:pfyMH105/AF2VZ4PbRgfDZ92iYQRxDyI09+9Yt6KBgejT/qtnA04Y6A7jv84dtJFwoWAczFAXweLTrXSdON0zU/HabArt+NF+TzTUjNCOgZ58zmu9H0kggbq,iv:RdKF2oa6ybG3mF+NckvnkIHMo5C6pWdB7GuN5/OQB/M=,tag:tx7SCcGtP2xRhAiss8OzQw==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:m1g25Gme4i0P54bvM0uZHVBE6LFgivdkxucx4zRr0dwVLJCudCwEIW0R+S9zVrn7zXy56rfszzG83iqv5NoOnw==,iv:+zPgC4gqAR9UU3iDRL6DI+yN38+fecvZ5b+jPzdNRG0=,tag:QUz2hmacsi2JsT8e+tunAQ==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS05Jbjd4WFU3VTM1WURu
            eDUwNWRlM29INlQyWFdXUUtpUCthNHFmc2ljCnRpalo2b3o1bEg4OWtRYXEwNjNI
            aFJIbk4yZkV2STZ4ZWVnQ3loSVZBSUkKLS0tIDdyaTlDZW1Yb3FQV2M3QWRCcDFr
            UlVPbzFncjVVa0ZVRVpaRFRaeGFuQlUKS0RjsbiCyCnfWNZi8j8/jkE2rQi6m/b6
            cpaMCF/VgCVata9riXeK5X4n944GAtGBPsr2VVVYD0ry8ME82bWd6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T19:27:41Z"
    mac: ENC[AES256_GCM,data:ZKtOBzJ3TnfnGcrp9KFtZzD2LmhIvHH/Y5XIreF4kN56GhS9ETloNOE3qYWAKKV20k5U58WGC2I7TIS/19cbqPuu6fljO1VIPIxXoBKmgd0znUXz2fxV80lMUaBXc4wwLJpNtHQflhjoJzhCsnjrZPFbX8C0NUnlzR1ADXLkTas=,iv:yX6mxZe7rc2Hbne4nGIrpkaUhVFAA75SAaVlnpbeXk0=,tag:eulN+SaxXjiNfWn398FEEw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-github-token-secrets
    namespace: renovate-system
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:la6Zo52OfXSNWXzWNZ4l1w25T+Y=,iv:Fk0LTxFCvV8VJBcMTrcltehO1ssAdgQqlMzFhZdLI30=,tag:UYOlXsnAMpZ6a2lHhD4vig==,type:str]
    INSTALLATION_ID: ENC[AES256_GCM,data:yxb3VWWAYnE=,iv:KEdeXPYB80ubUcGi+KcGlFUQtATMA5waZkTPwLjFVy0=,tag:DmiyLBncqY5AIGxyeckynw==,type:str]
    healthcheckUrl: ENC[AES256_GCM,data:kSTKGJfQzpU3b1f1B4BJW2fn77R0I9FV5w16UfFT9KFWUCepFkysEAbrAIlq5hc3jVBQF8tkkv85vsgG33zHsYvl9MIVFVs9nueGvTA9SqIcuvgPSRgXj9BE0muR1pRKybHVTc2lTxE=,iv:tzwML+xUluz9+9V1vUzLiY/VLreeSVH5M0plxN+e6GI=,tag:uC0o+8/a1ClOKCLvxojYcg==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:olEVru/e2ZZjpiaXVtoRrDJubekf4vCB6/xf3l6t47HKq2tHrF9B9Rmo4EtFygb+mQUxnfDt2BPgFZWuRM8VlA==,iv:WNxlUOVXsaLBNkoyZ7Nu+N5l3jr8zPTIf6STOWOLjyk=,tag:+J4qriJpA8fkgO0DOey9Mw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS05Jbjd4WFU3VTM1WURu
            eDUwNWRlM29INlQyWFdXUUtpUCthNHFmc2ljCnRpalo2b3o1bEg4OWtRYXEwNjNI
            aFJIbk4yZkV2STZ4ZWVnQ3loSVZBSUkKLS0tIDdyaTlDZW1Yb3FQV2M3QWRCcDFr
            UlVPbzFncjVVa0ZVRVpaRFRaeGFuQlUKS0RjsbiCyCnfWNZi8j8/jkE2rQi6m/b6
            cpaMCF/VgCVata9riXeK5X4n944GAtGBPsr2VVVYD0ry8ME82bWd6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T19:27:41Z"
    mac: ENC[AES256_GCM,data:ZKtOBzJ3TnfnGcrp9KFtZzD2LmhIvHH/Y5XIreF4kN56GhS9ETloNOE3qYWAKKV20k5U58WGC2I7TIS/19cbqPuu6fljO1VIPIxXoBKmgd0znUXz2fxV80lMUaBXc4wwLJpNtHQflhjoJzhCsnjrZPFbX8C0NUnlzR1ADXLkTas=,iv:yX6mxZe7rc2Hbne4nGIrpkaUhVFAA75SAaVlnpbeXk0=,tag:eulN+SaxXjiNfWn398FEEw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: renovate-github-token-key
    namespace: renovate-system
type: Opaque
stringData:
    private-key.pem: ENC[AES256_GCM,data:HBXtpxs27SoqJinbXxv5WZaHvBpgy45oDsVmpvz0erEOHGcxpIBrcLvWSoOfWJNDdWghuKcrbT4Mbnuykc2A5TK08274Jox3d15DKMeuR7NiaaqiYhhUFtIiYynJAlHncCcASfG4xwwMhxefyhe9EgLMGxtexyqGFDibj10/GWKGsv62/+LAzEWJDdoaOHYEZgmWKvRm2Z3+h1L0pbXj5Bfw210YiHHbdEdPGtG7P9+7P2LwcOslnfVE4xe1UMeUm8GHdCwnsOoWtxtfXKscdTpVBHhF+Yi418jSr/hj4zCQf6YjZYz1iWkzI1ZFZwOlc1wgVp4KzRRMj2sKhAM9NaHB+ymI0GlFqkl5HBWZc878S+d+HSw+FFesFVliVK1ymzt6OGEcAbH/rUMOCou9QsE/bN5D3g5VKZjPrSmGvhCc/HfAN3Bwp/ETf4KCKiMOpPbIne939QkVNllKqiucF6JK0E60wm6TFK7SNLLAZYFv68xcFrwLeFu9EsXY+dPAauRTye87i+/YolamDQ9vy0Dj+y0VFE3j0b63I/LrgOyz3JslXyw/MFWzpu6BLSbWsR3Y/IXHwROMqE4dwskg80cRy4IfIRVhVJDF2mSz6HEICRSvCxOz+a1bwJrgZjwNf5BqF4K+uyHuimdAwBTks9Q3hsFGTxSf1uQNn6rkTcY1B4IcTL1OREzrWr/lqOwumbG4RIlqTMw27QwGqyMn5Fmua9IKFIcrZMtRHfMgaUGkwNj2Cy/GUEMYWAitPS8QUFWwlPnPDgN09h3YtqYvEuTJR/AKIzaHiL1pG386PFmtzkKXReQCusOBpOnNwgygS4CHX5F48TUpD0yFQnVrwmXYYDdW3+i3j6SBBsgbIzFalQea+p/X/JbOwYcJUsdCEZxxGqH0uBaoNGx6VIWcYNb00Q6LskRt/DceMT+FcScG7lfaKr6tpq2OAKdXEd7B/QXcDihqFJMRuNPbDoTL0Hp155AQQxCxq4Bph5MlJy6adEGqi5lES/1OHUzvEfwpsD4sUUSC99FRcTgJNsH/jb29b1k6/NPTzzpTFQNpo5yhiG3MUuWQOfnPOuFgw2fjtGLnPymY/tjHq1PvJkk02CA7Myfpd1qVxghb3YCGY4ygK7xHeAfRFdAX9vVPEMa7DTFeHvs5BpvUb4VLD1guNvAYMt+h+fuU5NkQJ9LS+DWtRbjnTAIKJ3CitxsjB3sYt1jCmlFr9EWuzWjKETE1LoOJ9NlmpXWBrZ5YkPe3hzxi3FRKvQyRhPr09EdnhCQ6b7Lym7KH+4jUpmgd9pj2M7XXkUMLUgb2oeg/R2dPkR1oL/A8Y1mxfWmjW4d58RPm9VXCPYDXBNq64pPFv/TD0sONG3TKqV/nUIS6iy16ZD2XbA6xZ2fwqFpUdqC2vWXrpt9t9E4x8+O5VyfKl8ermB7SMxcYR2zgz+VSc31mcjop44Qt36X0MtTYrk1lkOzGvWM10L5viAs8Oba9agYqzwEGzPLApgxfTeOeZsJas0a0QzYrMV5P0Q98emOKWvRg2heOnXA5mouxcquwetAyaaHKYNyNBzSWME9gSOUdKMDDP4SxBSu49gU8pY99ev5S7KBZCx5ZHWY8Vffrd0D9NsX4HZSWfnPhYfBWfuQaiCyl3csDpuTfzYzI6O3z98gdgCZaHV3fPzwj/hSxwSpjCrU94848udfHpOl9WRVvnvZwnM22DfD0WcNKgAKNQ9DHouNFhjQO4GQFtU6/DWRq+T76C2RXlLOWI2Z46lRuWOxYHOVy3QZGrBdMlf//kyCDeAUbf06XoGjgROgL1w/ixgMuLQFpU4jmgRgKeSkq6CbpfTSC1LFZmJy54dhe8OQgCnARB/A/X+384HNQs+RHRoXJbfaIJhN20RrG9XdjYv8YNL4zNud50QckPP5YKGVlkaSJ1mY3rMGBgGThZR8j9cgNM5V4Z1eHA+iOBUxNxqC/F8wDD9gZl97W5ncBL9SXzqpQ/MH12xB3FwIdW/4GhNAQTQ7R1oWLblsoEh74M23LmCHokguAsWIvRcIstJGBPM0d29b4Y8Ng3FL9LrBkSyzLB9ZKjB6KBOoAX4L+zlsVUVzPtOCGHZyAC8huktWQSPXlzdpo4cvdwfWqkyTWpHOaS18XslTBIS4JZnkBTPz4RP8Sp5fhLhV3wfUDteaT0ERv0vWIx7tEVee0nGJgZV+dJeyW//vw/EfHYFE9JkGVXgXISbIL4rhcAN1lOOI=,iv:NByP/ygjQVfzqLId9UdqiH5t7fnOQgrAAx+gskNfr+s=,tag:maujvCf4nPb489GdAKaaxA==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS05Jbjd4WFU3VTM1WURu
            eDUwNWRlM29INlQyWFdXUUtpUCthNHFmc2ljCnRpalo2b3o1bEg4OWtRYXEwNjNI
            aFJIbk4yZkV2STZ4ZWVnQ3loSVZBSUkKLS0tIDdyaTlDZW1Yb3FQV2M3QWRCcDFr
            UlVPbzFncjVVa0ZVRVpaRFRaeGFuQlUKS0RjsbiCyCnfWNZi8j8/jkE2rQi6m/b6
            cpaMCF/VgCVata9riXeK5X4n944GAtGBPsr2VVVYD0ry8ME82bWd6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T19:27:41Z"
    mac: ENC[AES256_GCM,data:ZKtOBzJ3TnfnGcrp9KFtZzD2LmhIvHH/Y5XIreF4kN56GhS9ETloNOE3qYWAKKV20k5U58WGC2I7TIS/19cbqPuu6fljO1VIPIxXoBKmgd0znUXz2fxV80lMUaBXc4wwLJpNtHQflhjoJzhCsnjrZPFbX8C0NUnlzR1ADXLkTas=,iv:yX6mxZe7rc2Hbne4nGIrpkaUhVFAA75SAaVlnpbeXk0=,tag:eulN+SaxXjiNfWn398FEEw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
