apiVersion: v1
kind: Secret
metadata:
    name: renovate-config
    namespace: renovate-system
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:saPsuAGGQuUQbx8MaG6uMUd3b5pCpojjhw7JDUfyUKnzIrWBJsgLrqhkVuV01DjTygMuIypAIk8/RUot5YpNOdm3g7j9zHG7JZMjLhE0XS+4FXLCRri8l7up8rKj/78pdscbtGQTjU2hGgnflzOMUYhpLKrTgW1M197jDZSRjmKM3I3+zWNLvHctFkVR1/nvTvR88An4B80Dg2r0BPF1LCMbF8PxmaW3xvlqPrt5A2ey9cD8WZH9i75An5/zfNeFPw6Q00LegnH81R4SkZd/LqgLpHCVWNkbeVsCgwaFUws9zyFU+cBQeL2dO+v6IPuc0RQqVsGvILU3CQjZn0Y4EGEiFEzpt92KuHQp9gZrRSJJVl4WF/COOUBVnfMpPKyuHq0dHQOpTfvpNunarJBAg1xff0lID6f08dnarA1cSyg9Uf0n79RB+FNDMvdRyysLYXXi5joUS1RFixZUxSSyIttKVNXcrAs1TUqiaPO+Rhxq6xVvSOXY2X011VYdJ/PVlPf7S6YrLfG/2TbEvPPRrNJ04d9n3AyqeTjojrEoagCeRt27tm2bwtBaLMgRQ8oS9ZbVB5ZIntH8cNSjcMXWnn92lgnfmjbG7jjgQdRFI6mquFwhvNR/gUV+uykHFI8PKj+EExMcyHO+fqhshLeiOwdIulaWOV5OVIQUSPKU8mrMR3GeiaGcGTtQuWgUEw6bxTLSfPc8OxZ6XmxbOKLIQN3i,iv:tow52Gaz3ig0p4uG1fjrP0yKsjIn0PJP7SjNHnhN7BI=,tag:X+mmTNKpQNkQwXbIhHHgCQ==,type:str]
    healthcheckUrl: ENC[AES256_GCM,data:Xrcj3Gaw55wUUxelFLGgWDXy9d8T4GsQ+6fyJGfx1HxcD2XRG9Kg/jQ5EW8sVY3K7NRm4Nmp4rs0vV2GPGDn/c/18W/5c1e9KP2t,iv:5VPcjd5Sx3C75nJAr0vCOEddigimloqRHgf4BGzgOi4=,tag:dHz83H6r8WERi9I8hzVG9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweWkyelowOEJsNFo1SjNx
            SmozdUY4VlVsVHFIZmxSdENGZG1VYW54VHp3Cnh2YS92c09SbnhQbXU5ODNMUWlQ
            UDFPaTZRaXViVm4xTDVhUjNYbmFHM2cKLS0tIEI5NVc1d3NnbG9GTnA3TmRrK0R2
            d1JtcXVxbGpXYldXQmlTazQrMFRQaVUKiYmXESiQF6rA+J+zC9ReGVFeiRBvvtGe
            WgAmZznt5qaeXiOfh38iVqt6bY4q/1pPSaPHXJxd6jXIX+SsbX0MlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T19:25:10Z"
    mac: ENC[AES256_GCM,data:hDNAuVBrE1KkQkXr26CSMVD97B5d83fYdcLXkGNYDeoUejpBnzCFbWGOiI3f0BcO5OJKnmqzqNFbh8g/UqQw4KpwSA0xHve3ZkjU7WneVvI8qaBFD5IrfZd1SjnsECFL8o6APrgF8CubitTZPPKdxNwbRRhfH8dJCE0h/7ykJ4o=,iv:y33fxiMPhSN7Tt6sHYsb22xxpQ3cCfQ3ozyNyMO0O9M=,tag:fz3SIMfbYWEKxGUnQsp2tw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
