apiVersion: v1
kind: Secret
metadata:
    name: scrutiny-influxdb-admin
    namespace: monitoring-system
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:AjBNMSvxFtwEyMM1mcSx+2dlXlnkKVetT6pXg5Jmkws=,iv:cwaimRpK4gTQjw/xTuztjlq+Nq1IwnHqVpjwGAXRQUI=,tag:iQqMkp++wd3Xojy9SeTuDw==,type:str]
    admin-token: ENC[AES256_GCM,data:aPpSRJ7guCVJqROTq2ztnsA/24VIBpkWUGkUeqTEDPU=,iv:3sxTdGC4R1lJtsdHxICKGy1W229P7BsklSv3Qplq29E=,tag:t/rkiC1wQTGPP8eSQD8jrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T07:41:52Z"
    mac: ENC[AES256_GCM,data:5JvxtDfNi9froPrL/pf2MBBA4/VSj94jvtXEVXi/lP7OvACfE/3PB1cOVDPYeEEM4SeMol827KB6V6MaNpa4RtE6PEJiAPvu4/abuf4mpjNnrD1du+mcLQx/msWMGWsRJm/1/SD4kl4KRnC8WxoDPZT0Vy0aMc0tX4uM4xQZbEU=,iv:LXY/lpSkJED3UFBU5wboNZV/CxqN6mim//KNaXXUFGA=,tag:lg5Gk0ZdkuOzUrCX47hfmg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.4
