apiVersion: v1
kind: Secret
metadata:
    name: soundcloud-scraper-secrets
    namespace: default
type: Opaque
stringData:
    API_AUTH_METHOD: ENC[AES256_GCM,data:HdyzYDJr,iv:GJwW3H9iRXc2seJteKQCgoJ7oHSkFbhyogawqgGgad8=,tag:0y6WAaXcwOcEhxK5/eHNWg==,type:str]
    API_CLIENT_ID: ENC[AES256_GCM,data:fQFGh8VGczl9mnGQjQMEB0g6G9OMUeEg1uZ0jCH33NE=,iv:tkwTRZyJXLhy1q3qDPGnFvW0ykcN48rT5z6wnvBCYxs=,tag:6HGGAVQs75RDoP0FJMpcmw==,type:str]
    API_CLIENT_SECRET: ENC[AES256_GCM,data:Ew48/i7y8Duc2qk6w7gGY9OzZ3R/0gv9zuojUUhYU04=,iv:XY9PjIW6Rcb77Lspm0v/eOwO8uFZbZgRbdG5CXr7Irc=,tag:KpHI0+xyafr7BY9ZhBugUg==,type:str]
    API_REDIRECT_URI: ENC[AES256_GCM,data:JYQD4MJK4ohoVZEPbX+ubOX75HSXRqlJubc=,iv:RRH/xkYyB9NDJOG+ZO9pcUjkl8+1hfcZV0yDnxvNUDM=,tag:lNpAhsxIeIG6XDGA3MDulw==,type:str]
    WEBHOOK: ENC[AES256_GCM,data:3ovF8LLUTBYxQb8uuoIMnHnQ752EyJGjd5+1/uMveLU7ffXp2580Zjl8makkaZgLJueMOtKt9PW1tr8bH8Ik8leIoGo4,iv:9QAjE+RzwbBDhU3v7/4OE9TSdYU9AZJJ+/1ITVhwfNA=,tag:VPMhZ95sqpEWDKn4Mtz2KA==,type:str]
    healthcheckUrl: ENC[AES256_GCM,data:PdcLBCnlpHz4dltY+R+tB0g4S0+Mkdnr5HLbCBAfPzkrbVbr8sANNvvTCNT73CNF71aM/UsVQHZfUHkXU5lkJrfixo+WsrGQs4Ni3+niCvvWR0VO7cFPpGsFKzLJpWOJW8xXdQ==,iv:y35nI24VPK1p6G4w5WDU7UaoyYeNXRrh0K+/c6KUh1I=,tag:D/9GIQLxyxWoPAbO5ytqVA==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:JbOLdqhEYDAS2rQglcklGcTpIi2J0I/4wrNPi/gEBSIOVSAqNLCIGia6DqZCUPDddefk1Xxd+hH+89GPscVG7w==,iv:hDM5y35Q+c/oQ1VkWx9pXuAU25gekjwk3oYgjMHzOUU=,tag:NSpilSZPG+ZGPlL8yX1xNw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T19:32:32Z"
    mac: ENC[AES256_GCM,data:LCV/+WkCgs/h/RzOsbO9IQ6sR8KCzG56jeEM2MzQe2eAGwewQK1GDobYyHYeRMLBEFGC3DbTqDmGDDlteh1AyfFxhK+drT30h+RmudjjaybickkgKzVtN7n+Q1MlrIkFjk3PbA2kWakCwCZ8bR+rgoxjeUCJBnk6jzUdxmE66ro=,iv:QVC/vQbSGaUxWUtm+JGwmdMVdeVEGxShhrIlwTrewAU=,tag:NAID9EzIimArTB6u53gIyg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
