apiVersion: v1
kind: Secret
metadata:
    name: unifi-secrets
    namespace: default
type: Opaque
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:srYSqnCpK5YteRf7C/c8XRgw/CX9nQa/tjn5oV1IZkk=,iv:11R9ZSHz3HmI65db2h/pAJjJMm/ep/Id4qPwFi6LdCk=,tag:0/1XBszEjTMiZMRNsjgfOQ==,type:str]
    mongodb-password: ENC[AES256_GCM,data:tHc78+SpoZLHpsBjswTSQLJARhT5DAeI3J7l6ekXjGw=,iv:cDf3GzhwXyWwyL7Tni0pZJuULu2uOq4gr/OgSfYUVvM=,tag:uS9Q0P8sE4Lc1bmJH/Twvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTTRTcjJqc0RqVjhMdlMw
            RkJZR3NWdFd5OXBiYTZWNyt4RmtYS1BObDE4CjZ0RTducjJic09HbDFWMjQ0MEo2
            WGs5c2g1ekFJN1RWMU43cnVPdUs2UUkKLS0tIGNONXF5Q0xySGxCZmY5WmZ3TWxz
            WWJkODM2MnlKYjNtbmhid2RtWEVMSXMKug2eZ48DNLnQ5Nnr33R6hXRD5ZgviPaQ
            orm4XtmUswWhWWHL86Y6QgdX8qJmvXRojquAzUditKQM86QUP4CYrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T13:37:22Z"
    mac: ENC[AES256_GCM,data:Gk+MS5ItS9ZgKS+34+hr+D9+FINUGFPqibhR2BOoaXFDPVwY/iRA4Fv8VLLHmV9tyTvAcKj5uSuuRuk17pDctaYAJ83F5g3OZpUYSNgDRr9+IbQJU8xceffTfSLqWnEyExjKVfVJMy6axAhhy9oMADAEdvDi+vrx8/qXN9GMnpA=,iv:mRCACqVldrW/VbhtkoWCbs/P/VyygIqNtfzHc+c+8Fw=,tag:/Gvt8kwxxBoqFrrDP9uN0w==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.9.2
