apiVersion: v1
kind: Namespace
metadata:
    name: longhorn-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCamlFaHNWbUcyZ2xXaGh1
            cFhmTUMvQm1iaFRUQVhqWGRJQStXQ1E3K2lrCkdOMi9QMjVWQ3FJN25zN3Y1TnJV
            YytoMzJSZXZxdWY4VzRGZytjaFBMVWsKLS0tIENBYzYvRG1zditLTFFuazkvSm5Q
            YkdmN1JJWlBxMFNBUVZyeXRkVWFRUEUK41U8lyn683AhMaBVl/5bSLgtNK4aZTFq
            PYRAWWG/u5slJQxQETXzvA2axsKmEoptRJEdP8d6ZM1WFAVycITzyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T15:07:22Z"
    mac: ENC[AES256_GCM,data:WlyJuwe2vEqvj73ATyh8Jkos5uBwZoFX/fVuh5oxZBce+cF2lFcTbOSBf2RW/8TDSfMzxIQmBBQK91TKsWUMrqk214rlAvwpvmHJ25qiNdvE7Om1Od4nP1qJ2Eedn6dCs3rTfS/kCkBruSnLytNGeiV+/HjNv+MjZn6jwqY7jjk=,iv:g6eujgM2L9U0DQl+Dokdrn7IhXAR5EhsTd8BvKbqga4=,tag:RTKDM2YnkvAo4q8rYP5uPg==,type:str]
    pgp: []
    encrypted_regex: ^.*(host|hostname)$
    version: 3.9.2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: longhorn
    namespace: longhorn-system
spec:
    url: https://charts.longhorn.io
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCamlFaHNWbUcyZ2xXaGh1
            cFhmTUMvQm1iaFRUQVhqWGRJQStXQ1E3K2lrCkdOMi9QMjVWQ3FJN25zN3Y1TnJV
            YytoMzJSZXZxdWY4VzRGZytjaFBMVWsKLS0tIENBYzYvRG1zditLTFFuazkvSm5Q
            YkdmN1JJWlBxMFNBUVZyeXRkVWFRUEUK41U8lyn683AhMaBVl/5bSLgtNK4aZTFq
            PYRAWWG/u5slJQxQETXzvA2axsKmEoptRJEdP8d6ZM1WFAVycITzyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T15:07:22Z"
    mac: ENC[AES256_GCM,data:WlyJuwe2vEqvj73ATyh8Jkos5uBwZoFX/fVuh5oxZBce+cF2lFcTbOSBf2RW/8TDSfMzxIQmBBQK91TKsWUMrqk214rlAvwpvmHJ25qiNdvE7Om1Od4nP1qJ2Eedn6dCs3rTfS/kCkBruSnLytNGeiV+/HjNv+MjZn6jwqY7jjk=,iv:g6eujgM2L9U0DQl+Dokdrn7IhXAR5EhsTd8BvKbqga4=,tag:RTKDM2YnkvAo4q8rYP5uPg==,type:str]
    pgp: []
    encrypted_regex: ^.*(host|hostname)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: longhorn-ingress
    namespace: longhorn-system
spec:
    interval: 1m
    chart:
        spec:
            chart: longhorn
            version: 1.7.2
            sourceRef:
                kind: HelmRepository
                name: longhorn
                namespace: longhorn-system
    values:
        ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
                external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:ZI83ldWsILlM4T1OPg7/XEYmNz+w,iv:oNLfs8TONzCTvm19ZOkx+SNmnm3u7Kuj4DuIYhOo7hg=,tag:RVm8EuY3un0Utu2n7daLxw==,type:str]
                cert-manager.io/cluster-issuer: letsencrypt
            host: ENC[AES256_GCM,data:oGROfBOI7aYcpEgv9jy0M2MXQcnJ,iv:2g5ZgSxZbHN1fM1edtqc9i8zkmXISHrbR4vAeJ81oaM=,tag:foEy2FAYtp30m2axCoAkvA==,type:str]
            tls: true
            tlsSecret: longhorn-tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCamlFaHNWbUcyZ2xXaGh1
            cFhmTUMvQm1iaFRUQVhqWGRJQStXQ1E3K2lrCkdOMi9QMjVWQ3FJN25zN3Y1TnJV
            YytoMzJSZXZxdWY4VzRGZytjaFBMVWsKLS0tIENBYzYvRG1zditLTFFuazkvSm5Q
            YkdmN1JJWlBxMFNBUVZyeXRkVWFRUEUK41U8lyn683AhMaBVl/5bSLgtNK4aZTFq
            PYRAWWG/u5slJQxQETXzvA2axsKmEoptRJEdP8d6ZM1WFAVycITzyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T15:07:22Z"
    mac: ENC[AES256_GCM,data:WlyJuwe2vEqvj73ATyh8Jkos5uBwZoFX/fVuh5oxZBce+cF2lFcTbOSBf2RW/8TDSfMzxIQmBBQK91TKsWUMrqk214rlAvwpvmHJ25qiNdvE7Om1Od4nP1qJ2Eedn6dCs3rTfS/kCkBruSnLytNGeiV+/HjNv+MjZn6jwqY7jjk=,iv:g6eujgM2L9U0DQl+Dokdrn7IhXAR5EhsTd8BvKbqga4=,tag:RTKDM2YnkvAo4q8rYP5uPg==,type:str]
    pgp: []
    encrypted_regex: ^.*(host|hostname)$
    version: 3.9.2
