---
- name: install, configure and auto-start power auto-tune
  block:
  - apt:
      pkg: powertop
      state: present
  - cron:
      name: auto tune power
      special_time: reboot
      job: /usr/sbin/powertop --auto-tune
  - cron:
      name: force-enable WOL
      special_time: reboot
      job: |
        echo 'enabled' > '/sys/class/net/{{ ansible_default_ipv4.interface }}/device/power/wakeup'

- name: get human-readable device name
  shell: |
    dmidecode -t 1 | grep 'Product Name' | awk -F: '{print $2}' | xargs
  changed_when: false
  register: product_name

- name: force ASPM states for nodes with Realtek NICs
  # https://wireless.wiki.kernel.org/en/users/documentation/aspm
  # L1 seems to be bugged for the Realtek NIC, do only L0s (i.e. 0x41) for now
  block:
  - cron:
      name: force ASPM state of PCI bridge
      special_time: reboot
      job: setpci -s 00:1c.0 0x50.B=0x41
  - cron:
      name: force ASPM state of Ethernet controller
      special_time: reboot
      job: setpci -s 01:00.0 0x80.B=0x41
  when: product_name.stdout == 'ESPRIMO Q556/2'

- name: obtain all valid ASPM policies
  slurp:
    src: /sys/module/pcie_aspm/parameters/policy
  register: aspm_policies

- name: determine most efficient ASPM policy
  set_fact:
    aspm_policy: '{{ aspm_policies["content"] | b64decode | split | last | replace("[","") | replace("]","") }}'

- name: setup kernel parameters
  lineinfile: 
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(.*)"$'
    line: 'GRUB_CMDLINE_LINUX="mitigations=off nowatchdog pcie_aspm=force pcie_aspm.policy={{ aspm_policy }}"'
  notify:
    - update GRUB
    - reboot
