---
- name: reset cluster
  when: reset_cluster and reset_confirmation == "i-am-sure"
  block:
    - name: kubeadm reset
      command: kubeadm reset -f
      register: reset_result
      retries: 3
      until: reset_result.rc == 0
      changed_when: true
      failed_when: reset_result.rc != 0 and reset_result.attempts|default(1) == 3
    - name: remove k8s-related folders
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /var/lib/kubelet
        - /root/.kube
    - name: check if VIP is assigned
      command: ip addr show to {{ vip }}/32 dev eth0
      register: ip_addr_show_result
      changed_when: false
      failed_when: false
    - name: remove VIP from interface
      command: ip addr del {{ vip }}/32 dev eth0
      when: ip_addr_show_result.stdout_lines | length > 0
      changed_when: true

- when: "'controlplane' in group_names"
  block:
    - import_tasks: kube-vip.yaml
    - import_tasks: controlplane.yaml

- when: "'worker' in group_names"
  block:
    - name: set join command for worker nodes
      set_fact:
        kubeadm_join_command_worker: "{{ hostvars['controlplane1'].kubeadm_join_command_worker }}"
    - import_tasks: worker.yaml

- import_tasks:
    file: calico.yaml
  when: inventory_hostname == "controlplane1"
