---
- when: "'controlplane' in group_names"
  block:
    - import_tasks: kube-vip.yaml
    - import_tasks: controlplane.yaml

- when: "'worker' in group_names"
  block:
    - name: set join command for worker nodes
      set_fact:
        kubeadm_join_command_worker: "{{ hostvars['controlplane1'].kubeadm_join_command_worker }}"
    - import_tasks: worker.yaml

- import_tasks:
    file: calico.yaml
  when: inventory_hostname == "controlplane1"
