---
- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: os-base }
    - { role: os-power }
    - { role: k8s-base }
    - { role: k8s-controlplane, when: "'controlplane' in group_names" }
