apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: grafana
    namespace: monitoring-system
spec:
    interval: 1m
    chart:
        spec:
            chart: grafana
            version: 8.8.2
            sourceRef:
                kind: HelmRepository
                name: grafana
                namespace: monitoring-system
    values:
        adminPassword: ENC[AES256_GCM,data:WTN0/K+L2OSNhG4YcVeNJQw6+Mqlt8HTk4lZ91DhkIQ=,iv:7KTWIZ0NwQjS4ZAQc2Tiq1hKGmHIFOKbReRGPElvcTw=,tag:fB5SUdBw09y3roxkZ6sEpQ==,type:str]
        ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
                external-dns.alpha.kubernetes.io/hostname: grafana.kthxbye.cyou
                cert-manager.io/cluster-issuer: letsencrypt
            hosts:
                - ENC[AES256_GCM,data:VLbjr/VRzaJUdUjaw7gfMPdmEaA=,iv:+gR3no6F3wx9izevrwuPyBkrH1j6BUuY638zCR7kF5w=,tag:6/8TTex0NjYR69N4DpluqA==,type:str]
            tls:
                - secretName: grafana-tls
                  hosts:
                    - ENC[AES256_GCM,data:fDHTBHbhdHKyfELlzq6S7Vxi8VQ=,iv:e/J97tpPcjAe60Yg4NuKMXe02/9zH+l1tesqXbyWknM=,tag:QN9ISRamlr+NksH2P9qNwQ==,type:str]
        sidecar:
            dashboards:
                enabled: true
                searchNamespace: ALL
                label: grafana_dashboard
                labelValue: "1"
                folderAnnotation: grafana_dashboard_folder
                provider:
                    foldersFromFilesStructure: true
            datasources:
                enabled: true
                searchNamespace: ALL
                label: grafana_datasource
                labelValue: "1"
            plugins:
                enabled: true
                searchNamespace: ALL
                label: grafana_plugin
                labelValue: "1"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ1MzMUJPWlRiR3prZmJM
            RlRSY0l2eEpXbEhSMkdCRFJ6ZHpEMGY2REhnClFtT01wVmdOWWpzYStmSE5BSE1t
            SkhlenJXNEc0VUtwS1ZnRnZkYlR4UmcKLS0tIFJyZ0dycCswdXpBWENCc1lIa0xj
            R3I2ODkzbURrUHltREF3VFd6VStUV1UKTKcKUn+Y2Az8KmNOX9uQ4Ns48h+Udkyr
            djeUGHysvW6nbkWPvPtmRUXnQ4h0XbGGHsNZdxdnmaSMG5uBSqbf4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T08:42:04Z"
    mac: ENC[AES256_GCM,data:aGuf4cuRYs+zq3nA9PlOQSZ0AVvbwSP7UM11nbHn9bWLh/evL3zZHf6tfvb72kVUNp5QJrUdbDnmGvt3qF8E5nXiyAG5l8ZLhpSlEunHW21Gcevs8wKv2vl+55a7jZBukF6K6cmT7uc50GNtc3D6ZoUh7CTggpdZ2y2rUa70gMk=,iv:OgMU9DMYefo1MxHE5DUnbAaQDbWWJkkDI02kiWV/NxQ=,tag:kOJQ3JxbzOJdtXfrcMjPOg==,type:str]
    pgp: []
    encrypted_regex: ^.*(adminPassword|hosts)$
    version: 3.9.2
