apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring-system
spec:
    interval: 1m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: 67.5.0
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: monitoring-system
    values:
        alertmanager:
            ingress:
                enabled: ENC[AES256_GCM,data:CDf0Xw==,iv:YWKHNk7fKjPBjeuQPIMcEtnn21CrZ416qEbznST184o=,tag:Tmjpks3XloKvzkuO6C1YvQ==,type:bool]
                ingressClassName: ENC[AES256_GCM,data:xRJ7INQ=,iv:mOxOCo+3ZitEc3/PS2SWTAvKP4RGRqSNstjG5Ly5gNE=,tag:IAGYrTYIVTkpLc3iGWuZdg==,type:str]
                annotations:
                    external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:+jOQf1UFGpqhi0aQHwSXRYI3JOMCLY6upg==,iv:OJiKl8mtg3rMGRpClm+c7/5sXYk7rJKcJ3GYVVX1nGo=,tag:CZP2uOIhO7SvGpAVFr+2rQ==,type:str]
                    cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:9df3Mz7+91mrDgk=,iv:hcvvFWXnBC3xB0zf9MADVURM5GhJ9zoo81uzXfFyKpY=,tag:ahIXj95eJGKowQcpMrjgNw==,type:str]
                hosts:
                    - ENC[AES256_GCM,data:CAqMBDPKcrOHdpCzaeEAbbMpD3dYJkETjQ==,iv:BwzbB7f7V2HLT2T1tCzmjnUXh/zAN71LYtDxHmDNz9E=,tag:6e1j7zDCp2KTCBMMMqBhbg==,type:str]
                tls:
                    - secretName: ENC[AES256_GCM,data:DhhA976DhkOgOUCtPqX5rA==,iv:mH8XqMIlxpIlrjHIv2aduGblzjSJqLUnWlQxPUxeG3I=,tag:l1LFyWdNaoqdIoJP2pu4ZA==,type:str]
                      hosts:
                        - ENC[AES256_GCM,data:DV3OTABbmrxtMXoi1XVTeo09YNkNMs7lSw==,iv:byDINiPIMztjhK/Qg8Accecga2VFvdpY7uJDqe2jwGw=,tag:5FDGGBzAv46CWiVZ2m9SzA==,type:str]
            alertmanagerSpec:
                retention: 168h
                storage:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: cluster-scratch
                            resources:
                                requests:
                                    storage: 1Gi
        grafana:
            enabled: false
            forceDeployDatasources: true
            forceDeployDashboards: true
            defaultDashboardsEnabled: true
            defaultDashboardsTimezone: Europe/Berlin
            defaultDashboardsEditable: true
            sidecar:
                dashboards:
                    annotations:
                        grafana_dashboard_folder: kube-prometheus-stack
        prometheus:
            ingress:
                enabled: ENC[AES256_GCM,data:EJyljg==,iv:8feMeBdrj58OWsFsLNf2mKSKXcNdEoGyx0WnZpU0ntw=,tag:nsmMdYpmu5PCGGlob9Iz3Q==,type:bool]
                ingressClassName: ENC[AES256_GCM,data:/HqT66Q=,iv:9D13LMXinewl3CRP87ldvbN//sRH3Fc5jkuBN28P6ns=,tag:w2dcgBf1l9Xk8LHEDd5hKw==,type:str]
                annotations:
                    external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:0f5GrOpBAD2i10i+6pJtVnnf1sOXL7s=,iv:gvOAF9UOUWMj3LlXUzMewLoySGCm+zEkgJ+l68uuFNA=,tag:nVtpAepFc9+wkdOMU9yWJA==,type:str]
                    cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:5gMm/zqdOv6HoZo=,iv:4QQhJ2lVpB9oxZ5X5QF9NT50sIev6PaYvVrI9a8AwH0=,tag:6ZALLm851+Yh04IUn1vfOQ==,type:str]
                hosts:
                    - ENC[AES256_GCM,data:h/pTCqoUl39/Sn+zvGoO0b1jMREYS14=,iv:NWdvhdLqpfnM1k82WbBU1x967axZlTu0GcS1iSxT8Ro=,tag:Vnz61lru8ohwRhwwwwCuKg==,type:str]
                tls:
                    - secretName: ENC[AES256_GCM,data:dTwmYHHjV45VX/6B5qw=,iv:8S7xpHZdYEanBuscAtmxjY1HYx/bZVM9iu0/ejcsi8A=,tag:xg3FOEx4AviCzQEmT6XWQw==,type:str]
                      hosts:
                        - ENC[AES256_GCM,data:dFVOgzzHmUog2GnfebeotGTS/YjGNCs=,iv:7g9mMxLKYrTSX98dNQiqVHA0QAiWCKoD8Tc1enlL7ak=,tag:5jCcmMjuLgRoPz0z4vX62g==,type:str]
            prometheusSpec:
                retention: 90d
                retentionSize: 250GiB
                storageSpec:
                    volumeClaimTemplate:
                        spec:
                            storageClassName: nas-replicated-hdd
                            resources:
                                requests:
                                    storage: 250Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WlFKQm9Od3diSGhsUVdX
            VW9US1ZKdCsvdFN3UUNMdHNWak42akZSTkVvCmsxbktsMUIxRmFmZ2o2aHBjOUxn
            SGo5bGdKYnFKOGxOa2lKdTNpb2RnUzAKLS0tIG1BRG1aOEduZUFPSCtjWGo5RytP
            eUw2dmJ3ZEFHQ1hZdlJJaTZsZ3V6NHcK2nAd+pD0RUIn6XUNfcI4Du/tbVGJSAQT
            GECySg7LkeWTCfnR1qyru8vUkHaSBdC43lc9VWGuyTK0hZPfe38G4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:48:36Z"
    mac: ENC[AES256_GCM,data:PjnWaM57hZUP6sKXx753mqukN/CcfFMmhhoRDidYAPBy71VpSkiAiwxLYhdtQPhMhcXw3nwBp0cUbK8FzMK+lJ3yJkTgknrKEXS2fOzX5hXvgLLBiak/Cs07VI9e3k0kPgBmVG/HGzqEVnTuZsm+m1SP9YESKTfx0bh/2uBj6bk=,iv:+iNh+0o2eJxGoAseTecsKDX385VsSbt6TNvW69vak+8=,tag:LQk1fJxCNp9VpaweK1RA9Q==,type:str]
    pgp: []
    encrypted_regex: ^.*(ingress|adminPassword)$
    version: 3.9.2
