apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: grafana
    namespace: monitoring-system
spec:
    url: https://grafana.github.io/helm-charts
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc3Fjc3VvNHZkOXo2MWZl
            YnliUG5LcU1TanhrQjdGbjhrRzJONUZBazNVCkFyRHhMd3dkRDhFc2txblNsUzU3
            VW4xZUZhclBTa0JVUU10ZGUwOFRZcWsKLS0tIFQvZTZwWE1UYVNORTFFMlg3c1Bh
            SWlRYWUvbHB5d1RkK2ZpSFRkTGMxZkEK7xQXBGF0rYwdB1IpBcF60XfIBRhS68ep
            xhUZJXsfNlX5rMhxYOv7jEu+koY/ccv9y+IPbMfeQKOp+MUSuK1xCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T11:48:06Z"
    mac: ENC[AES256_GCM,data:3auv8Jt7V1P9niHYBVvVJtZtwReHnh2Ub9sj8ZAeDR/EgGMHsTV1M1jdUP0ni7QxkFvmxHsvdYOFjyGc7o0X+jAxmGGtlqQ7J9rQxhAdWObrzcx7KYeu/B38ZA6mf/fDPz5lfj5X5TwFNlG7bHPMre+K4DbZAH4RAG8eHCUd1wk=,iv:vEdk8EGl9OHRsz0hypYXq5IUPy6VNsgCSK43zZrxXNs=,tag:k7aSkJFHjTk8ouM726a+pA==,type:str]
    pgp: []
    encrypted_regex: ^.*(hosts)$
    version: 3.9.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: loki
    namespace: monitoring-system
spec:
    interval: 1m
    chart:
        spec:
            chart: loki
            version: 6.24.0
            sourceRef:
                kind: HelmRepository
                name: grafana
                namespace: monitoring-system
    values:
        deploymentMode: SingleBinary
        loki:
            storage:
                type: filesystem
            commonConfig:
                replication_factor: 1
            schemaConfig:
                configs:
                    - from: "2024-04-01"
                      store: tsdb
                      object_store: filesystem
                      schema: v13
                      index:
                        prefix: loki_index_
                        period: 24h
            pattern_ingester:
                enabled: true
            limits_config:
                allow_structured_metadata: true
                volume_enabled: true
            ruler:
                enable_api: true
        gateway:
            enabled: true
            ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                hosts:
                    - host: ENC[AES256_GCM,data:b+cWDn3b1DslB1g7n3ZaEqA=,iv:CldqaV2HOvilxaOe62senZVIkE4BZX8S+IjhvD7UyRo=,tag:Oudcw2aoiVoxgfgou2LmEQ==,type:str]
                      paths:
                        - path: ENC[AES256_GCM,data:TA==,iv:dEuD+plYIxgwu3APTMfnuEJSkI65StxP0e5yKeRrYZg=,tag:bZ2G0XaUuOCyWyie2d0tVg==,type:str]
                          pathType: ENC[AES256_GCM,data:DAQIOHqQ,iv:BTE56Xp5+dRkwzutDjPC2HrjtrPPDXRLo9ICX/hKx+E=,tag:o6gz+YcZO6LJ+2sddLUX7A==,type:str]
                tls:
                    - hosts:
                        - ENC[AES256_GCM,data:jbfR5VWihYKKOVGOID2aR6M=,iv:NWlJxAwT5Fm5AIOGy20N1sSGnU9fXtv9c7Z08O/0lLc=,tag:wcusfhtI6A8Y9AtTDs8Vkw==,type:str]
                      secretName: loki-tls
        singleBinary:
            replicas: 1
            persistence:
                size: 500Gi
                storageClass: nas-replicated-hdd
        write:
            replicas: 0
        read:
            replicas: 0
        backend:
            replicas: 0
        ingester:
            replicas: 0
        querier:
            replicas: 0
        queryFrontend:
            replicas: 0
        queryScheduler:
            replicas: 0
        distributor:
            replicas: 0
        compactor:
            replicas: 0
        indexGateway:
            replicas: 0
        bloomCompactor:
            replicas: 0
        bloomGateway:
            replicas: 0
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc3Fjc3VvNHZkOXo2MWZl
            YnliUG5LcU1TanhrQjdGbjhrRzJONUZBazNVCkFyRHhMd3dkRDhFc2txblNsUzU3
            VW4xZUZhclBTa0JVUU10ZGUwOFRZcWsKLS0tIFQvZTZwWE1UYVNORTFFMlg3c1Bh
            SWlRYWUvbHB5d1RkK2ZpSFRkTGMxZkEK7xQXBGF0rYwdB1IpBcF60XfIBRhS68ep
            xhUZJXsfNlX5rMhxYOv7jEu+koY/ccv9y+IPbMfeQKOp+MUSuK1xCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T11:48:06Z"
    mac: ENC[AES256_GCM,data:3auv8Jt7V1P9niHYBVvVJtZtwReHnh2Ub9sj8ZAeDR/EgGMHsTV1M1jdUP0ni7QxkFvmxHsvdYOFjyGc7o0X+jAxmGGtlqQ7J9rQxhAdWObrzcx7KYeu/B38ZA6mf/fDPz5lfj5X5TwFNlG7bHPMre+K4DbZAH4RAG8eHCUd1wk=,iv:vEdk8EGl9OHRsz0hypYXq5IUPy6VNsgCSK43zZrxXNs=,tag:k7aSkJFHjTk8ouM726a+pA==,type:str]
    pgp: []
    encrypted_regex: ^.*(hosts)$
    version: 3.9.2
