---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: cluster-scratch
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
    numberOfReplicas: "1"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: cluster-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
    numberOfReplicas: "1"
    dataLocality: strict-local
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: cluster-replicated
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
    numberOfReplicas: "3"
    replicaAutoBalance: least-effort
