apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt
    namespace: cert-manager-system
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: letsencrypt@${SERVICE_DOMAIN}
        privateKeySecretRef:
            name: letsencrypt
        solvers:
            - dns01:
                cloudflare:
                    email: cloudflare@${SERVICE_DOMAIN}
                    apiTokenSecretRef:
                        name: cloudflare-api-token
                        key: api-token
