apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager-system
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ydWRCR3qCVL4ODRYiHIM+ndnf8CauR+jCkqUUoSn1B2XF9n+R/p1lw==,iv:/NrUAhj1YrOnjXz1IDbSrsxKTO4yUcNkaV6N5PIUrgs=,tag:CKcy+E3vXGqOrbAZyVt1Hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRUlHQnc2Qnp2YXlWSFNG
            aTR0ZHl0WmtyYlZwczhwdGZ1WjFaSEh5SVNrCk43bGFOY0M0ZUU1SzJlbDBaQjFT
            bDZDMHRPYXdnalZXYnFpZmg2RVFtc1UKLS0tIHZkRWI0anBqN2lrM0JXeStmemZM
            cjJDczdDR2dTSGd0ZmtqSkMzb1ZBOWMKLttbBh1qMa0TI/5JoGTKVuaGzZMNhDj/
            8fpvCNQbs8GwMI2CuvurIjwqnhkYFg1ozq0uk9edu8fr+0QXeNbz7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T16:23:45Z"
    mac: ENC[AES256_GCM,data:4OgGWdkIswgCaScPTAb9HHT8Bkr6DH+0VBxdxig4SIF55r/f2hbYNpdY8P7DiVCJKMOCmYk8uLjHKsARkT6p2wysJwrxRhLCBXxJx0ECxEKU/UFhNemDLEjYItxh7O+ZgZNc3YNh4M3Gc6o6rt5T+VXLijWCEcMMrqjp3pUfoIg=,iv:U5nGMThgaB4zF7D0fbBmEj4dDniquQO5bDAGl9Kse8Q=,tag:JNx4Y5BI3bqeKsNoapcoLQ==,type:str]
    pgp: []
    encrypted_regex: ^.*(email|api-token)$
    version: 3.9.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt
    namespace: cert-manager-system
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:RApv5U4rcKAx6xoxH5bI1spB6y8eAnvU,iv:Hp0sD255Gl3lD6/esWdduTTwkYpu/NzOErvy1820V74=,tag:F0cebozfjBreTRfvq+gdmA==,type:str]
        privateKeySecretRef:
            name: letsencrypt
        solvers:
            - dns01:
                cloudflare:
                    email: ENC[AES256_GCM,data:N05w2CMED9+ku0bJpdczkEIR8wXIUz8=,iv:kqCWOpdR4MSZpJpoTm6TOYaB2Jd+1+K4tI62zXOMa6g=,tag:EAcJxWBOqwFcVjRGCu5RUw==,type:str]
                    apiTokenSecretRef:
                        name: cloudflare-api-token
                        key: api-token
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRUlHQnc2Qnp2YXlWSFNG
            aTR0ZHl0WmtyYlZwczhwdGZ1WjFaSEh5SVNrCk43bGFOY0M0ZUU1SzJlbDBaQjFT
            bDZDMHRPYXdnalZXYnFpZmg2RVFtc1UKLS0tIHZkRWI0anBqN2lrM0JXeStmemZM
            cjJDczdDR2dTSGd0ZmtqSkMzb1ZBOWMKLttbBh1qMa0TI/5JoGTKVuaGzZMNhDj/
            8fpvCNQbs8GwMI2CuvurIjwqnhkYFg1ozq0uk9edu8fr+0QXeNbz7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T16:23:45Z"
    mac: ENC[AES256_GCM,data:4OgGWdkIswgCaScPTAb9HHT8Bkr6DH+0VBxdxig4SIF55r/f2hbYNpdY8P7DiVCJKMOCmYk8uLjHKsARkT6p2wysJwrxRhLCBXxJx0ECxEKU/UFhNemDLEjYItxh7O+ZgZNc3YNh4M3Gc6o6rt5T+VXLijWCEcMMrqjp3pUfoIg=,iv:U5nGMThgaB4zF7D0fbBmEj4dDniquQO5bDAGl9Kse8Q=,tag:JNx4Y5BI3bqeKsNoapcoLQ==,type:str]
    pgp: []
    encrypted_regex: ^.*(email|api-token)$
    version: 3.9.2
